//This file contains data and prototypes for latelinks. It is autogenerated by StructParser

//autogeneratednocheckin
#include "LateLinkSupport.h"

//Stuff relating to LATELINK_OVERRIDE_ProdSpecificGlobalConfigSetup(), defined in C:\src\Night\GameServer\..\Common\NNOCommon.c
extern void OVERRIDE_LATELINK_ProdSpecificGlobalConfigSetup(void);
typedef void ProdSpecificGlobalConfigSetup_LATELINK_FPTYPE_INTERNAL(void);
extern ProdSpecificGlobalConfigSetup_LATELINK_FPTYPE_INTERNAL *ProdSpecificGlobalConfigSetup_LATELINK_FP;
extern char *ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup(void)
{
	ProdSpecificGlobalConfigSetup_LATELINK_FP = OVERRIDE_LATELINK_ProdSpecificGlobalConfigSetup;
	TestLateLinkArgString(&ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING, "void ", "ProdSpecificGlobalConfigSetup");
}

//Stuff relating to LATELINK_OVERRIDE_entity_CreateProjSpecificLogString(), defined in C:\src\Night\GameServer\NNOLogging.c
extern void* OVERRIDE_LATELINK_entity_CreateProjSpecificLogString(void* arg0);
typedef void* entity_CreateProjSpecificLogString_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern entity_CreateProjSpecificLogString_LATELINK_FPTYPE_INTERNAL *entity_CreateProjSpecificLogString_LATELINK_FP;
extern char *entity_CreateProjSpecificLogString_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_entity_CreateProjSpecificLogString(void)
{
	entity_CreateProjSpecificLogString_LATELINK_FP = OVERRIDE_LATELINK_entity_CreateProjSpecificLogString;
	TestLateLinkArgString(&entity_CreateProjSpecificLogString_LATELINK_ARGSTRING, "char * Entity * ", "entity_CreateProjSpecificLogString");
}

//Stuff relating to LATELINK_OVERRIDE_isValidRegionTypeForGame(), defined in C:\src\Night\GameServer\..\Common\NNOCommon.c
extern bool OVERRIDE_LATELINK_isValidRegionTypeForGame(U32 arg0);
typedef bool isValidRegionTypeForGame_LATELINK_FPTYPE_INTERNAL(U32 arg0);
extern isValidRegionTypeForGame_LATELINK_FPTYPE_INTERNAL *isValidRegionTypeForGame_LATELINK_FP;
extern char *isValidRegionTypeForGame_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame(void)
{
	isValidRegionTypeForGame_LATELINK_FP = OVERRIDE_LATELINK_isValidRegionTypeForGame;
	TestLateLinkArgString(&isValidRegionTypeForGame_LATELINK_ARGSTRING, "bool U32 ", "isValidRegionTypeForGame");
}


#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
3
1 "ProdSpecificGlobalConfigSetup" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "C:\src\Night\GameServer\..\Common\NNOCommon.c" 23 0 "void " 
1 "entity_CreateProjSpecificLogString" "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "C:\src\Night\GameServer\NNOLogging.c" 28 0 "char * Entity * " 
1 "isValidRegionTypeForGame" "bool"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "C:\src\Night\GameServer\..\Common\NNOCommon.c" 160 1 "bool U32 " 
#endif
