#ifndef _GENERICMESHBITS_H_
#define _GENERICMESHBITS_H_

typedef enum GMeshAttributeUsage
{
	USE_EMPTY					= 0,

	USE_POSITIONS				= 1<<0,
	USE_POSITIONS2				= 1<<1,
	USE_NORMALS					= 1<<2,
	USE_NORMALS2				= 1<<3,
	USE_BINORMALS				= 1<<4,
	USE_TANGENTS				= 1<<5,
	USE_TEX1S					= 1<<6,
	USE_TEX2S					= 1<<7,
	USE_BONEWEIGHTS				= 1<<8,
	USE_COLORS					= 1<<9,
	USE_VARCOLORS				= 1<<10,
	USE_OPTIONAL_PARSE_STRUCT	= 1<<11,

	USE_ALL_GMESH_ATTRIBUTES = USE_POSITIONS | USE_POSITIONS2 | USE_NORMALS | USE_NORMALS2 | 
		USE_BINORMALS | USE_TANGENTS | USE_TEX1S | USE_TEX2S | USE_BONEWEIGHTS | USE_COLORS | USE_VARCOLORS |
		USE_OPTIONAL_PARSE_STRUCT
} GMeshAttributeUsage;

#define USE_TANGENT_BASIS_BITS (USE_NORMALS | USE_TANGENTS | USE_BINORMALS)

typedef enum GMeshTangentSpaceState
{
	TANGENT_SPACE_NONE,
	TANGENT_SPACE_INCOMPLETE,
	TANGENT_SPACE_COMPLETE,
} GMeshTangentSpaceState;

#endif
