#pragma once
GCC_SYSTEM
/***************************************************************************



***************************************************************************/

typedef struct StashTableImp*		StashTable;
typedef struct WorkerThread WorkerThread;

typedef enum TestStatus
{
	TEST_UNKNOWN,
	TEST_SETUP,
	TEST_RUNNING,
	TEST_RUNNING_CHILDREN,
	TEST_FAILED,
	TEST_PASSED,
} TestStatus;

typedef void(*TestCaseCB)(void);


typedef struct TestCase
{
	char testName[MAX_PATH]; //Full name of the test, including /'s for nested tests

	TestCaseCB setUpFunc;
	TestCaseCB runFunc;
	TestCaseCB tearDownFunc;

	TestStatus testStatus;
	char *estrReturnMessage;
	char *estrStackTrace;
	char *estrExpr;
	unsigned int errorLine;
	char errorFile[MAX_PATH];

	PERFINFO_TYPE*		piStatic;

	F32 elapsedTime;

	struct TestCase *pParent; //might be NULL

	struct TestCase **ppChildren;
	int iCurChildNum; 

	int iNumChildrenSucceeded;

	int iNumTestsSucceeded_recurse;
	int iTotalNumTests_recurse;

	//used as a bool. Needed for the rare group which has children and also its own run func
	int myRunFuncSucceeded;

} TestCase;

typedef struct TestHarness
{
	TestCase **testCases;
	StashTable testLookup;

	// Options
	U32 timeoutMs;					// If set, number of milliseconds to time out test after.
	bool disableThreading;			// If true, disable the test thread.

	char currentMatch[MAX_PATH];
	TestCase **runningTests;
	int currentTest;

	TestCase *pCurCaseBeingTested;	//points to the childmost state being tested

	F32 elapsedTime;

	WorkerThread *testThread;		// Execution thread.
	U32	testThreadRunning;			// If non-zero, test thread is running.

} TestHarness;

// Register a test with the test harness
void testRegister(const char *testName, const char *parentName, TestCaseCB run, TestCaseCB setup, TestCaseCB teardown);

// Fail a test, and give the resulting error message
int testFailFunc(const char *expr, const char *message,const char* filename, unsigned lineno);
int testFailFuncf(const char *expr, FORMAT_STR const char *messageformat,const char* filename, unsigned lineno,...);

// Various asserts used in tests
#define testAssert(expr) ((expr) || testFailFunc(#expr, "Test failed", __FILE__, __LINE__) ? 0 : 0)
#define testAssertEqual(x, y) (((x) == (y)) || testFailFuncf(#x " == " #y, "%d != %d", __FILE__, __LINE__, (x), (y)) ? 0 : 0)
#define testAssertStrEqual(x, y) ((strcmp((x), (y)) == 0) || testFailFuncf(#x " == " #y, "%s != %s", __FILE__, __LINE__, (x), (y)) ? 0 : 0)
#define testAssertPtrEqual(x, y) (((x) == (y)) || testFailFuncf(#x " == " #y, "%p != %p", __FILE__, __LINE__, (x), (y)) ? 0 : 0)

//used by autogenerated code to fake file/line numbers
#define testAssert_FileLine(expr, file, line) ((expr) || (testFailFunc(#expr, "Test failed", file, line) ? 0 : 0))

#define testAssertMsgf(expr,msg, ...) ((expr) || (testFailFuncf(#expr,msg, __FILE__, __LINE__, __VA_ARGS__) ? 0 : 0))
#define testAssertMsg(expr,msg) ((expr) || (testFailFunc(#expr,msg, __FILE__, __LINE__) ? 0 : 0))

#define testAssertMsgReturnf(expr,msg, ...) if (!(expr)) { testFailFuncf(#expr,msg, __FILE__, __LINE__, __VA_ARGS__); return; }
#define testAssertMsgReturn(expr,msg) if (!(expr)) { testFailFunc(#expr,msg, __FILE__, __LINE__); return; }

// Run a set of tests, all the ones that match the given string. Won't return until they're done
void testRunMatchedCasesEx(const char *matchString, bool onlyScanTopLevel);
#define testRunMatchedCases(matchString) testRunMatchedCasesEx(matchString, true)

// Find a test case with the given name
TestCase *testFindCase(const char *name);

// Report functions. Call them after a testRunMatchedCases call
int testReportToConsole(void);
void testReportToFile(char *fileName);

// Wrapper functions (that are also AUTO_COMMANDS) that will run a test for you

// Run a test string, and report it to a file
void testRun(const char *match);

// Run a test string, and report it the console
void testRunToConsole(const char *match);

// Run a timed test string, and report it and the profiler data to files
void testRunTimed(const char * match);

// Threading is enabled by default; call with false to disable.
void testEnableThreading(bool enabled);

// Set the per-thread timeout in milliseconds.
void testSetTimeout(U32 ms);
