#if !_PS3
#include "rt_xshaderdata.h"

// Copy and paste, then regex replace ^{.*}$ with \"\1\\n\"

// Note: vertex shaders in here do not currently go through the preprocessor

//////////////////////////////////////////////////////////////////////////
// Vertex shaders
const char dx_11_vshader_prefix[] =
"\n"
"cbuffer PerObject : register( b2 ) {\n"
"	uniform float4x4 projection_mat		: packoffset(c0);\n"						// view -> clip space	(Objects may have force far depth, this goes here)\n"
"	uniform float4x4 modelview_mat		: packoffset(c4);\n"						// model -> view space\n"
"}\n"
"\n";

const char dx_9_vshader_prefix[] =
"\n"
"uniform float4x4 projection_mat	: register(c17);		// view -> clip space\n"
"uniform float4x4 modelview_mat	: register(c21);		// model -> view space\n"
"\n";

const char dx_vshader_data_error[] = 
"struct VS_INPUT_ERROR\n"
"{\n"
"	float4 vPosition	: POSITION;\n"
"	float2 vTexCoord0	: TEXCOORD0;\n"
"	float4 cColor		: COLOR;\n"
"};\n"
"\n"
"struct VS_OUTPUT_ERROR\n"
"{\n"
"	float4 vPosition	: SV_POSITION;\n"
"	float2 vTexCoord0	: TEXCOORD0;\n"
"	float4 cColor		: COLOR0;\n"
"	float4 color0		: TEXCOORD2;\n"
"	float4 vertex_lighting: TEXCOORD7;\n"
"};\n"
"\n"
"VS_OUTPUT_ERROR error_vertexshader(VS_INPUT_ERROR v)\n"
"{\n"
"	VS_OUTPUT_ERROR o;\n"
"	float4 position_vs = mul(modelview_mat, v.vPosition);\n"
"	o.vPosition = mul(projection_mat, position_vs);\n"
"	o.cColor = float4(1, 0.5, 0.5, 1);\n"
"	o.color0 = float4(1, 0.5, 0.5, 1);\n"
"	o.vertex_lighting = float4(1, 0.5, 0.5, 1);\n"
"	o.vTexCoord0 = v.vTexCoord0;\n"
"	return o;\n"
"}\n";

const char dx_vshader_data_sprite[] = 
"struct VS_INPUT_SPRITE\n"
"{\n"
"	float3 position			: POSITION;\n"
"	float4 texcoord			: TEXCOORD0;\n"
"	float4 color			: COLOR;\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT_SPRITE\n"
"{\n"
"	float4 position_clip		: SV_POSITION;\n"
"	float4 texcoord				: TEXCOORD0;\n"
"	float4 position_vs			: TEXCOORD1;	// view space position, world space fog height interpolater\n"
"	float4 color				: TEXCOORD2;	// matches VS_OUTPUT_NORMAL to allow mixing normal VS and sprite PS for particles\n"
"};\n"
"\n"
"void sprite_vertexshader(in VS_INPUT_SPRITE vIn, \n"
"						 out VS_OUTPUT_SPRITE vOut \n"
"						 )\n"
"{\n"
"	vOut.position_vs.xyz = mul(modelview_mat, float4(vIn.position.x, vIn.position.y, vIn.position.z, 1.0f)).xyz;\n"
"\n"
"	// Transform to clip space\n"
"	vOut.position_clip = mul(projection_mat, float4(vOut.position_vs.xyz, 1));\n"
"\n"
"	vOut.position_vs.w = 0;\n"
"	vOut.texcoord = vIn.texcoord;\n"
"	vOut.color = vIn.color;\n"
"}\n";

const char dx_vshader_data_sprite_srgb[] = 
"struct VS_INPUT_SPRITE\n"
"{\n"
"	float3 position			: POSITION;\n"
"	float4 texcoord			: TEXCOORD0;\n"
"	float4 color			: COLOR;\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT_SPRITE\n"
"{\n"
"	float4 position_clip		: SV_POSITION;\n"
"	float4 texcoord				: TEXCOORD0;\n"
"	float4 position_vs			: TEXCOORD1;	// view space position, world space fog height interpolater\n"
"	float4 color				: TEXCOORD2;	// matches VS_OUTPUT_NORMAL to allow mixing normal VS and sprite PS for particles\n"
"};\n"
"\n"
"void sprite_vertexshader_srgb(in VS_INPUT_SPRITE vIn, \n"
"							   out VS_OUTPUT_SPRITE vOut \n"
"						       )\n"
"{\n"
"	vOut.position_vs.xyz = mul(modelview_mat, float4(vIn.position.x, vIn.position.y, vIn.position.z, 1.0f)).xyz;\n"
"\n"
"	// Transform to clip space\n"
"	vOut.position_clip = mul(projection_mat, float4(vOut.position_vs.xyz, 1));\n"
"\n"
"	vOut.position_vs.w = 0;\n"
"	vOut.texcoord = vIn.texcoord;\n"
"	vOut.color = vIn.color;\n"
"	vOut.color.rgb *= vOut.color.rgb;	//approximate srgb color values with gamma 2.0\n"
"}\n";

const char dx_vshader_data_primitive[] =
"struct VS_INPUT_SPRITE\n"
"{\n"
"	float3 position			: POSITION;\n"
"	float4 color			: COLOR;\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT_SPRITE\n"
"{\n"
"	float4 position_clip		: SV_POSITION;\n"
"	float4 texcoord				: TEXCOORD0;\n"
"	float4 position_vs			: TEXCOORD1;	// view space position, world space fog height interpolater\n"
"	float4 color				: TEXCOORD2;	// matches VS_OUTPUT_NORMAL to allow mixing normal VS and sprite PS for particles\n"
"};\n"
"\n"
"void primitive_vertexshader(in VS_INPUT_SPRITE vIn, \n"
"							 out VS_OUTPUT_SPRITE vOut \n"
"							 )\n"
"{\n"
"	vOut.position_vs.xyz = mul(modelview_mat, float4(vIn.position,1.0f)).xyz;\n"
"\n"
"	// Transform to clip space\n"
"	vOut.position_clip = mul(projection_mat, float4(vOut.position_vs.xyz, 1));\n"
"\n"
"	vOut.position_vs.w = 0;\n"
"	vOut.texcoord = 0;\n"
"	vOut.color = vIn.color;\n"
"}\n";

const char dx_vshader_data_primitive_srgb[] =
"struct VS_INPUT_SPRITE\n"
"{\n"
"	float3 position			: POSITION;\n"
"	float4 color			: COLOR;\n"
"};\n"
"\n"
"\n"
"struct VS_OUTPUT_SPRITE\n"
"{\n"
"	float4 position_clip		: SV_POSITION;\n"
"	float4 texcoord				: TEXCOORD0;\n"
"	float4 position_vs			: TEXCOORD1;	// view space position, world space fog height interpolater\n"
"	float4 color				: TEXCOORD2;	// matches VS_OUTPUT_NORMAL to allow mixing normal VS and sprite PS for particles\n"
"};\n"
"\n"
"void primitive_vertexshader_srgb(in VS_INPUT_SPRITE vIn, \n"
"                                 out VS_OUTPUT_SPRITE vOut \n"
"						          )\n"
"{\n"
"	vOut.position_vs.xyz = mul(modelview_mat, float4(vIn.position,1.0f)).xyz;\n"
"\n"
"	// Transform to clip space\n"
"	vOut.position_clip = mul(projection_mat, float4(vOut.position_vs.xyz, 1));\n"
"\n"
"	vOut.position_vs.w = 0;\n"
"	vOut.texcoord = 0;\n"
"	vOut.color = vIn.color;\n"
"	vOut.color.rgb *= vOut.color.rgb;	//approximate srgb color values with gamma 2.0\n"
"}\n";

//////////////////////////////////////////////////////////////////////////
// Pixel shaders

const char dx_pshader_data_sprite[] =
"\n"
"struct PS_INPUT_SPRITE\n"
"{\n"
"	float4 position_screen				: SV_POSITION;\n"
"	float4 texcoord						: TEXCOORD0;\n"
"	float4 position_vs					: TEXCOORD1;	// view space position, world space fog height interpolater fog_value if VERTEX_FOG\n"
"	float4 color						: TEXCOORD2;	// matches VS_OUTPUT_NORMAL to allow mixing normal VS and sprite PS for particles\n"
"};\n"
"\n"
"sampler2D texture_sampler : register(s0);\n"
"\n"
"struct PS_OUTPUT\n"
"{\n"
"	float4 color[1] : COLOR0;\n"
"};\n"
"\n"
"PS_OUTPUT sprite_2d_pixelshader(PS_INPUT_SPRITE fragment)\n"
"{\n"
"	PS_OUTPUT output;\n"
"\n"
"	float4 texcolor = tex2D(texture_sampler, fragment.texcoord.xy);\n"
"	float4 outcolor = fragment.color * texcolor;\n"
"\n"
"	output.color[0] = outcolor;\n"
"	\n"
"	return output;\n"
"}\n"
;


#endif
