#ifndef __BEACON_H_AST_H_
#define __BEACON_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \beacon.h
//autogeneratednocheckin

extern ParseTable parse_BeaconPathLogEntry[];
#define TYPE_parse_BeaconPathLogEntry BeaconPathLogEntry

extern ParseTable parse_BeaconPathLogEntrySet[];
#define TYPE_parse_BeaconPathLogEntrySet BeaconPathLogEntrySet

#endif
