#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_DynBitFieldStatic[];
#define TYPE_parse_DynBitFieldStatic DynBitFieldStatic
//Structparser.exe autogenerated ParseTable for struct DynAnimOverride
#define TYPE_parse_DynAnimOverride DynAnimOverride
ParseTable parse_DynAnimOverride[] =
{
	{ "DynAnimOverride", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimOverride), 0, NULL, 0, NULL },
	{ "Name",				TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(DynAnimOverride, pcName, 0), NULL },
	{ "bits",				TOK_EMBEDDEDSTRUCT(DynAnimOverride, bits, parse_DynBitFieldStatic)},
	{ "DynMove",			TOK_NON_NULL_REF | TOK_REQUIRED | TOK_REFERENCE(DynAnimOverride, hMove, 0, "DynMove") },
	{ "Bones",				TOK_POOL_STRING | TOK_STRINGARRAY(DynAnimOverride, eaBones), NULL },
	{ "SuppressionTag",		TOK_POOL_STRING | TOK_STRING(DynAnimOverride, pcSuppressionTag, 0), NULL },
	{ "DisableHandIK",		TOK_AUTOINT(DynAnimOverride, bDisableHandIK, 0), NULL },
	{ "Interpolation",		TOK_F32(DynAnimOverride, fInterpolation, 0), NULL },
	{ "End",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimOverride()
{
	int iSize = sizeof(DynAnimOverride);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimOverride, iSize, "DynAnimOverride", NULL, "dynAnimOverride.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynAnimOverride[];
#define TYPE_parse_DynAnimOverride DynAnimOverride
//Structparser.exe autogenerated ParseTable for struct DynAnimOverrideList
#define TYPE_parse_DynAnimOverrideList DynAnimOverrideList
ParseTable parse_DynAnimOverrideList[] =
{
	{ "DynAnimOverrideList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimOverrideList), 0, NULL, 0, NULL },
	{ "Name",					TOK_POOL_STRING | TOK_KEY | TOK_STRING(DynAnimOverrideList, pcName, 0), NULL },
	{ "FileName",				TOK_POOL_STRING | TOK_CURRENTFILE(DynAnimOverrideList, pcFileName), NULL},
	{ "DynAnimOverride",		TOK_STRUCT(DynAnimOverrideList, eaAnimOverride, parse_DynAnimOverride) },
	{ "End",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimOverrideList()
{
	int iSize = sizeof(DynAnimOverrideList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimOverrideList, iSize, "DynAnimOverrideList", NULL, "dynAnimOverride.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
