#include "textparser.h"

//auto-generated staticdefine for enum eAnimTemplateType
//autogeneratednocheckin
StaticDefineInt eAnimTemplateTypeEnum[] =
{
	DEFINE_INT
	{ "NotSet", eAnimTemplateType_NotSet},
	{ "Idle", eAnimTemplateType_Idle},
	{ "Emote", eAnimTemplateType_Emote},
	{ "Power", eAnimTemplateType_Power},
	{ "HitReact", eAnimTemplateType_HitReact},
	{ "Death", eAnimTemplateType_Death},
	{ "NearDeath", eAnimTemplateType_NearDeath},
	{ "Block", eAnimTemplateType_Block},
	{ "TPose", eAnimTemplateType_TPose},
	{ "PowerInterruptingHitReact", eAnimTemplateType_PowerInterruptingHitReact},
	{ "Movement", eAnimTemplateType_Movement},
	DEFINE_END
};
void autoEnum_fixup_eAnimTemplateType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(eAnimTemplateTypeEnum, "eAnimTemplateType");
}

//auto-generated staticdefine for enum eAnimTemplateNodeType
//autogeneratednocheckin
StaticDefineInt eAnimTemplateNodeTypeEnum[] =
{
	DEFINE_INT
	{ "Normal", eAnimTemplateNodeType_Normal},
	{ "Randomizer", eAnimTemplateNodeType_Randomizer},
	{ "Start", eAnimTemplateNodeType_Start},
	{ "End", eAnimTemplateNodeType_End},
	DEFINE_END
};
void autoEnum_fixup_eAnimTemplateNodeType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(eAnimTemplateNodeTypeEnum, "eAnimTemplateNodeType");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct DynAnimTemplateNodeRef
#define TYPE_parse_DynAnimTemplateNodeRef DynAnimTemplateNodeRef
ParseTable parse_DynAnimTemplateNodeRef[] =
{
	{ "DynAnimTemplateNodeRef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimTemplateNodeRef), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "index",					TOK_AUTOINT(DynAnimTemplateNodeRef, index, -1), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimTemplateNodeRef()
{
	int iSize = sizeof(DynAnimTemplateNodeRef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimTemplateNodeRef, iSize, "DynAnimTemplateNodeRef", NULL, "dynAnimTemplate.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynAnimTemplateNodeRef[];
#define TYPE_parse_DynAnimTemplateNodeRef DynAnimTemplateNodeRef
//Structparser.exe autogenerated ParseTable for struct DynAnimTemplateSwitch
#define TYPE_parse_DynAnimTemplateSwitch DynAnimTemplateSwitch
ParseTable parse_DynAnimTemplateSwitch[] =
{
	{ "DynAnimTemplateSwitch", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimTemplateSwitch), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "next",					TOK_EMBEDDEDSTRUCT(DynAnimTemplateSwitch, next, parse_DynAnimTemplateNodeRef)},
	{ "Flag",					TOK_POOL_STRING | TOK_STRING(DynAnimTemplateSwitch, pcFlag, 0), NULL },
	{ "Direction",				TOK_AUTOINT(DynAnimTemplateSwitch, eDirection, 0), DynMovementDirectionEnum },
	{ "Interrupt",				TOK_AUTOINT(DynAnimTemplateSwitch, bInterrupt_Depreciated, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimTemplateSwitch()
{
	int iSize = sizeof(DynAnimTemplateSwitch);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimTemplateSwitch, iSize, "DynAnimTemplateSwitch", NULL, "dynAnimTemplate.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynAnimTemplateSwitch[];
#define TYPE_parse_DynAnimTemplateSwitch DynAnimTemplateSwitch
//Structparser.exe autogenerated ParseTable for struct DynAnimTemplateDirectionalData
#define TYPE_parse_DynAnimTemplateDirectionalData DynAnimTemplateDirectionalData
ParseTable parse_DynAnimTemplateDirectionalData[] =
{
	{ "DynAnimTemplateDirectionalData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimTemplateDirectionalData), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "Switch",							TOK_STRUCT(DynAnimTemplateDirectionalData, eaSwitch, parse_DynAnimTemplateSwitch) },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimTemplateDirectionalData()
{
	int iSize = sizeof(DynAnimTemplateDirectionalData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimTemplateDirectionalData, iSize, "DynAnimTemplateDirectionalData", NULL, "dynAnimTemplate.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynAnimTemplateNodeRef[];
#define TYPE_parse_DynAnimTemplateNodeRef DynAnimTemplateNodeRef
//Structparser.exe autogenerated ParseTable for struct DynAnimTemplatePath
#define TYPE_parse_DynAnimTemplatePath DynAnimTemplatePath
ParseTable parse_DynAnimTemplatePath[] =
{
	{ "DynAnimTemplatePath", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimTemplatePath), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "next",					TOK_EMBEDDEDSTRUCT(DynAnimTemplatePath, next, parse_DynAnimTemplateNodeRef)},
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimTemplatePath()
{
	int iSize = sizeof(DynAnimTemplatePath);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimTemplatePath, iSize, "DynAnimTemplatePath", NULL, "dynAnimTemplate.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynAnimTemplateNodeRef[];
#define TYPE_parse_DynAnimTemplateNodeRef DynAnimTemplateNodeRef
extern ParseTable parse_DynAnimTemplateSwitch[];
#define TYPE_parse_DynAnimTemplateSwitch DynAnimTemplateSwitch
extern ParseTable parse_DynAnimTemplateDirectionalData[];
#define TYPE_parse_DynAnimTemplateDirectionalData DynAnimTemplateDirectionalData
extern ParseTable parse_DynAnimTemplatePath[];
#define TYPE_parse_DynAnimTemplatePath DynAnimTemplatePath
//Structparser.exe autogenerated ParseTable for struct DynAnimTemplateNode
#define TYPE_parse_DynAnimTemplateNode DynAnimTemplateNode
ParseTable parse_DynAnimTemplateNode[] =
{
	{ "DynAnimTemplateNode", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimTemplateNode), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Name",					TOK_POOL_STRING | TOK_STRING(DynAnimTemplateNode, pcName, 0), NULL },
	{ "defaultNext",			TOK_EMBEDDEDSTRUCT(DynAnimTemplateNode, defaultNext, parse_DynAnimTemplateNodeRef)},
	{ "Switch",					TOK_STRUCT(DynAnimTemplateNode, eaSwitch, parse_DynAnimTemplateSwitch) },
	{ "DirectionalData",		TOK_NO_TEXT_SAVE | TOK_STRUCT(DynAnimTemplateNode, eaDirectionalData, parse_DynAnimTemplateDirectionalData) },
	{ "Path",					TOK_STRUCT(DynAnimTemplateNode, eaPath, parse_DynAnimTemplatePath) },
	{ "Type",					TOK_AUTOINT(DynAnimTemplateNode, eType, 0), eAnimTemplateNodeTypeEnum },
	{ "Interruptible",			TOK_AUTOINT(DynAnimTemplateNode, bInterruptible, 0), NULL },
	{ "X",						TOK_F32(DynAnimTemplateNode, fX, 0), NULL },
	{ "Y",						TOK_F32(DynAnimTemplateNode, fY, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimTemplateNode()
{
	int iSize = sizeof(DynAnimTemplateNode);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimTemplateNode, iSize, "DynAnimTemplateNode", NULL, "dynAnimTemplate.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynAnimGraph[];
#define TYPE_parse_DynAnimGraph DynAnimGraph
extern ParseTable parse_DynAnimTemplateNode[];
#define TYPE_parse_DynAnimTemplateNode DynAnimTemplateNode
//Structparser.exe autogenerated ParseTable for struct DynAnimTemplate
#define TYPE_parse_DynAnimTemplate DynAnimTemplate
ParseTable parse_DynAnimTemplate[] =
{
	{ "DynAnimTemplate", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynAnimTemplate), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_POOL_STRING | TOK_KEY | TOK_STRING(DynAnimTemplate, pcName, 0), NULL },
	{ "Filename",			TOK_POOL_STRING | TOK_POOL_STRING | TOK_CURRENTFILE(DynAnimTemplate, pcFilename), NULL},
	{ "Comments",			TOK_SERVER_ONLY | TOK_STRING(DynAnimTemplate, pcComments, 0), NULL },
	{ "Scope",				TOK_POOL_STRING | TOK_SERVER_ONLY | TOK_STRING(DynAnimTemplate, pcScope, 0), NULL },
	{ "Type",				TOK_AUTOINT(DynAnimTemplate, eType, 0), eAnimTemplateTypeEnum },
	{ "DefaultsGraph",		TOK_OPTIONALSTRUCT(DynAnimTemplate, pDefaultsGraph, parse_DynAnimGraph) },
	{ "Nodes",				TOK_STRUCT(DynAnimTemplate, eaNodes, parse_DynAnimTemplateNode) },
	{ "Flags",				TOK_POOL_STRING | TOK_STRINGARRAY(DynAnimTemplate, eaFlags), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynAnimTemplate()
{
	int iSize = sizeof(DynAnimTemplate);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynAnimTemplate, iSize, "DynAnimTemplate", NULL, "dynAnimTemplate.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
