#ifndef __DYNANIMPHYSINFO_H_AST_H_
#define __DYNANIMPHYSINFO_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \dynAnimPhysInfo.h
//autogeneratednocheckin

//auto-generated staticdefine for enum eBouncerType
//autogeneratednocheckin
extern StaticDefineInt eBouncerTypeEnum[];

extern ParseTable parse_DynBouncerInfo[];
#define TYPE_parse_DynBouncerInfo DynBouncerInfo

extern ParseTable parse_DynBouncerGroupInfo[];
#define TYPE_parse_DynBouncerGroupInfo DynBouncerGroupInfo

#endif
