#include "textparser.h"

//auto-generated staticdefine for enum eDynForceType
//autogeneratednocheckin
StaticDefineInt eDynForceTypeEnum[] =
{
	DEFINE_INT
	{ "None", eDynForceType_None},
	{ "Out", eDynForceType_Out},
	{ "Swirl", eDynForceType_Swirl},
	{ "Up", eDynForceType_Up},
	{ "Side", eDynForceType_Side},
	{ "Forward", eDynForceType_Forward},
	DEFINE_END
};
void autoEnum_fixup_eDynForceType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(eDynForceTypeEnum, "eDynForceType");
}

//auto-generated staticdefine for enum eDynForceFalloff
//autogeneratednocheckin
StaticDefineInt eDynForceFalloffEnum[] =
{
	DEFINE_INT
	{ "Linear", eDynForceFallOff_Linear},
	{ "None", eDynForceFallOff_None},
	DEFINE_END
};
void autoEnum_fixup_eDynForceFalloff(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(eDynForceFalloffEnum, "eDynForceFalloff");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct DynContactPair
#define TYPE_parse_DynContactPair DynContactPair
ParseTable parse_DynContactPair[] =
{
	{ "DynContactPair", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynContactPair), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Touching",			TOK_AUTOINT(DynContactPair, bTouching, 0), NULL },
	{ "ContactForceTotal",	TOK_F32(DynContactPair, fContactForceTotal, 0), NULL },
	{ "ContactPoint",		TOK_AUTOINT(DynContactPair, bContactPoint, 0), NULL },
	{ "ContactPos",			TOK_VEC3(DynContactPair, vContactPos), NULL },
	{ "ContactNorm",		TOK_VEC3(DynContactPair, vContactNorm), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynContactPair()
{
	int iSize = sizeof(DynContactPair);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynContactPair, iSize, "DynContactPair", NULL, "dynFxPhysics.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynContactPair[];
#define TYPE_parse_DynContactPair DynContactPair
//Structparser.exe autogenerated ParseTable for struct DynFxPhysicsUpdateInfo
#define TYPE_parse_DynFxPhysicsUpdateInfo DynFxPhysicsUpdateInfo
ParseTable parse_DynFxPhysicsUpdateInfo[] =
{
	{ "DynFxPhysicsUpdateInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynFxPhysicsUpdateInfo), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Accel",					TOK_VEC3(DynFxPhysicsUpdateInfo, vAccel), NULL },
	{ "Drag",					TOK_F32(DynFxPhysicsUpdateInfo, fDrag, 0), NULL },
	{ "boolAccel",				TOK_AUTOINT(DynFxPhysicsUpdateInfo, bAccel, 0), NULL },
	{ "NeedsWakeup",			TOK_AUTOINT(DynFxPhysicsUpdateInfo, bNeedsWakeup, 0), NULL },
	{ "ContactPairs",			TOK_STRUCT(DynFxPhysicsUpdateInfo, eaContactPairs, parse_DynContactPair) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynFxPhysicsUpdateInfo()
{
	int iSize = sizeof(DynFxPhysicsUpdateInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynFxPhysicsUpdateInfo, iSize, "DynFxPhysicsUpdateInfo", NULL, "dynFxPhysics.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct DynForce
#define TYPE_parse_DynForce DynForce
ParseTable parse_DynForce[] =
{
	{ "DynForce", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynForce), 0, NULL, 0, NULL },
	{ "Type",		TOK_AUTOINT(DynForce, eForceType, 0), eDynForceTypeEnum },
	{ "FallOff",	TOK_AUTOINT(DynForce, eForceFallOff, 0), eDynForceFalloffEnum },
	{ "Radius",		TOK_F32(DynForce, fForceRadius, 0), NULL },
	{ "Power",		TOK_F32(DynForce, fForcePower, 0), NULL },
	{ "Impulse",	TOK_BOOLFLAG(DynForce, bImpulse, 0), NULL },
	{ "Name",		TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(DynForce, pcTag, 0), NULL },
	{ "End",		TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynForce()
{
	int iSize = sizeof(DynForce);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynForce, iSize, "DynForce", NULL, "dynFxPhysics.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct DynFxPhysicsInfo
#define TYPE_parse_DynFxPhysicsInfo DynFxPhysicsInfo
ParseTable parse_DynFxPhysicsInfo[] =
{
	{ "DynFxPhysicsInfo", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynFxPhysicsInfo), 0, NULL, 0, NULL },
	{ "Radius",				TOK_F32(DynFxPhysicsInfo, fRadius, -1), NULL },
	{ "SFriction",			TOK_F32(DynFxPhysicsInfo, fSFriction, -1), NULL },
	{ "DFriction",			TOK_F32(DynFxPhysicsInfo, fDFriction, -1), NULL },
	{ "Density",			TOK_F32(DynFxPhysicsInfo, fDensity, -1), NULL },
	{ "Restitution",		TOK_F32(DynFxPhysicsInfo, fRestitution, -1), NULL },
	{ "ForceImmunity",		TOK_F32(DynFxPhysicsInfo, fForceImmunity, 0), NULL },
	{ "Type",				TOK_AUTOINT(DynFxPhysicsInfo, eType, edpt_Normal), ParseDynPhysType },
	{ "PhysicalProperty",	TOK_POOL_STRING | TOK_STRING(DynFxPhysicsInfo, pcPhysicalProperty, 0), NULL },
	{ "Debris",				TOK_BOOLFLAG(DynFxPhysicsInfo, bDebris, 0), NULL },
	{ "StartAsleep",		TOK_BOOLFLAG(DynFxPhysicsInfo, bStartAsleep, 0), NULL },
	{ "NoCollide",			TOK_AUTOINT(DynFxPhysicsInfo, bNoCollide, 0), NULL },
	{ "PhysicsAttached",	TOK_BOOLFLAG(DynFxPhysicsInfo, bPhysicsAttached, 0), NULL },
	{ "KinematicActor",		TOK_BOOLFLAG(DynFxPhysicsInfo, bKinematicActor, 0), NULL },
	{ "ParentAttachPoint",	TOK_VEC3(DynFxPhysicsInfo, vParentAttachPoint), NULL },
	{ "ChildAttachPoint",	TOK_VEC3(DynFxPhysicsInfo, vChildAttachPoint), NULL },
	{ "jointAxis",			TOK_AUTOINT(DynFxPhysicsInfo, jointAxis, 0), eJointAxisEnum },
	{ "RevoluteJoint",		TOK_BOOLFLAG(DynFxPhysicsInfo, bRevoluteJoint, 0), NULL },
	{ "LimitJoint",			TOK_BOOLFLAG(DynFxPhysicsInfo, bLimitJoint, 0), NULL },
	{ "JointMin",			TOK_F32(DynFxPhysicsInfo, fJointMin, 0), NULL },
	{ "JointMax",			TOK_F32(DynFxPhysicsInfo, fJointMax, 0), NULL },
	{ "JointSpringiness",	TOK_F32(DynFxPhysicsInfo, fJointSpringiness, 0), NULL },
	{ "End",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynFxPhysicsInfo()
{
	int iSize = sizeof(DynFxPhysicsInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynFxPhysicsInfo, iSize, "DynFxPhysicsInfo", NULL, "dynFxPhysics.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	parse_DynFxPhysicsInfo[1].param = GET_INTPTR_FROM_FLOAT((float)-1);
	parse_DynFxPhysicsInfo[2].param = GET_INTPTR_FROM_FLOAT((float)-1);
	parse_DynFxPhysicsInfo[3].param = GET_INTPTR_FROM_FLOAT((float)-1);
	parse_DynFxPhysicsInfo[4].param = GET_INTPTR_FROM_FLOAT((float)-1);
	parse_DynFxPhysicsInfo[5].param = GET_INTPTR_FROM_FLOAT((float)-1);
	return 0;
};
