#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct DynGroundRegDataLimb
#define TYPE_parse_DynGroundRegDataLimb DynGroundRegDataLimb
ParseTable parse_DynGroundRegDataLimb[] =
{
	{ "DynGroundRegDataLimb", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynGroundRegDataLimb), 0, NULL, 0, NULL },
	{ "HeightFixupNode",		TOK_POOL_STRING | TOK_STRING(DynGroundRegDataLimb, pcHeightFixupNode, 0), NULL },
	{ "EndEffectorNode",		TOK_POOL_STRING | TOK_STRING(DynGroundRegDataLimb, pcEndEffectorNode, 0), NULL },
	{ "UpperBody",				TOK_BOOLFLAG(DynGroundRegDataLimb, bUpperBody, 0), NULL },
	{ "HyperExtAxis",			TOK_VEC3(DynGroundRegDataLimb, vHyperExtAxis), NULL },
	{ "End",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynGroundRegDataLimb()
{
	int iSize = sizeof(DynGroundRegDataLimb);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynGroundRegDataLimb, iSize, "DynGroundRegDataLimb", NULL, "dynGroundReg.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynGroundRegDataLimb[];
#define TYPE_parse_DynGroundRegDataLimb DynGroundRegDataLimb
//Structparser.exe autogenerated ParseTable for struct DynGroundRegData
#define TYPE_parse_DynGroundRegData DynGroundRegData
ParseTable parse_DynGroundRegData[] =
{
	{ "DynGroundRegData", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynGroundRegData), 0, NULL, 0, NULL },
	{ "Name",					TOK_POOL_STRING | TOK_KEY | TOK_STRING(DynGroundRegData, pcName, 0), NULL },
	{ "FileName",				TOK_POOL_STRING | TOK_CURRENTFILE(DynGroundRegData, pcFileName), NULL},
	{ "HipsNode",				TOK_POOL_STRING | TOK_STRING(DynGroundRegData, pcHipsNode, 0), NULL },
	{ "HeightFixupNode",		TOK_POOL_STRING | TOK_STRING(DynGroundRegData, pcHeightFixupNode, 0), NULL },
	{ "FloorDeltaNear",			TOK_F32(DynGroundRegData, fFloorDeltaNear, 0.2), NULL },
	{ "FloorDeltaFar",			TOK_F32(DynGroundRegData, fFloorDeltaFar, 1.8), NULL },
	{ "DynGroundRegDataLimb",	TOK_STRUCT(DynGroundRegData, eaLimbs, parse_DynGroundRegDataLimb) },
	{ "End",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynGroundRegData()
{
	int iSize = sizeof(DynGroundRegData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynGroundRegData, iSize, "DynGroundRegData", NULL, "dynGroundReg.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	parse_DynGroundRegData[5].param = GET_INTPTR_FROM_FLOAT((float)0.2);
	parse_DynGroundRegData[6].param = GET_INTPTR_FROM_FLOAT((float)1.8);
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_DynGroundRegDataLimb[];
#define TYPE_parse_DynGroundRegDataLimb DynGroundRegDataLimb
extern ParseTable parse_DynNode[];
#define TYPE_parse_DynNode DynNode
extern ParseTable parse_DynNode[];
#define TYPE_parse_DynNode DynNode
extern ParseTable parse_DynTransform[];
#define TYPE_parse_DynTransform DynTransform
//Structparser.exe autogenerated ParseTable for struct DynGroundRegLimb
#define TYPE_parse_DynGroundRegLimb DynGroundRegLimb
ParseTable parse_DynGroundRegLimb[] =
{
	{ "DynGroundRegLimb", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynGroundRegLimb), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "StaticLimbData",				TOK_OPTIONALSTRUCT(DynGroundRegLimb, pStaticLimbData, parse_DynGroundRegDataLimb) },
	{ "HeightFixupNode",			TOK_OPTIONALSTRUCT(DynGroundRegLimb, pHeightFixupNode, parse_DynNode) },
	{ "EndEffectorNode",			TOK_OPTIONALSTRUCT(DynGroundRegLimb, pEndEffectorNode, parse_DynNode) },
	{ "xPerFrame_TargetPosition",	TOK_EMBEDDEDSTRUCT(DynGroundRegLimb, xPerFrame_TargetPosition, parse_DynTransform)},
	{ "PerFrame_HyperExtension",	TOK_F32(DynGroundRegLimb, fPerFrame_HyperExtension, 0), NULL },
	{ "PerFrame_RelWeight",			TOK_F32(DynGroundRegLimb, fPerFrame_RelWeight, 0), NULL },
	{ "PerFrame_DiffPosition",		TOK_F32(DynGroundRegLimb, fPerFrame_DiffPosition, 0), NULL },
	{ "PerFrame_IsSafe",			TOK_AUTOINT(DynGroundRegLimb, bPerFrame_IsSafe, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynGroundRegLimb()
{
	int iSize = sizeof(DynGroundRegLimb);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynGroundRegLimb, iSize, "DynGroundRegLimb", NULL, "dynGroundReg.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
