#ifndef __DYNMOVETRANSITION_H_AST_H_
#define __DYNMOVETRANSITION_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \dynMoveTransition.h
//autogeneratednocheckin

extern ParseTable parse_DynMoveTransition[];
#define TYPE_parse_DynMoveTransition DynMoveTransition

#endif
