#ifndef __PARTITION_ENUMS_H_AST_H_
#define __PARTITION_ENUMS_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \partition_enums.h
//autogeneratednocheckin

//auto-generated staticdefine for enum PartitionDeathReason
//autogeneratednocheckin
extern StaticDefineInt PartitionDeathReasonEnum[];

#endif
