#ifndef __WLGENESISEXTERIORNODE_H_AST_H_
#define __WLGENESISEXTERIORNODE_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \wlGenesisExteriorNode.h
//autogeneratednocheckin

//auto-generated staticdefine for enum GenesisConstraintFuncName
//autogeneratednocheckin
extern StaticDefineInt GenesisConstraintFuncNameEnum[];

//auto-generated staticdefine for enum GenesisParamType
//autogeneratednocheckin
extern StaticDefineInt GenesisParamTypeEnum[];

//auto-generated staticdefine for enum GenesisNodeType
//autogeneratednocheckin
extern StaticDefineInt GenesisNodeTypeEnum[];

extern ParseTable parse_GenesisConstraintParam[];
#define TYPE_parse_GenesisConstraintParam GenesisConstraintParam

extern ParseTable parse_GenesisRoomConstraint[];
#define TYPE_parse_GenesisRoomConstraint GenesisRoomConstraint

extern ParseTable parse_GenesisNodeConstraint[];
#define TYPE_parse_GenesisNodeConstraint GenesisNodeConstraint

extern ParseTable parse_GenesisNodeObject[];
#define TYPE_parse_GenesisNodeObject GenesisNodeObject

extern ParseTable parse_GenesisNodePatrol[];
#define TYPE_parse_GenesisNodePatrol GenesisNodePatrol

extern ParseTable parse_GenesisNodeMission[];
#define TYPE_parse_GenesisNodeMission GenesisNodeMission

extern ParseTable parse_GenesisNodePathPoint[];
#define TYPE_parse_GenesisNodePathPoint GenesisNodePathPoint

extern ParseTable parse_GenesisNodeConnection[];
#define TYPE_parse_GenesisNodeConnection GenesisNodeConnection

extern ParseTable parse_GenesisNodeConnectionGroup[];
#define TYPE_parse_GenesisNodeConnectionGroup GenesisNodeConnectionGroup

extern ParseTable parse_GenesisNodeBorder[];
#define TYPE_parse_GenesisNodeBorder GenesisNodeBorder

extern ParseTable parse_GenesisNode[];
#define TYPE_parse_GenesisNode GenesisNode

#endif
