#ifndef __WLSKELINFO_H_AST_H_
#define __WLSKELINFO_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \wlSkelInfo.h
//autogeneratednocheckin

extern ParseTable parse_SkelScaleBone[];
#define TYPE_parse_SkelScaleBone SkelScaleBone

extern ParseTable parse_SkelScaleGroupInclude[];
#define TYPE_parse_SkelScaleGroupInclude SkelScaleGroupInclude

extern ParseTable parse_SkelScaleGroup[];
#define TYPE_parse_SkelScaleGroup SkelScaleGroup

extern ParseTable parse_SkelScaleAnimTrack[];
#define TYPE_parse_SkelScaleAnimTrack SkelScaleAnimTrack

extern ParseTable parse_SkelScaleInfo[];
#define TYPE_parse_SkelScaleInfo SkelScaleInfo

extern ParseTable parse_SkelBlendRunAndGunBone[];
#define TYPE_parse_SkelBlendRunAndGunBone SkelBlendRunAndGunBone

extern ParseTable parse_SkelBlendSeqInfo[];
#define TYPE_parse_SkelBlendSeqInfo SkelBlendSeqInfo

extern ParseTable parse_SkelBlendInfo[];
#define TYPE_parse_SkelBlendInfo SkelBlendInfo

extern ParseTable parse_HeadShotFrameBone[];
#define TYPE_parse_HeadShotFrameBone HeadShotFrameBone

extern ParseTable parse_HeadShotFrame[];
#define TYPE_parse_HeadShotFrame HeadShotFrame

extern ParseTable parse_SkelHeadshotInfo[];
#define TYPE_parse_SkelHeadshotInfo SkelHeadshotInfo

extern ParseTable parse_BodySockInfo[];
#define TYPE_parse_BodySockInfo BodySockInfo

extern ParseTable parse_SkelInfo[];
#define TYPE_parse_SkelInfo SkelInfo

#endif
