#ifndef __WORLDGRIDLOADPRIVATE_H_AST_H_
#define __WORLDGRIDLOADPRIVATE_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \WorldGridLoadPrivate.h
//autogeneratednocheckin

extern ParseTable parse_LibFileLoad[];
#define TYPE_parse_LibFileLoad LibFileLoad

#endif
