#include "textparser.h"

//auto-generated staticdefine for enum PrefType
//autogeneratednocheckin
StaticDefineInt PrefTypeEnum[] =
{
	DEFINE_INT
	{ "PREF_STRING", PREF_STRING},
	DEFINE_END
};
void autoEnum_fixup_PrefType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(PrefTypeEnum, "PrefType");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct PrefKV
#define TYPE_parse_PrefKV PrefKV
ParseTable parse_PrefKV[] =
{
	{ "PrefKV", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PrefKV), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "name",		TOK_PERSIST | TOK_POOL_STRING | TOK_KEY | TOK_STRING(PrefKV, name, 0), NULL },
	{ "type",		TOK_PERSIST | TOK_AUTOINT(PrefKV, type, 0), PrefTypeEnum },
	{ "stringVal",	TOK_PERSIST | TOK_STRING(PrefKV, stringVal, 0), NULL },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_PrefKV()
{
	int iSize = sizeof(PrefKV);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_PrefKV, iSize, "PrefKV", NULL, "ServerLibPrefStore.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_PrefKV[];
#define TYPE_parse_PrefKV PrefKV
//Structparser.exe autogenerated ParseTable for struct PrefStore
#define TYPE_parse_PrefStore PrefStore
ParseTable parse_PrefStore[] =
{
	{ "PrefStore", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PrefStore), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "id",					TOK_PERSIST | TOK_KEY | TOK_AUTOINT(PrefStore, id, 0), NULL },
	{ "ppPrefs",			TOK_PERSIST | TOK_STRUCT(PrefStore, ppPrefs, parse_PrefKV) },
	{ "Apply Transaction", 	TOK_COMMAND, 0, (intptr_t)"ServerMonTransactionOnEntity PrefStore $FIELD(id) $STRING(Transaction String)$CONFIRM(Really apply this transaction?)" },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_PrefStore()
{
	int iSize = sizeof(PrefStore);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_PrefStore, iSize, "PrefStore", NULL, "ServerLibPrefStore.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
