#ifndef __SERVERLIBPREFSTORE_H_AST_H_
#define __SERVERLIBPREFSTORE_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \ServerLibPrefStore.h
//autogeneratednocheckin

//auto-generated staticdefine for enum PrefType
//autogeneratednocheckin
extern StaticDefineInt PrefTypeEnum[];

extern ParseTable parse_PrefKV[];
#define TYPE_parse_PrefKV PrefKV

//This is the autogenerated non-const copy of PrefKV
//Here are some struct prototypes for PrefKV

typedef struct PrefKV_AutoGen_NoConst { 
	STRING_POOLED name ; 
	PrefType type ; 
	STRING_MODIFIABLE stringVal ; 
	int cmdID ; 
	} 
PrefKV_AutoGen_NoConst ; 



extern ParseTable parse_PrefStore[];
#define TYPE_parse_PrefStore PrefStore

//This is the autogenerated non-const copy of PrefStore
//Here are some struct prototypes for PrefStore
typedef struct PrefKV_AutoGen_NoConst PrefKV_AutoGen_NoConst;

typedef struct PrefStore_AutoGen_NoConst { 
	U32 id ; 
	EARRAY_OF ( PrefKV_AutoGen_NoConst ) ppPrefs ; 
	AST_COMMAND ( Apply Transaction , ServerMonTransactionOnEntity PrefStore $FIELD(id) $STRING(Transaction String)$CONFIRM(Really apply this transaction?) ) } 
PrefStore_AutoGen_NoConst ; 



#endif
