#ifndef __TEXTFILTERCOMMON_C_AST_H_
#define __TEXTFILTERCOMMON_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \TextFilterCommon.c
//autogeneratednocheckin

extern ParseTable parse_FilterEntry[];
#define TYPE_parse_FilterEntry FilterEntry

extern ParseTable parse_FilterFile[];
#define TYPE_parse_FilterFile FilterFile

extern ParseTable parse_FilterFileList[];
#define TYPE_parse_FilterFileList FilterFileList

#endif
