#ifndef __PATCHDIALOGS_C_AST_H_
#define __PATCHDIALOGS_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \patchdialogs.c
//autogeneratednocheckin

extern ParseTable parse_ProjectEntry[];
#define TYPE_parse_ProjectEntry ProjectEntry

extern ParseTable parse_PatchName[];
#define TYPE_parse_PatchName PatchName

extern ParseTable parse_GetLatestPath[];
#define TYPE_parse_GetLatestPath GetLatestPath

#endif
