#include "textparser.h"

//auto-generated staticdefine for enum PCLStatusMonitoringState
//autogeneratednocheckin
StaticDefineInt PCLStatusMonitoringStateEnum[] =
{
	DEFINE_INT
	{ "UPDATE", PCLSMS_UPDATE},
	{ "FAILED", PCLSMS_FAILED},
	{ "SUCCEEDED", PCLSMS_SUCCEEDED},
	{ "TIMEOUT", PCLSMS_TIMEOUT},
	{ "FAILED_TIMEOUT", PCLSMS_FAILED_TIMEOUT},
	{ "INTERNAL_CREATE", PCLSMS_INTERNAL_CREATE},
	{ "DELETING", PCLSMS_DELETING},
	DEFINE_END
};
void autoEnum_fixup_PCLStatusMonitoringState(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(PCLStatusMonitoringStateEnum, "PCLStatusMonitoringState");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct PCLStatusMonitoringUpdate_Internal
#define TYPE_parse_PCLStatusMonitoringUpdate_Internal PCLStatusMonitoringUpdate_Internal
ParseTable parse_PCLStatusMonitoringUpdate_Internal[] =
{
	{ "PCLStatusMonitoringUpdate_Internal", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PCLStatusMonitoringUpdate_Internal), 0, NULL, 0, NULL },
	{ "{",									TOK_START, 0 },
	{ "MyIDString",							TOK_STRING(PCLStatusMonitoringUpdate_Internal, pMyIDString, 0), NULL },
	{ "State",								TOK_AUTOINT(PCLStatusMonitoringUpdate_Internal, eState, 0), PCLStatusMonitoringStateEnum },
	{ "UpdateString",						TOK_ESTRING | TOK_STRING(PCLStatusMonitoringUpdate_Internal, pUpdateString, 0), NULL },
	{ "PatchName",							TOK_STRING(PCLStatusMonitoringUpdate_Internal, pPatchName, 0), NULL },
	{ "PatchDir",							TOK_STRING(PCLStatusMonitoringUpdate_Internal, pPatchDir, 0), NULL },
	{ "MyPID",								TOK_AUTOINT(PCLStatusMonitoringUpdate_Internal, iMyPID, 0), NULL },
	{ "uMyHWND",							TOK_AUTOINT(PCLStatusMonitoringUpdate_Internal, uMyHWND, 0), NULL },
	{ "}",									TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_PCLStatusMonitoringUpdate_Internal()
{
	int iSize = sizeof(PCLStatusMonitoringUpdate_Internal);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_PCLStatusMonitoringUpdate_Internal, iSize, "PCLStatusMonitoringUpdate_Internal", NULL, "PatchClientLibStatusMonitoring.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_PCLStatusMonitoringUpdate_Internal[];
#define TYPE_parse_PCLStatusMonitoringUpdate_Internal PCLStatusMonitoringUpdate_Internal
//Structparser.exe autogenerated ParseTable for struct PCLStatusMonitoringUpdate
#define TYPE_parse_PCLStatusMonitoringUpdate PCLStatusMonitoringUpdate
ParseTable parse_PCLStatusMonitoringUpdate[] =
{
	{ "PCLStatusMonitoringUpdate", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PCLStatusMonitoringUpdate), 0, NULL, 0, "HTML_DEF_FIELDS_TO_SHOW = \"internalStatus.State, internalStatus.UpdateString, MostRecentUpdateTime\""},
	{ "{",							TOK_START, 0 },
	{ "internalStatus",				TOK_EMBEDDEDSTRUCT(PCLStatusMonitoringUpdate, internalStatus, parse_PCLStatusMonitoringUpdate_Internal)},
	{ "TimeBegan",					TOK_AUTOINT(PCLStatusMonitoringUpdate, iTimeBegan, 0), NULL , 0 , "HTML_SECS_AGO = 1"},
	{ "MostRecentUpdateTime",		TOK_AUTOINT(PCLStatusMonitoringUpdate, iMostRecentUpdateTime, 0), NULL , 0 , "HTML_SECS_AGO = 1"},
	{ "SucceededOrFailedTime",		TOK_AUTOINT(PCLStatusMonitoringUpdate, iSucceededOrFailedTime, 0), NULL , 0 , "HTML_SECS_AGO = 1"},
	{ "NumUpdatesReceived",			TOK_AUTOINT(PCLStatusMonitoringUpdate, iNumUpdatesReceived, 0), NULL },
	{ "TimeoutLength",				TOK_AUTOINT(PCLStatusMonitoringUpdate, iTimeoutLength, 0), NULL , 0 , "HTML_SECS_DURATION = 1"},
	{ "TimeoutIndex",				TOK_AUTOINT(PCLStatusMonitoringUpdate, iTimeoutIndex, 0), NULL },
	{ "DestroyRequested",			TOK_AUTOINT(PCLStatusMonitoringUpdate, bDestroyRequested, 0), NULL },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_PCLStatusMonitoringUpdate()
{
	int iSize = sizeof(PCLStatusMonitoringUpdate);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_PCLStatusMonitoringUpdate, iSize, "PCLStatusMonitoringUpdate", NULL, "PatchClientLibStatusMonitoring.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
