//autogeneratednocheckin  this file is autogenerated by structparser, and includes all other autogenerated .c files
GCC_SYSTEM
#pragma warning(default:4242)

#include "cmdparse.h"
#include "textparser.h"
#include "globaltypes.h"
#include "memorybudget.h"
//extra define of assertmsg for weird projects like crashrptDLL
#if !defined(assertmsg) 
#define assertmsg(x,y) assert(x)
#endif

//
//
//Beginning forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_commands_autogen.c
//
//
//
//This file contains data and prototypes for magic commands. It is autogenerated by StructParser

//autogeneratednocheckin
#include "cmdparse.h"
#include "textparser.h"
#include "globaltypes.h"
#include "net/net.h"
#include "net/netpacketutil.h"
#include "structnet.h"
#include "structInternals.h"
static char sPatchClientLibName[] = "PatchClientLib";
//if one of these includes fails, you're trying to use expression list commands somewhere illegal... talk to Raoul
#include "ExpressionMinimal.h"
#include "ExpressionFunc.h"
#include "ScratchStack.h"
#include "mathutil.h"
#include "timing.h"
typedef struct Entity Entity;
extern void MakePatchVersionsServerMonitorable(const char* pServer, const char* pProductName); // function defined in I:\Night\Night\src\libs\PatchClientLib\pcl_client_wt.c
static void MakePatchVersionsServerMonitorable_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS2(char*, arg0, char*, arg1);
	MakePatchVersionsServerMonitorable(arg0, arg1);
}
extern void ignorechecksum(int value); // function defined in I:\Night\Night\src\libs\PatchClientLib\pcl_client.c
static void ignorechecksum_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS1(int, arg0);
	ignorechecksum(arg0);
}
static Cmd cmdSetData_MakePatchVersionsServerMonitorable[] = {
	{ 9, "MakePatchVersionsServerMonitorable", "pcl_client_wt.c", 396, NULL, sPatchClientLibName, NULL, {{"pServer", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }, {"pProductName", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0,
		"No comment provided", MakePatchVersionsServerMonitorable_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdSetData_ignorechecksum[] = {
	{ 9, "ignorechecksum", "pcl_client.c", 6794, NULL, sPatchClientLibName, NULL, {{"value", MULTI_INT,0, sizeof(S32), CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0,
		"No comment provided", ignorechecksum_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdVarSetData_patchxferhttpforcerange =
{
	9, "patchxferhttpforcerange", "patchxferhttp.c", 65, NULL, sPatchClientLibName,  NULL, {{ NULL, MULTI_INT, NULL, 0, 0, 0 }},CMDF_PRINTVARS ,
		"If set, send \"whole file\" requests as ranges.\n", NULL, {NULL, MULTI_NONE,0,0,0}, NULL
};

static Cmd cmdVarSetData_patchxferhttpforcerangeaswholefile =
{
	9, "patchxferhttpforcerangeaswholefile", "patchxferhttp.c", 69, NULL, sPatchClientLibName,  NULL, {{ NULL, MULTI_INT, NULL, 0, 0, 0 }},CMDF_PRINTVARS ,
		"If set, send all requests as a request for the whole file, even if we only need a subrange.\n", NULL, {NULL, MULTI_NONE,0,0,0}, NULL
};


void AutoGen_RegisterAutoCmd_patchxferhttpforcerange(void *pAddress, int iSize)
{
	cmdVarSetData_patchxferhttpforcerange.data[0].ptr = pAddress;
	cmdVarSetData_patchxferhttpforcerange.data[0].data_size = iSize;
}
void AutoGen_RegisterAutoCmd_patchxferhttpforcerangeaswholefile(void *pAddress, int iSize)
{
	cmdVarSetData_patchxferhttpforcerangeaswholefile.data[0].ptr = pAddress;
	cmdVarSetData_patchxferhttpforcerangeaswholefile.data[0].data_size = iSize;
}

extern CmdList gRemoteCmdList;
extern CmdList gSlowRemoteCmdList;
extern ParseTable parse_Entity[];
void Add_Auto_Cmds_PatchClientLib(void)
{
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdSetData_MakePatchVersionsServerMonitorable[0]);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdSetData_ignorechecksum[0]);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdVarSetData_patchxferhttpforcerange);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdVarSetData_patchxferhttpforcerangeaswholefile);
};
void Add_Auto_Cmds_PatchClientLib_Later(void)
{
};
#pragma warning (disable:4054) // casting function pointers as data pointers

//
//
//Ending forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_commands_autogen.c
//
//
//
//
//
//Beginning forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_autotransactions_autogen.c
//
//
//
#ifndef GAMECLIENT
//This file contains data and prototypes for auto transactions. It is autogenerated by StructParser

//autogeneratednocheckin

#endif
//
//
//Ending forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_autotransactions_autogen.c
//
//
//
//
//
//Beginning forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_AutoTest.c
//
//
//
//This file contains data and prototypes for AutoTests. It is autogenerated by StructParser

// autogeneratednocheckin
#include "testharness.h"


//
//
//Ending forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_AutoTest.c
//
//
//
//
//
//Beginning forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_latelink_autogen.c
//
//
//
//This file contains data and prototypes for latelinks. It is autogenerated by StructParser

//autogeneratednocheckin
#include "LateLinkSupport.h"

//Stuff relating to LATELINK_OVERRIDE_PCLStatusMonitoring_GetAllStatuses(), defined in I:\Night\Night\src\libs\PatchClientLib\PatchClientLibStatusMonitoring.c
extern void OVERRIDE_LATELINK_PCLStatusMonitoring_GetAllStatuses(void*** arg0);
typedef void PCLStatusMonitoring_GetAllStatuses_LATELINK_FPTYPE_INTERNAL(void*** arg0);
extern PCLStatusMonitoring_GetAllStatuses_LATELINK_FPTYPE_INTERNAL *PCLStatusMonitoring_GetAllStatuses_LATELINK_FP;
extern char *PCLStatusMonitoring_GetAllStatuses_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_PCLStatusMonitoring_GetAllStatuses(void)
{
	PCLStatusMonitoring_GetAllStatuses_LATELINK_FP = OVERRIDE_LATELINK_PCLStatusMonitoring_GetAllStatuses;
	TestLateLinkArgString(&PCLStatusMonitoring_GetAllStatuses_LATELINK_ARGSTRING, "void PCLStatusMonitoringUpdate * * * ", "PCLStatusMonitoring_GetAllStatuses");
}


//
//
//Ending forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_latelink_autogen.c
//
//
//
//
//
//Beginning forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_autorun_autogen.c
//
//
//
//This file contains data and prototypes for autoruns. It is autogenerated by StructParser

// autogeneratednocheckin
//This file contains data and prototypes for autoruns. It is autogenerated by StructParser

// autogeneratednocheckin
#include"metatask.h"
extern int giCurAutoRunStep;

//including I:\Night\Night\src\libs\PatchClientLib\PatchClientLib_AnonAutoRunIncludes.h, so that ANON_AUTORUNs will get the header files they need
#include "I:\Night\Night\src\libs\PatchClientLib\PatchClientLib_AnonAutoRunIncludes.h"
//declarations/code for internal autorun _patchdb_c_ANON_AUTORUN_416
static void _patchdb_c_ANON_AUTORUN_416(void)
{ memBudgetAddMapping("I:\\Night\\Night\\src\\libs\\PatchClientLib\\patchdb.c", BUDGET_FileSystem); }
//declarations/code for internal autorun _patchfilespec_c_ANON_AUTORUN_380
static void _patchfilespec_c_ANON_AUTORUN_380(void)
{ memBudgetAddMapping("I:\\Night\\Night\\src\\libs\\PatchClientLib\\patchfilespec.c", BUDGET_FileSystem); }
//declarations/code for internal autorun _patchxfer_c_ANON_AUTORUN_695
static void _patchxfer_c_ANON_AUTORUN_695(void)
{ memBudgetAddMapping("I:\\Night\\Night\\src\\libs\\PatchClientLib\\patchxfer.c", BUDGET_FileSystem); }
//declarations/code for internal autorun _patchxferhttp_c_ANON_AUTORUN_899
static void _patchxferhttp_c_ANON_AUTORUN_899(void)
{ memBudgetAddMapping("I:\\Night\\Night\\src\\libs\\PatchClientLib\\patchxferhttp.c", BUDGET_FileSystem); }
//declarations/code for internal autorun _patchxferhttp_opt_c_ANON_AUTORUN_323
static void _patchxferhttp_opt_c_ANON_AUTORUN_323(void)
{ memBudgetAddMapping("I:\\Night\\Night\\src\\libs\\PatchClientLib\\patchxferhttp_opt.c", BUDGET_EngineMisc); }
//declarations/code for internal autorun _pcl_client_c_ANON_AUTORUN_1163
static void _pcl_client_c_ANON_AUTORUN_1163(void)
{ memBudgetAddMapping("I:\\Night\\Night\\src\\libs\\PatchClientLib\\pcl_client.c", BUDGET_FileSystem); }
extern void Add_Auto_Cmds_PatchClientLib(void);
extern void Add_Auto_Cmds_PatchClientLib_Later(void); extern void AutoGen_AutoRun_RegisterAutoCmd_patchxferhttpforcerange(void); extern void AutoGen_AutoRun_RegisterAutoCmd_patchxferhttpforcerangeaswholefile(void); extern void OVERRIDE_LATELINK_AUTORUN_PCLStatusMonitoring_GetAllStatuses(void); extern void _PatchClientLib_AutoRun_SPECIALINTERNAL(void);
extern void _patchdb_c_ANON_AUTORUN_416(void); extern void _patchfilespec_c_ANON_AUTORUN_380(void); extern void _patchxfer_c_ANON_AUTORUN_695(void); extern void _patchxferhttp_c_ANON_AUTORUN_899(void); extern void _patchxferhttp_opt_c_ANON_AUTORUN_323(void);
extern void _pcl_client_c_ANON_AUTORUN_1163(void); extern void autoEnum_fixup_ControlSpecType(void); extern void autoEnum_fixup_FileSpecFlag(void); extern void autoEnum_fixup_PCLStatusMonitoringState(void); extern void autoEnum_fixup_PCL_ErrorCode(void);
extern void autoEnum_fixup_PCL_LogLevel(void); extern void autoEnum_fixup_PatchClientCmd(void); extern void autoEnum_fixup_PatchServerCmd(void); extern void autoStruct_fixup_Checkin(void); extern void autoStruct_fixup_Checkout(void);
extern void autoStruct_fixup_ControlSpec(void); extern void autoStruct_fixup_ControlSpecLine(void); extern void autoStruct_fixup_DirEntry(void); extern void autoStruct_fixup_FileSpecs(void); extern void autoStruct_fixup_FileVersion(void);
extern void autoStruct_fixup_FlagSpec(void); extern void autoStruct_fixup_FlagSpecLine(void); extern void autoStruct_fixup_GetLatestPath(void); extern void autoStruct_fixup_HogSpec(void); extern void autoStruct_fixup_LinkInfo(void);
extern void autoStruct_fixup_MirrorFolder(void); extern void autoStruct_fixup_NamedView(void); extern void autoStruct_fixup_PCLFileSpec(void); extern void autoStruct_fixup_PCLFileSpecEntry(void); extern void autoStruct_fixup_PCLStatusMonitoringUpdate(void);
extern void autoStruct_fixup_PCLStatusMonitoringUpdate_Internal(void); extern void autoStruct_fixup_PatchDB(void); extern void autoStruct_fixup_PatchMsgPerfInfo(void); extern void autoStruct_fixup_PatchMsgPerfInfos(void); extern void autoStruct_fixup_PatchName(void);
extern void autoStruct_fixup_PatchProcessStats(void); extern void autoStruct_fixup_PatchServerMonStuff(void); extern void autoStruct_fixup_PatchVersionInfo(void); extern void autoStruct_fixup_PatchVersionInfoForServerMon(void); extern void autoStruct_fixup_PatcherFileHistory(void);
extern void autoStruct_fixup_ProjectEntry(void); extern void autoStruct_fixup_Spec(void); extern void autoStruct_fixup_XferStateInfo(void); extern void initLoadFileVersionParse(void); extern void initializeMemlog(void);
extern void initializeStaticCmdPerfMutex(void); extern void patchRunOnce(void); void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);
void doAutoRuns_UtilitiesLib_5(void);
void doAutoRuns_UtilitiesLib_6(void);
void doAutoRuns_UtilitiesLib_7(void);

void doAutoRuns_PatchClientLib_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 0;
	doAutoRuns_UtilitiesLib_0();
	_PatchClientLib_AutoRun_SPECIALINTERNAL();
}

void doAutoRuns_PatchClientLib_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 1;
	doAutoRuns_UtilitiesLib_1();
	OVERRIDE_LATELINK_AUTORUN_PCLStatusMonitoring_GetAllStatuses();
}

void doAutoRuns_PatchClientLib_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 2;
	doAutoRuns_UtilitiesLib_2();
	Add_Auto_Cmds_PatchClientLib();
	AutoGen_AutoRun_RegisterAutoCmd_patchxferhttpforcerange(); 	AutoGen_AutoRun_RegisterAutoCmd_patchxferhttpforcerangeaswholefile(); 	autoEnum_fixup_ControlSpecType(); 	autoEnum_fixup_FileSpecFlag(); 	autoEnum_fixup_PCLStatusMonitoringState();
	autoEnum_fixup_PCL_ErrorCode(); 	autoEnum_fixup_PCL_LogLevel(); 	autoEnum_fixup_PatchClientCmd(); 	autoEnum_fixup_PatchServerCmd(); 	autoStruct_fixup_Checkin();
	autoStruct_fixup_Checkout(); 	autoStruct_fixup_ControlSpec(); 	autoStruct_fixup_ControlSpecLine(); 	autoStruct_fixup_DirEntry(); 	autoStruct_fixup_FileSpecs();
	autoStruct_fixup_FileVersion(); 	autoStruct_fixup_FlagSpec(); 	autoStruct_fixup_FlagSpecLine(); 	autoStruct_fixup_GetLatestPath(); 	autoStruct_fixup_HogSpec();
	autoStruct_fixup_LinkInfo(); 	autoStruct_fixup_MirrorFolder(); 	autoStruct_fixup_NamedView(); 	autoStruct_fixup_PCLFileSpec(); 	autoStruct_fixup_PCLFileSpecEntry();
	autoStruct_fixup_PCLStatusMonitoringUpdate(); 	autoStruct_fixup_PCLStatusMonitoringUpdate_Internal(); 	autoStruct_fixup_PatchDB(); 	autoStruct_fixup_PatchMsgPerfInfo(); 	autoStruct_fixup_PatchMsgPerfInfos();
	autoStruct_fixup_PatchName(); 	autoStruct_fixup_PatchProcessStats(); 	autoStruct_fixup_PatchServerMonStuff(); 	autoStruct_fixup_PatchVersionInfo(); 	autoStruct_fixup_PatchVersionInfoForServerMon();
	autoStruct_fixup_PatcherFileHistory(); 	autoStruct_fixup_ProjectEntry(); 	autoStruct_fixup_Spec(); 	autoStruct_fixup_XferStateInfo(); }

void doAutoRuns_PatchClientLib_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 3;
	doAutoRuns_UtilitiesLib_3();
}

void doAutoRuns_PatchClientLib_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 4;
	doAutoRuns_UtilitiesLib_4();
	Add_Auto_Cmds_PatchClientLib_Later();
}

void doAutoRuns_PatchClientLib_5(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 5;
	doAutoRuns_UtilitiesLib_5();
	_patchdb_c_ANON_AUTORUN_416();
	_patchfilespec_c_ANON_AUTORUN_380(); 	_patchxfer_c_ANON_AUTORUN_695(); 	_patchxferhttp_c_ANON_AUTORUN_899(); 	_patchxferhttp_opt_c_ANON_AUTORUN_323(); 	_pcl_client_c_ANON_AUTORUN_1163();
	initLoadFileVersionParse(); 	initializeMemlog(); 	initializeStaticCmdPerfMutex(); 	patchRunOnce(); }

void doAutoRuns_PatchClientLib_6(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 6;
	doAutoRuns_UtilitiesLib_6();
}

void doAutoRuns_PatchClientLib_7(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 7;
	doAutoRuns_UtilitiesLib_7();
}
extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_PatchClientLib(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_PatchClientLib_0();
	doAutoRuns_PatchClientLib_1();
	doAutoRuns_PatchClientLib_2();
	doAutoRuns_PatchClientLib_3();
	doAutoRuns_PatchClientLib_4();
	doAutoRuns_PatchClientLib_5();
	doAutoRuns_PatchClientLib_6();
	return 0;
}
int MagicAutoRunFunc_File_PatchClientLib(void)
{
	doAutoRuns_PatchClientLib_7();
	return 0;
}


//
//
//Ending forced include of all contents of file I:\Night\Night\src\libs\PatchClientLib\\AutoGen\PatchClientLib_autorun_autogen.c
//
//
//
//special internal auto-run function that does global fixup and setup stuff
extern int gBuildVersion;
extern void SetBuildBranch(char *pBranchName);
//If this assert hits, it's because someone is linking together libraries and executables from different
//SVN branches. Somehow.
void _PatchClientLib_AutoRun_SPECIALINTERNAL(void) { if (1 > gBuildVersion) gBuildVersion = 1; SetBuildBranch("(Unknown)");}
