#ifndef __BEACONFILE_H_AST_H_
#define __BEACONFILE_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \beaconFile.h
//autogeneratednocheckin

//auto-generated staticdefine for enum BeaconMapWarning
//autogeneratednocheckin
extern StaticDefineInt BeaconMapWarningEnum[];

//auto-generated staticdefine for enum BeaconMapFailureReason
//autogeneratednocheckin
extern StaticDefineInt BeaconMapFailureReasonEnum[];

//auto-generated staticdefine for enum BeaconProcessPhase
//autogeneratednocheckin
extern StaticDefineInt BeaconProcessPhaseEnum[];

extern ParseTable parse_SimpleWaypoint[];
#define TYPE_parse_SimpleWaypoint SimpleWaypoint

extern ParseTable parse_SimplePath[];
#define TYPE_parse_SimplePath SimplePath

extern ParseTable parse_BeaconMapMetaData[];
#define TYPE_parse_BeaconMapMetaData BeaconMapMetaData

#endif
