#ifndef __DYNANIMOVERRIDE_H_AST_H_
#define __DYNANIMOVERRIDE_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \dynAnimOverride.h
//autogeneratednocheckin

extern ParseTable parse_DynAnimOverride[];
#define TYPE_parse_DynAnimOverride DynAnimOverride

extern ParseTable parse_DynAnimOverrideList[];
#define TYPE_parse_DynAnimOverrideList DynAnimOverrideList

#endif
