#ifndef __DYNANIMTEMPLATE_H_AST_H_
#define __DYNANIMTEMPLATE_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \dynAnimTemplate.h
//autogeneratednocheckin

//auto-generated staticdefine for enum eAnimTemplateType
//autogeneratednocheckin
extern StaticDefineInt eAnimTemplateTypeEnum[];

//auto-generated staticdefine for enum eAnimTemplateNodeType
//autogeneratednocheckin
extern StaticDefineInt eAnimTemplateNodeTypeEnum[];

extern ParseTable parse_DynAnimTemplateNodeRef[];
#define TYPE_parse_DynAnimTemplateNodeRef DynAnimTemplateNodeRef

extern ParseTable parse_DynAnimTemplateSwitch[];
#define TYPE_parse_DynAnimTemplateSwitch DynAnimTemplateSwitch

extern ParseTable parse_DynAnimTemplateDirectionalData[];
#define TYPE_parse_DynAnimTemplateDirectionalData DynAnimTemplateDirectionalData

extern ParseTable parse_DynAnimTemplatePath[];
#define TYPE_parse_DynAnimTemplatePath DynAnimTemplatePath

extern ParseTable parse_DynAnimTemplateNode[];
#define TYPE_parse_DynAnimTemplateNode DynAnimTemplateNode

extern ParseTable parse_DynAnimTemplate[];
#define TYPE_parse_DynAnimTemplate DynAnimTemplate

#endif
