#ifndef __DYNBITFIELD_C_AST_H_
#define __DYNBITFIELD_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \dynBitField.c
//autogeneratednocheckin

extern ParseTable parse_DynBitString[];
#define TYPE_parse_DynBitString DynBitString

extern ParseTable parse_DynBitGroup[];
#define TYPE_parse_DynBitGroup DynBitGroup

extern ParseTable parse_DynBitList[];
#define TYPE_parse_DynBitList DynBitList

#endif
