#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_DynAnimInterpolation[];
#define TYPE_parse_DynAnimInterpolation DynAnimInterpolation
extern ParseTable parse_DynAnimInterpolation[];
#define TYPE_parse_DynAnimInterpolation DynAnimInterpolation
extern ParseTable parse_DynAnimTimedStance[];
#define TYPE_parse_DynAnimTimedStance DynAnimTimedStance
extern ParseTable parse_DynAnimTimedStance[];
#define TYPE_parse_DynAnimTimedStance DynAnimTimedStance
extern ParseTable parse_DynAnimTimedStance[];
#define TYPE_parse_DynAnimTimedStance DynAnimTimedStance
//Structparser.exe autogenerated ParseTable for struct DynMoveTransition
#define TYPE_parse_DynMoveTransition DynMoveTransition
ParseTable parse_DynMoveTransition[] =
{
	{ "DynMoveTransition", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(DynMoveTransition), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Name",						TOK_POOL_STRING | TOK_KEY | TOK_STRING(DynMoveTransition, pcName, 0), NULL },
	{ "Filename",					TOK_POOL_STRING | TOK_POOL_STRING | TOK_CURRENTFILE(DynMoveTransition, pcFilename), NULL},
	{ "Comments",					TOK_SERVER_ONLY | TOK_STRING(DynMoveTransition, pcComments, 0), NULL },
	{ "Scope",						TOK_POOL_STRING | TOK_SERVER_ONLY | TOK_STRING(DynMoveTransition, pcScope, 0), NULL },
	{ "Chart",						TOK_REFERENCE(DynMoveTransition, hChart, 0, "DynAnimChartLoadTime") },
	{ "Forced",						TOK_BOOLFLAG(DynMoveTransition, bForced, 0), NULL },
	{ "BlendLowerBodyFromGraph",	TOK_BOOLFLAG(DynMoveTransition, bBlendLowerBodyFromGraph, 0), NULL },
	{ "BlendWholeBodyFromGraph",	TOK_BOOLFLAG(DynMoveTransition, bBlendWholeBodyFromGraph, 0), NULL },
	{ "interpBlockPre",				TOK_EMBEDDEDSTRUCT(DynMoveTransition, interpBlockPre, parse_DynAnimInterpolation)},
	{ "interpBlockPost",			TOK_EMBEDDEDSTRUCT(DynMoveTransition, interpBlockPost, parse_DynAnimInterpolation)},
	{ "BlendWholeBodyToGraph",		TOK_BOOLFLAG(DynMoveTransition, bBlendWholeBodyToGraph, 0), NULL },
	{ "BlendLowerBodyToGraph",		TOK_BOOLFLAG(DynMoveTransition, bBlendLowerBodyToGraph, 0), NULL },
	{ "TimedStanceWordSource",		TOK_POOL_STRING | TOK_STRUCT(DynMoveTransition, eaTimedStancesSource, parse_DynAnimTimedStance) },
	{ "TimedStanceWordTarget",		TOK_POOL_STRING | TOK_STRUCT(DynMoveTransition, eaTimedStancesTarget, parse_DynAnimTimedStance) },
	{ "AllTimedStancesSorted",		TOK_POOL_STRING | TOK_NO_TEXT_SAVE | TOK_STRUCT(DynMoveTransition, eaAllTimedStancesSorted, parse_DynAnimTimedStance) },
	{ "StanceWordSource",			TOK_POOL_STRING | TOK_STRINGARRAY(DynMoveTransition, eaStanceWordsSource), NULL },
	{ "StanceWordTarget",			TOK_POOL_STRING | TOK_STRINGARRAY(DynMoveTransition, eaStanceWordsTarget), NULL },
	{ "AllStanceWordsSorted",		TOK_POOL_STRING | TOK_NO_TEXT_SAVE | TOK_STRINGARRAY(DynMoveTransition, eaAllStanceWordsSorted), NULL },
	{ "JointStanceWordsSorted",		TOK_POOL_STRING | TOK_NO_TEXT_SAVE | TOK_STRINGARRAY(DynMoveTransition, eaJointStanceWordsSorted), NULL },
	{ "MovementTypeSource",			TOK_POOL_STRING | TOK_STRINGARRAY(DynMoveTransition, eaMovementTypesSource), NULL },
	{ "MovementTypeTarget",			TOK_POOL_STRING | TOK_STRINGARRAY(DynMoveTransition, eaMovementTypesTarget), NULL },
	{ "Move",						TOK_REFERENCE(DynMoveTransition, hMove, 0, "DynMove") },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_DynMoveTransition()
{
	int iSize = sizeof(DynMoveTransition);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_DynMoveTransition, iSize, "DynMoveTransition", NULL, "dynMoveTransition.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
