#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MaterialModelDep
#define TYPE_parse_MaterialModelDep MaterialModelDep
ParseTable parse_MaterialModelDep[] =
{
	{ "MaterialModelDep", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MaterialModelDep), 0, NULL, 0, NULL },
	{ "model_name",			TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_STRING(MaterialModelDep, model_name, 0), NULL },
	{ "material_name",		TOK_STRUCTPARAM | TOK_POOL_STRING | TOK_FILENAME(MaterialModelDep, material_name, NULL), NULL},
	{ "\n",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MaterialModelDep()
{
	int iSize = sizeof(MaterialModelDep);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MaterialModelDep, iSize, "MaterialModelDep", NULL, "Materials.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MaterialModelDep[];
#define TYPE_parse_MaterialModelDep MaterialModelDep
//Structparser.exe autogenerated ParseTable for struct MaterialDeps
#define TYPE_parse_MaterialDeps MaterialDeps
ParseTable parse_MaterialDeps[] =
{
	{ "MaterialDeps", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MaterialDeps), 0, NULL, 0, NULL },
	{ "depfilename",		TOK_POOL_STRING | TOK_CURRENTFILE(MaterialDeps, dep_filename), NULL},
	{ "GeoFile",			TOK_POOL_STRING | TOK_FILENAME(MaterialDeps, src_file, NULL), NULL},
	{ "MaterialDep",		TOK_POOL_STRING | TOK_FILENAMEARRAY(MaterialDeps, dependency), NULL },
	{ "MaterialModelDep",	TOK_STRUCT(MaterialDeps, model_dependency, parse_MaterialModelDep) },
	{ "EndMaterialDeps",	TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MaterialDeps()
{
	int iSize = sizeof(MaterialDeps);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MaterialDeps, iSize, "MaterialDeps", NULL, "Materials.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_MaterialDeps[];
#define TYPE_parse_MaterialDeps MaterialDeps
//Structparser.exe autogenerated ParseTable for struct MaterialDepsQuickList
#define TYPE_parse_MaterialDepsQuickList MaterialDepsQuickList
ParseTable parse_MaterialDepsQuickList[] =
{
	{ "MaterialDepsQuickList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MaterialDepsQuickList), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "MaterialDeps",			TOK_STRUCT(MaterialDepsQuickList, deps_source, parse_MaterialDeps) },
	{ "deps_strings",			TOK_POOL_STRING | TOK_STRINGARRAY(MaterialDepsQuickList, deps_strings), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
TextParserResult fixupMaterialDepsQuick(MaterialDepsQuickList *pStruct, enumTextParserFixupType eFixupType, void *pExtraData);
int autoStruct_fixup_MaterialDepsQuickList()
{
	int iSize = sizeof(MaterialDepsQuickList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MaterialDepsQuickList, iSize, "MaterialDepsQuickList", fixupMaterialDepsQuick, "Materials.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
