#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ResourcePackParsed
#define TYPE_parse_ResourcePackParsed ResourcePackParsed
ParseTable parse_ResourcePackParsed[] =
{
	{ "ResourcePackParsed", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ResourcePackParsed), 0, NULL, 0, NULL },
	{ "Pack",				TOK_START, 0 },
	{ "filename",			TOK_POOL_STRING | TOK_FILENAME(ResourcePackParsed, filename, NULL), NULL},
	{ "packname",			TOK_STRUCTPARAM | TOK_STRING(ResourcePackParsed, pack_name, 0), NULL },
	{ "Folder",				TOK_STRINGARRAY(ResourcePackParsed, packed_dirs), NULL },
	{ "End",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ResourcePackParsed()
{
	int iSize = sizeof(ResourcePackParsed);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ResourcePackParsed, iSize, "ResourcePackParsed", NULL, "wlResourcePack.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
