#ifndef __WLSKY_C_AST_H_
#define __WLSKY_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \wlSky.c
//autogeneratednocheckin

extern ParseTable parse_WLSkyInfo[];
#define TYPE_parse_WLSkyInfo WLSkyInfo

#endif
