//autogeneratednocheckin  this file is autogenerated by structparser
#pragma warning(default:4242)
#ifdef WANT_EXPRCODE_ENUMS_WORLDLIB
#ifndef DEFINED_EXPRCODE_ENUM_VOID_STR_F32_F32_STR
#define DEFINED_EXPRCODE_ENUM_VOID_STR_F32_F32_STR
	EXPRCODE_ENUM_VOID_STR_F32_F32_STR,
#endif
#ifndef DEFINED_EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR
#define DEFINED_EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR
	EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR,
#endif
#ifndef DEFINED_EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR_STR
#define DEFINED_EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR_STR
	EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR_STR,
#endif
#endif //WANT_EXPRCODE_ENUMS_WORLDLIB
#ifdef WANT_EXPRCODE_STATICDEFINE_WORLDLIB
#ifndef DEFINED_EXPRCODE_STATICDEFINE_VOID_STR_F32_F32_STR
#define DEFINED_EXPRCODE_STATICDEFINE_VOID_STR_F32_F32_STR
	{ "VOID_STR_F32_F32_STR", EXPRCODE_ENUM_VOID_STR_F32_F32_STR },
#endif
#ifndef DEFINED_EXPRCODE_STATICDEFINE_VOID_STR_F32_F32_STR_STR
#define DEFINED_EXPRCODE_STATICDEFINE_VOID_STR_F32_F32_STR_STR
	{ "VOID_STR_F32_F32_STR_STR", EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR },
#endif
#ifndef DEFINED_EXPRCODE_STATICDEFINE_VOID_STR_F32_F32_STR_STR_STR
#define DEFINED_EXPRCODE_STATICDEFINE_VOID_STR_F32_F32_STR_STR_STR
	{ "VOID_STR_F32_F32_STR_STR_STR", EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR_STR },
#endif
#endif //WANT_EXPRCODE_STATICDEFINE_WORLDLIB
#ifdef WANT_EXPRCODE_PROTOTYPES_WORLDLIB
#ifndef DEFINED_EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR
#define DEFINED_EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR
typedef void EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR(const char* arg0, F32 arg1, F32 arg2, const char* arg3); //for example, worldSetRegionSkyOverride1
#endif
#ifndef DEFINED_EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR
#define DEFINED_EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR
typedef void EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR(const char* arg0, F32 arg1, F32 arg2, const char* arg3, const char* arg4); //for example, worldSetRegionSkyOverride2
#endif
#ifndef DEFINED_EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR_STR
#define DEFINED_EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR_STR
typedef void EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR_STR(const char* arg0, F32 arg1, F32 arg2, const char* arg3, const char* arg4, const char* arg5); //for example, worldSetRegionSkyOverride3
#endif
#endif // WANT_EXPRCODE_PROTOTYPES_WORLDLIB
#ifdef WANT_EXPRCODE_SWITCH_CASES_WORLDLIB
#ifndef DEFINE_EXPR_SWITCH_CASE_VOID_STR_F32_F32_STR
#define DEFINE_EXPR_SWITCH_CASE_VOID_STR_F32_F32_STR
xcase EXPRCODE_ENUM_VOID_STR_F32_F32_STR:
{
	const char* arg0; 	F32 arg1; 	F32 arg2; 	const char* arg3; 
	arg0 = (char*)(args[0]->str);
	arg1 = QuickGetFloat(args[1]);
	arg2 = QuickGetFloat(args[2]);
	arg3 = (char*)(args[3]->str);
	((EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR*)(pFuncPtr))(arg0, arg1, arg2, arg3);
	return ExprFuncReturnFinished;
};
#endif
#ifndef DEFINE_EXPR_SWITCH_CASE_VOID_STR_F32_F32_STR_STR
#define DEFINE_EXPR_SWITCH_CASE_VOID_STR_F32_F32_STR_STR
xcase EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR:
{
	const char* arg0; 	F32 arg1; 	F32 arg2; 	const char* arg3; 	const char* arg4; 
	arg0 = (char*)(args[0]->str);
	arg1 = QuickGetFloat(args[1]);
	arg2 = QuickGetFloat(args[2]);
	arg3 = (char*)(args[3]->str);
	arg4 = (char*)(args[4]->str);
	((EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR*)(pFuncPtr))(arg0, arg1, arg2, arg3, arg4);
	return ExprFuncReturnFinished;
};
#endif
#ifndef DEFINE_EXPR_SWITCH_CASE_VOID_STR_F32_F32_STR_STR_STR
#define DEFINE_EXPR_SWITCH_CASE_VOID_STR_F32_F32_STR_STR_STR
xcase EXPRCODE_ENUM_VOID_STR_F32_F32_STR_STR_STR:
{
	const char* arg0; 	F32 arg1; 	F32 arg2; 	const char* arg3; 	const char* arg4; 	const char* arg5; 
	arg0 = (char*)(args[0]->str);
	arg1 = QuickGetFloat(args[1]);
	arg2 = QuickGetFloat(args[2]);
	arg3 = (char*)(args[3]->str);
	arg4 = (char*)(args[4]->str);
	arg5 = (char*)(args[5]->str);
	((EXPRCODE_PROTOTYPE_VOID_STR_F32_F32_STR_STR_STR*)(pFuncPtr))(arg0, arg1, arg2, arg3, arg4, arg5);
	return ExprFuncReturnFinished;
};
#endif
#endif // WANT_EXPRCODE_SWITCH_CASES_WORLDLIB
