#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_ModelClusterSource[];
#define TYPE_parse_ModelClusterSource ModelClusterSource
extern ParseTable parse_ModelClusterVolume[];
#define TYPE_parse_ModelClusterVolume ModelClusterVolume
//Structparser.exe autogenerated ParseTable for struct WorldClusterState
#define TYPE_parse_WorldClusterState WorldClusterState
ParseTable parse_WorldClusterState[] =
{
	{ "WorldClusterState", 					TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WorldClusterState), 0, NULL, 0, NULL },
	{ "{",									TOK_START, 0 },
	{ "start_i",							TOK_AUTOINT(WorldClusterState, start_i, 0), NULL },
	{ "end_i",								TOK_AUTOINT(WorldClusterState, end_i, 0), NULL },
	{ "start_j",							TOK_AUTOINT(WorldClusterState, start_j, 0), NULL },
	{ "end_j",								TOK_AUTOINT(WorldClusterState, end_j, 0), NULL },
	{ "start_y",							TOK_AUTOINT(WorldClusterState, start_y, 0), NULL },
	{ "end_y",								TOK_AUTOINT(WorldClusterState, end_y, 0), NULL },
	{ "worldCellsChangedFlag",				TOK_AUTOINT(WorldClusterState, worldCellsChangedFlag, 0), NULL },
	{ "gatherFromLeafLevel",				TOK_AUTOINT(WorldClusterState, gatherFromLeafLevel, 0), NULL },
	{ "cluster_all_levels",					TOK_AUTOINT(WorldClusterState, cluster_all_levels, 0), NULL },
	{ "_cluster_buckets",					TOK_STRUCT(WorldClusterState, ea_cluster_buckets, parse_ModelClusterSource) },
	{ "timeClusteringStart",				TOK_AUTOINT(WorldClusterState, timeClusteringStart, 0), NULL },
	{ "timeClusteringComplete",				TOK_AUTOINT(WorldClusterState, timeClusteringComplete, 0), NULL },
	{ "numDistributedRemeshes",				TOK_AUTOINT(WorldClusterState, numDistributedRemeshes, 0), NULL },
	{ "processed_blocks",					TOK_AUTOINT(WorldClusterState, processed_blocks, 0), NULL },
	{ "total_blocks",						TOK_AUTOINT(WorldClusterState, total_blocks, 0), NULL },
	{ "current_region_idx",					TOK_AUTOINT(WorldClusterState, current_region_idx, 0), NULL },
	{ "total_regions",						TOK_AUTOINT(WorldClusterState, total_regions, 0), NULL },
	{ "clusterTempBinPath",					TOK_FIXEDSTR(WorldClusterState, clusterTempBinPath), NULL },
	{ "clusterBinPath",						TOK_FIXEDSTR(WorldClusterState, clusterBinPath), NULL },
	{ "clusterTempImagePath",				TOK_FIXEDSTR(WorldClusterState, clusterTempImagePath), NULL },
	{ "clusterTempImageFullPath",			TOK_FIXEDSTR(WorldClusterState, clusterTempImageFullPath), NULL },
	{ "clusterCacheHoggFile",				TOK_FIXEDSTR(WorldClusterState, clusterCacheHoggFile), NULL },
	{ "clusterClientRegionBinFile",			TOK_FIXEDSTR(WorldClusterState, clusterClientRegionBinFile), NULL },
	{ "clusterClientRegionBinFileFullPath",	TOK_FIXEDSTR(WorldClusterState, clusterClientRegionBinFileFullPath), NULL },
	{ "cluster_volumes",					TOK_STRUCT(WorldClusterState, cluster_volumes, parse_ModelClusterVolume) },
	{ "}",									TOK_END, 0 },
	{ "", 0, 0 }
};
TextParserResult fixupWorldClusterState(WorldClusterState *pStruct, enumTextParserFixupType eFixupType, void *pExtraData);
int autoStruct_fixup_WorldClusterState()
{
	int iSize = sizeof(WorldClusterState);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WorldClusterState, iSize, "WorldClusterState", fixupWorldClusterState, "WorldCellClustering.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ModelClusterSource[];
#define TYPE_parse_ModelClusterSource ModelClusterSource
extern ParseTable parse_RemeshMaterial[];
#define TYPE_parse_RemeshMaterial RemeshMaterial
extern ParseTable parse_WorldClusterStats[];
#define TYPE_parse_WorldClusterStats WorldClusterStats
//Structparser.exe autogenerated ParseTable for struct worldCellClusterGenerateCellClusterData
#define TYPE_parse_worldCellClusterGenerateCellClusterData worldCellClusterGenerateCellClusterData
ParseTable parse_worldCellClusterGenerateCellClusterData[] =
{
	{ "worldCellClusterGenerateCellClusterData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(worldCellClusterGenerateCellClusterData), 0, NULL, 0, NULL },
	{ "{",											TOK_START, 0 },
	{ "source_models",								TOK_OPTIONALSTRUCT(worldCellClusterGenerateCellClusterData, source_models, parse_ModelClusterSource) },
	{ "unprocessedChildrenRemaining",				TOK_AUTOINT(worldCellClusterGenerateCellClusterData, unprocessedChildrenRemaining, 0), NULL },
	{ "remeshState",								TOK_AUTOINT(worldCellClusterGenerateCellClusterData, remeshState, 0), NULL },
	{ "timeTaskRequestIssued",						TOK_AUTOINT(worldCellClusterGenerateCellClusterData, timeTaskRequestIssued, 0), NULL },
	{ "timeTaskAutoRetry",							TOK_AUTOINT(worldCellClusterGenerateCellClusterData, timeTaskAutoRetry, 0), NULL },
	{ "WroteClientBins",							TOK_AUTOINT(worldCellClusterGenerateCellClusterData, bWroteClientBins, 0), NULL },
	{ "remeshClusterMaterial",						TOK_OPTIONALSTRUCT(worldCellClusterGenerateCellClusterData, remeshClusterMaterial, parse_RemeshMaterial) },
	{ "buildStats",									TOK_EMBEDDEDSTRUCT(worldCellClusterGenerateCellClusterData, buildStats, parse_WorldClusterStats)},
	{ "clusterBaseName",							TOK_FIXEDSTR(worldCellClusterGenerateCellClusterData, clusterBaseName), NULL },
	{ "remeshGMeshName",							TOK_FIXEDSTR(worldCellClusterGenerateCellClusterData, remeshGMeshName), NULL },
	{ "diffuseTexName",								TOK_FIXEDSTR(worldCellClusterGenerateCellClusterData, diffuseTexName), NULL },
	{ "normalTexName",								TOK_FIXEDSTR(worldCellClusterGenerateCellClusterData, normalTexName), NULL },
	{ "specularTexName",							TOK_FIXEDSTR(worldCellClusterGenerateCellClusterData, specularTexName), NULL },
	{ "taskParameterHoggFile",						TOK_FIXEDSTR(worldCellClusterGenerateCellClusterData, taskParameterHoggFile), NULL },
	{ "taskResultHoggFile",							TOK_FIXEDSTR(worldCellClusterGenerateCellClusterData, taskResultHoggFile), NULL },
	{ "}",											TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_worldCellClusterGenerateCellClusterData()
{
	int iSize = sizeof(worldCellClusterGenerateCellClusterData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_worldCellClusterGenerateCellClusterData, iSize, "worldCellClusterGenerateCellClusterData", NULL, "WorldCellClustering.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
