#pragma once

#include "Organization.h"

#define DEFAULT_PATCHSERVER			ORGANIZATION_DOMAIN
#define DEFAULT_PATCHSERVER_PORT	7255

#define DEFAULT_MAX_NET_BYTES		(5*1024*1024)

#define MAX_SINGLE_REQUEST_BYTES	4096
#define HEADER_BLOCK_SIZE			256

#define PCL_SLIPSTREAM_THRESHOLD 4096

enum {
	#if 0
		// Original
		PATCHCLIENT_VERSION_ORIGINAL = 0,

		// Added version checking (when view is set)
		PATCHCLIENT_VERSION_VERSIONCHECK = 1,

		// Changed version checking to connect-time, client redirection
		PATCHCLIENT_VERSION_REDIRECTION = 2,

		// Changed manifest format and added expiration to named views
		PATCHCLIENT_VERSION_SLIMMERMANIFEST	= 3,

		// PatchClients before version 4 are no longer supported! The code has been removed (svn 49820 or so)
	#endif

	// Root directory is no longer named, other massive changes
	PATCHCLIENT_VERSION_NAMELESSROOT = 4,

	// Ver 4 clients forget how to update after a redirect
	PATCHCLIENT_VERSION_AUTOUPDATEFIX = 5,

	// Starting using revision numbers instead of timestamps
	PATCHCLIENT_VERSION_REVISIONNUMBERS = 6,

	// Starting supporting queries in patchme without updating the manifest
	PATCHCLIENT_VERSION_MANIFESTLESS_QUERIES = 7,
	
	// Client-side compression of checkins.  Named views have comments.
	PATCHCLIENT_VERSION_CLIENT_CHECKIN_COMPRESSION = 8,
	PATCHCLIENT_VERSION_NAMED_VIEW_COMMENTS = 8,
	PATCHCLIENT_VERSION_OLD_VERSION_SCHEME = 8,

	// Patch Server as a client supports HTTP patching information updates
	PATCHCLIENT_VERSION_HTTPINFO = 9,

	// Patch Server as a client supports Autoupdate patching information updates
	PATCHCLIENT_VERSION_AUTOUPINFO = 10,

	// --------------------------- CURRENT VERSION -------------------------------------
	// Must be right after the last version.
	PATCHCLIENT_VERSION_CURRENT_PLUS_ONE,
	PATCHCLIENT_VERSION_CURRENT = PATCHCLIENT_VERSION_CURRENT_PLUS_ONE - 1,

	// The lowest supported version.
	PATCHCLIENT_VERSION_SUPPORTED = PATCHCLIENT_VERSION_NAMELESSROOT,
};


// NetLink options
#define PATCHER_LINK_COMPRESSION_ON 0

AUTO_ENUM;
typedef enum PatchServerCmd // In case you were wondering, NEVER change the order of these
{
	PATCHSERVER_CONNECT_OK = 1,
	PATCHSERVER_FINGERPRINTS,
	PATCHSERVER_BLOCKS,
	PATCHSERVER_FILEINFO,
	PATCHSERVER_PROJECT_VIEW_STATUS,
	PATCHSERVER_AUTHOR_RESPONSE,
	PATCHSERVER_FILE_HISTORY_DEPRECATED,
	PATCHSERVER_LOCK,
	PATCHSERVER_CHECKIN,
	PATCHSERVER_FORCEIN,
	PATCHSERVER_BLOCK_RECV,
	PATCHSERVER_FINISH_CHECKIN,
	PATCHSERVER_FINISH_FORCEIN,
	PATCHSERVER_VIEW_NAMED,
	PATCHSERVER_UPDATE,
	PATCHSERVER_BLOCKS_COMPRESSED,
	PATCHSERVER_HEADERINFO,
	PATCHSERVER_HEADER_BLOCKS,
	PATCHSERVER_PROJECT_LIST,
	PATCHSERVER_NAME_LIST,
	PATCHSERVER_FINGERPRINTS_COMPRESSED,
	PATCHSERVER_EXPIRATION_SET,
	PATCHSERVER_UNLOCK,
	PATCHSERVER_DONT_RECONNECT,
	PATCHSERVER_AUTOUPDATE_FILE,
	PATCHSERVER_VERSION_INFO,
	PATCHSERVER_BRANCH_INFO,
	PATCHSERVER_CHECK_DELETED,
	PATCHSERVER_LASTAUTHOR,
	PATCHSERVER_LOCKAUTHOR,
	PATCHSERVER_FILE_HISTORY_STRUCTS,
	PATCHSERVER_CHECKINS_BETWEEN_TIMES,
	PATCHSERVER_CHECKIN_INFO,
	PATCHSERVER_FILEVERSIONINFO,
	PATCHSERVER_PONG,
	PATCHSERVER_IS_COMPLETELY_SYNCED_RESPONSE,
	PATCHSERVER_FILE_EXPIRATION_SET,
	PATCHSERVER_UPDATE_HTTPINFO,
	PATCHSERVER_BAD_PACKET,
	PATCHSERVER_UPDATE_AUTOUPINFO,

	PATCHSERVER_CMD_COUNT,
} PatchServerCmd;

enum {
	// Version 0 of DynamicAutoupConfig parse table. This allows us to due a fixup in the future if we want to change the data format of DynamicAutoupConfig
	AUTOUPINFO_VERSION_0 = 0,

	// --------------------------- CURRENT VERSION -------------------------------------
	// Must be right after the last version.
	AUTOUPINFO_VERSION_CURRENT_PLUS_ONE,
	AUTOUPINFO_VERSION_CURRENT = AUTOUPINFO_VERSION_CURRENT_PLUS_ONE - 1
};

AUTO_ENUM;
typedef enum PatchClientCmd // In case you were wondering, NEVER change the order of these
{
	PATCHCLIENT_CONNECT = 1,
	PATCHCLIENT_REQ_FINGERPRINTS,
	PATCHCLIENT_REQ_BLOCKS,
	PATCHCLIENT_REQ_FILEINFO,
	PATCHCLIENT_SET_PROJECT_VIEW_BY_TIME,
	PATCHCLIENT_SET_PROJECT_VIEW_DEFAULT,
	PATCHCLIENT_SET_PROJECT_VIEW_NAME,
	PATCHCLIENT_SET_AUTHOR,
	PATCHCLIENT_REQ_FILE_HISTORY_DEPRECATED,
	PATCHCLIENT_REQ_LOCK,
	PATCHCLIENT_REQ_CHECKIN,
	PATCHCLIENT_REQ_FORCEIN,
	PATCHCLIENT_BLOCK_SEND,
	PATCHCLIENT_FINISH_CHECKIN,
	PATCHCLIENT_FINISH_FORCEIN,
	PATCHCLIENT_NAME_VIEW,
	PATCHCLIENT_REQ_NOTIFICATION,
	PATCHCLIENT_REQ_NOTIFICATION_OFF,
	PATCHCLIENT_REQ_BLOCKS_COMPRESSED,
	PATCHCLIENT_REQ_HEADERINFO,
	PATCHCLIENT_REQ_HEADER_BLOCKS,
	PATCHCLIENT_REQ_PROJECT_LIST,
	PATCHCLIENT_REQ_NAME_LIST,
	PATCHCLIENT_REQ_FINGERPRINTS_COMPRESSED,
	PATCHCLIENT_SET_EXPIRATION,
	PATCHCLIENT_REQ_UNLOCK,
	PATCHCLIENT_SET_PROJECT_VIEW_NEW_INCREMENTAL,
	PATCHCLIENT_REQ_AUTOUPDATE,
	PATCHCLIENT_REQ_VERSION_INFO,
	PATCHCLIENT_REQ_BRANCH_INFO,
	PATCHCLIENT_SET_PROJECT_VIEW_BY_REV,
	PATCHCLIENT_CHECK_DELETED,
	PATCHCLIENT_SHUTDOWN,
	PATCHCLIENT_REQ_LASTAUTHOR,
	PATCHCLIENT_REQ_LOCKAUTHOR,
	PATCHCLIENT_REQ_FILE_HISTORY_STRUCTS,
	PATCHCLIENT_REQ_CHECKINS_BETWEEN_TIMES,
	PATCHCLIENT_NOTIFYVIEW,
	PATCHCLIENT_REQ_CHECKIN_INFO,
	PATCHCLIENT_REQ_FILEVERSIONINFO,
	PATCHCLIENT_LOG,
	PATCHCLIENT_REQ_UNDO_CHECKIN,
	PATCHCLIENT_PING,
	PATCHCLIENT_HEARTBEAT,
	PATCHCLIENT_SET_PREFIX,
	PATCHCLIENT_SET_PROJECT_VIEW_NEW_INCREMENTAL_NAME,
	PATCHCLIENT_PATCHSERVER_ACTIVATED,
	PATCHCLIENT_PATCHSERVER_DEACTIVATED,
	PATCHCLIENT_PATCHSERVER_UPDATE_STATUS,
	PATCHCLIENT_REQ_COMPLETELY_SYNCED,
	PATCHCLIENT_SET_FILE_EXPIRATION,
	PATCHCLIENT_SERVER_MERGE,								// Request that the Patch Server run its merger.

	PATCHCLIENT_CMD_COUNT,
} PatchClientCmd;

typedef enum PatchServerLastAuthorResponse // Do not reorder!
{
	LASTAUTHOR_GOT_AUTHOR,	// Followed by string
	LASTAUTHOR_ERROR,		// Followed by string
	LASTAUTHOR_NOT_IN_DATABASE,
	LASTAUTHOR_CHECKEDOUT,
	LASTAUTHOR_NOT_LATEST,
} PatchServerLastAuthorResponse;

// Performance Reporting: Statistics for a particular command packet type
AUTO_STRUCT;
typedef struct PatchMsgPerfInfo
{
	const char *cmd;
	U64 count;
	float duration;
	float minDuration;
	float maxDuration;
} PatchMsgPerfInfo;

// Performance Reporting: Server data and array of PatchMsgPerfInfo
AUTO_STRUCT;
typedef struct PatchMsgPerfInfos
{
	const char *server;
	EARRAY_OF(PatchMsgPerfInfo) cmds;
	U64 totalCount;
	float totalDuration;
	float totalMinDuration;
	float totalMaxDuration;
} PatchMsgPerfInfos;
