//For more info on remote commands, look here: http://crypticwiki:8081/display/Core/AUTO_COMMAND_REMOTE+and+AUTO_COMMAND_REMOTE_SLOW
//This file is autogenerated. autogeneratednocheckin
#pragma once
GCC_SYSTEM
#include "RemoteAutoCommandSupport.h"
#include "objtransactions.h"
#include "textparser.h"

//autogenerated function used to return the value from slow command AttemptToBootPlayerWithBooter_Outer
//defined in file I:\Night\Night\src\libs\ServerLib\PlayerBooter.c
typedef struct PlayerBooterResult PlayerBooterResult;
extern ParseTable parse_PlayerBooterResult[];
void SlowRemoteCommandReturn_AttemptToBootPlayerWithBooter_Outer(SlowRemoteCommandID iCmdID, PlayerBooterResult* retVal);

//autogenerated function used to return the value from slow command SlowCmdNeverReturns
//defined in file I:\Night\Night\src\libs\ServerLib\ServerLib.c
void SlowRemoteCommandReturn_SlowCmdNeverReturns(SlowRemoteCommandID iCmdID, int retVal);

//autogenerated function used to return the value from slow command TestJobStep
//defined in file I:\Night\Night\src\libs\ServerLib\JobManagerSupport.c
void SlowRemoteCommandReturn_TestJobStep(SlowRemoteCommandID iCmdID, int retVal);

//autogenerated function used to return the value from slow command slowTest
//defined in file I:\Night\Night\src\libs\ServerLib\serverlib_structparsertests.c
void SlowRemoteCommandReturn_slowTest(SlowRemoteCommandID iCmdID, char* retVal);
