#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct PendingXMLRPCRequest
#define TYPE_parse_PendingXMLRPCRequest PendingXMLRPCRequest
ParseTable parse_PendingXMLRPCRequest[] =
{
	{ "PendingXMLRPCRequest", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PendingXMLRPCRequest), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "RequestTimeClockTicks",	TOK_AUTOINT(PendingXMLRPCRequest, iRequestTimeClockTicks, 0), NULL },
	{ "RequestID",				TOK_AUTOINT(PendingXMLRPCRequest, iRequestID, 0), NULL },
	{ "MCPID",					TOK_AUTOINT(PendingXMLRPCRequest, iMCPID, 0), NULL },
	{ "iclientID",				TOK_AUTOINT(PendingXMLRPCRequest, iclientID, 0), NULL },
	{ "requestTimeout",			TOK_F32(PendingXMLRPCRequest, requestTimeout, 60.0), NULL },
	{ "ErrorAsText",			TOK_AUTOINT(PendingXMLRPCRequest, iErrorAsText, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_PendingXMLRPCRequest()
{
	int iSize = sizeof(PendingXMLRPCRequest);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_PendingXMLRPCRequest, iSize, "PendingXMLRPCRequest", NULL, "HttpLib.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	parse_PendingXMLRPCRequest[6].param = GET_INTPTR_FROM_FLOAT((float)60.0);
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_PendingXMLRPCRequest[];
#define TYPE_parse_PendingXMLRPCRequest PendingXMLRPCRequest
//Structparser.exe autogenerated ParseTable for struct HttpClientStateDefault
#define TYPE_parse_HttpClientStateDefault HttpClientStateDefault
ParseTable parse_HttpClientStateDefault[] =
{
	{ "HttpClientStateDefault", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(HttpClientStateDefault), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "PostHeaderString",		TOK_ESTRING | TOK_STRING(HttpClientStateDefault, pPostHeaderString, 0), NULL },
	{ "PostDataString",			TOK_ESTRING | TOK_STRING(HttpClientStateDefault, pPostDataString, 0), NULL },
	{ "AuthUserName",			TOK_ESTRING | TOK_STRING(HttpClientStateDefault, pAuthUserName, 0), NULL },
	{ "AuthStringCRC",			TOK_AUTOINT(HttpClientStateDefault, iAuthStringCRC, 0), NULL },
	{ "WaitingForPostData",		TOK_AUTOINT(HttpClientStateDefault, bWaitingForPostData, 0), NULL },
	{ "requestTime",			TOK_AUTOINT(HttpClientStateDefault, requestTime, 0), NULL },
	{ "req",					TOK_OPTIONALSTRUCT(HttpClientStateDefault, req, parse_PendingXMLRPCRequest) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_HttpClientStateDefault()
{
	int iSize = sizeof(HttpClientStateDefault);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_HttpClientStateDefault, iSize, "HttpClientStateDefault", NULL, "HttpLib.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
