#include "textparser.h"
#ifndef _XBOX
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct XML_TestStruct
#define TYPE_parse_XML_TestStruct XML_TestStruct
ParseTable parse_XML_TestStruct[] =
{
	{ "XML_TestStruct", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(XML_TestStruct), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "i",				TOK_AUTOINT(XML_TestStruct, i, 0), NULL },
	{ "f",				TOK_F32(XML_TestStruct, f, 0), NULL },
	{ "aint",			TOK_INTARRAY(XML_TestStruct, aint),  NULL},
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_XML_TestStruct()
{
	int iSize = sizeof(XML_TestStruct);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_XML_TestStruct, iSize, "XML_TestStruct", NULL, "XMLRPC.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
#endif //_XBOX
#ifndef _XBOX
//autogeneratednocheckin
extern ParseTable parse_XML_TestStruct[];
#define TYPE_parse_XML_TestStruct XML_TestStruct
//Structparser.exe autogenerated ParseTable for struct XML_CollectionOfStuff
#define TYPE_parse_XML_CollectionOfStuff XML_CollectionOfStuff
ParseTable parse_XML_CollectionOfStuff[] =
{
	{ "XML_CollectionOfStuff", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(XML_CollectionOfStuff), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ptrs",					TOK_STRUCT(XML_CollectionOfStuff, ptrs, parse_XML_TestStruct) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_XML_CollectionOfStuff()
{
	int iSize = sizeof(XML_CollectionOfStuff);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_XML_CollectionOfStuff, iSize, "XML_CollectionOfStuff", NULL, "XMLRPC.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
#endif //_XBOX
