#ifndef __JSONRPC_C_AST_H_
#define __JSONRPC_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \JSONRPC.c
//autogeneratednocheckin

extern ParseTable parse_Placeholder[];
#define TYPE_parse_Placeholder Placeholder

extern ParseTable parse_ResponseTemplate[];
#define TYPE_parse_ResponseTemplate ResponseTemplate

#endif
