#ifndef __WICOMMONINTERNAL_H_AST_H_
#define __WICOMMONINTERNAL_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \wiCommonInternal.h
//autogeneratednocheckin

extern ParseTable parse_WICWebRequest[];
#define TYPE_parse_WICWebRequest WICWebRequest

extern ParseTable parse_WICommonWebSite[];
#define TYPE_parse_WICommonWebSite WICommonWebSite

extern ParseTable parse_WICWebRequestData[];
#define TYPE_parse_WICWebRequestData WICWebRequestData

#endif
