#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct WICWebRequest
#define TYPE_parse_WICWebRequest WICWebRequest
ParseTable parse_WICWebRequest[] =
{
	{ "WICWebRequest", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WICWebRequest), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "NumericAccessLevel",	TOK_AUTOINT(WICWebRequest, iAccessLevel, 0), NULL },
	{ "AccessLevel",		TOK_AUTOINT(WICWebRequest, eAccessLevel, 0), WIAccessLevelEnum },
	{ "RawFileName",		TOK_ESTRING | TOK_STRING(WICWebRequest, pRawFileName, 0), NULL },
	{ "Result",				TOK_AUTOINT(WICWebRequest, eResult, 0), WIResultEnum },
	{ "DumpHDF",			TOK_BIT, 0, 8, NULL},
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
void FindAutoStructBitField(char *pStruct, int iAllocedSizeInWords, ParseTable *pTPIColumn);
int autoStruct_fixup_WICWebRequest()
{
	int iSize = sizeof(WICWebRequest);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WICWebRequest, iSize, "WICWebRequest", NULL, "wiCommonInternal.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	{
		int iSizeInWords = (sizeof(WICWebRequest) + 7) / 4;
		WICWebRequest *pTemp = alloca(iSizeInWords * 4);
		memset(pTemp, 0, iSizeInWords * 4);
		pTemp->bDumpHDF = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_WICWebRequest[6]);
		pTemp->bDumpHDF = 0;
	}
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct WICommonWebSite
#define TYPE_parse_WICommonWebSite WICommonWebSite
ParseTable parse_WICommonWebSite[] =
{
	{ "WICommonWebSite", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WICommonWebSite), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Version",			TOK_UNOWNED | TOK_STRING(WICommonWebSite, pVersion, 0), NULL },
	{ "BuildVersion",		TOK_UNOWNED | TOK_STRING(WICommonWebSite, pBuildVersion, 0), NULL },
	{ "Instance",			TOK_ESTRING | TOK_STRING(WICommonWebSite, pInstance, 0), NULL },
	{ "Access",				TOK_UNOWNED | TOK_STRING(WICommonWebSite, pAccess, 0), NULL },
	{ "Content",			TOK_STRING(WICommonWebSite, pContent, 0), NULL },
	{ "Extension",			TOK_UNOWNED | TOK_STRING(WICommonWebSite, pExtension, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_WICommonWebSite()
{
	int iSize = sizeof(WICommonWebSite);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WICommonWebSite, iSize, "WICommonWebSite", NULL, "wiCommonInternal.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_HttpVars[];
#define TYPE_parse_HttpVars HttpVars
//Structparser.exe autogenerated ParseTable for struct WICWebRequestData
#define TYPE_parse_WICWebRequestData WICWebRequestData
ParseTable parse_WICWebRequestData[] =
{
	{ "WICWebRequestData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(WICWebRequestData), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Vars",				TOK_STRUCT(WICWebRequestData, eaVars, parse_HttpVars) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_WICWebRequestData()
{
	int iSize = sizeof(WICWebRequestData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_WICWebRequestData, iSize, "WICWebRequestData", NULL, "wiCommonInternal.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
