//This file contains data and prototypes for magic commands. It is autogenerated by StructParser

//autogeneratednocheckin
#include "cmdparse.h"
#include "textparser.h"
#include "globaltypes.h"
#include "net/net.h"
#include "net/netpacketutil.h"
#include "structnet.h"
#include "structInternals.h"
static char sContentLibName[] = "ContentLib";
//if one of these includes fails, you're trying to use expression list commands somewhere illegal... talk to Raoul
#include "ExpressionMinimal.h"
#include "ExpressionFunc.h"
#include "ScratchStack.h"
#include "mathutil.h"
#include "timing.h"
typedef struct Entity Entity;
extern void OutputDictionaryInfo(const char* dictionaryName, const char* fileName); // function defined in I:\Night\Night\src\libs\ContentLib\ResourceCommands.c
static void OutputDictionaryInfo_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS2(char*, arg0, char*, arg1);
	OutputDictionaryInfo(arg0, arg1);
}
extern void OutputObjectInfo(const char* dictionaryName, const char* resourceName, const char* fileName); // function defined in I:\Night\Night\src\libs\ContentLib\ResourceCommands.c
static void OutputObjectInfo_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS3(char*, arg0, char*, arg1, char*, arg2);
	OutputObjectInfo(arg0, arg1, arg2);
}
extern void PerformDataCopy(const char* fileName); // function defined in I:\Night\Night\src\libs\ContentLib\ResourceCommands.c
static void PerformDataCopy_MAGICCOMMANDWRAPPER(CMDARGS) { 	READARGS1(char*, arg0);
	PerformDataCopy(arg0);
}
extern void resVerifyWritable( void ); // function defined in I:\Night\Night\src\libs\ContentLib\ResourceDataBackend.c
static void resVerifyWritable_MAGICCOMMANDWRAPPER(CMDARGS) { 	resVerifyWritable();
}
static Cmd cmdSetData_OutputDictionaryInfo[] = {
	{ 9, "OutputDictionaryInfo", "ResourceCommands.c", 82, NULL, sContentLibName, NULL, {{"dictionaryName", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }, {"fileName", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0 | CMDF_COMMANDLINE | CMDF_COMMANDLINEONLY,
		"No comment provided", OutputDictionaryInfo_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdSetData_OutputObjectInfo[] = {
	{ 9, "OutputObjectInfo", "ResourceCommands.c", 88, NULL, sContentLibName, NULL, {{"dictionaryName", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }, {"resourceName", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }, {"fileName", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0 | CMDF_COMMANDLINE | CMDF_COMMANDLINEONLY,
		"No comment provided", OutputObjectInfo_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdSetData_PerformDataCopy[] = {
	{ 9, "PerformDataCopy", "ResourceCommands.c", 94, NULL, sContentLibName, NULL, {{"fileName", MULTI_STRING, 0, 0, CMDAF_ALLOCATED, 0,  NAMELISTTYPE_NONE, NULL }},0 | CMDF_COMMANDLINE | CMDF_COMMANDLINEONLY,
		"No comment provided", PerformDataCopy_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};
static Cmd cmdSetData_resVerifyWritable[] = {
	{ 9, "resVerifyWritable", "ResourceDataBackend.c", 98, NULL, sContentLibName, NULL, {{0}},0,
		"Checks the read-only status against the filesystem for all ResourceInfos\n", resVerifyWritable_MAGICCOMMANDWRAPPER,{NULL,MULTI_NONE,NULL,0,0}, NULL}
	
};


extern CmdList gRemoteCmdList;
extern CmdList gSlowRemoteCmdList;
extern ParseTable parse_Entity[];
void Add_Auto_Cmds_ContentLib(void)
{
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdSetData_OutputDictionaryInfo[0]);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdSetData_OutputObjectInfo[0]);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdSetData_PerformDataCopy[0]);
	cmdAddSingleCmdToList(&gGlobalCmdList, &cmdSetData_resVerifyWritable[0]);
};
void Add_Auto_Cmds_ContentLib_Later(void)
{
};
#pragma warning (disable:4054) // casting function pointers as data pointers

#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
4
 2129920 0 "OutputDictionaryInfo" "OutputDictionaryInfo"  ""  ""  ""  ""  ""  ""  ""  "" 9 "" 0 "I:\Night\Night\src\libs\ContentLib\ResourceCommands.c" 82 "No comment provided"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 2 7 "char*" "dictionaryName" "" "" 0 0 0 0 0 "" 7 "char*" "fileName" "" "" 0 0 0 0 0 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  "" "" "" 0 0 0 0 0 0  0  0 
 2129920 0 "OutputObjectInfo" "OutputObjectInfo"  ""  ""  ""  ""  ""  ""  ""  "" 9 "" 0 "I:\Night\Night\src\libs\ContentLib\ResourceCommands.c" 88 "No comment provided"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 3 7 "char*" "dictionaryName" "" "" 0 0 0 0 0 "" 7 "char*" "resourceName" "" "" 0 0 0 0 0 "" 7 "char*" "fileName" "" "" 0 0 0 0 0 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  "" "" "" "" 0 0 0 0 0 0 0 0  0  0 
 2129920 0 "PerformDataCopy" "PerformDataCopy"  ""  ""  ""  ""  ""  ""  ""  "" 9 "" 0 "I:\Night\Night\src\libs\ContentLib\ResourceCommands.c" 94 "No comment provided"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 1 7 "char*" "fileName" "" "" 0 0 0 0 0 "" 0  ""  ""  ""  ""  ""  ""  ""  ""  "" "" 0 0 0 0  0  0 
 0 0 "resVerifyWritable" "resVerifyWritable"  ""  ""  ""  ""  ""  ""  ""  "" 9 "" 0 "I:\Night\Night\src\libs\ContentLib\ResourceDataBackend.c" 98 "Checks the read-only status against the filesystem for all ResourceInfos\n"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  0 "void" "" 0 "" 0 0 0  ""  ""  ""  ""  ""  ""  ""  ""  "" 0 0  0  0 
0
#endif
