#include "textparser.h"

//auto-generated staticdefine for enum BuildScriptingContextChildBehaviorFlags
//autogeneratednocheckin
StaticDefineInt BuildScriptingContextChildBehaviorFlagsEnum[] =
{
	DEFINE_INT
	{ "FAILURE_IS_NONFATAL_FOR_PARENT", FAILURE_IS_NONFATAL_FOR_PARENT},
	{ "NON_INTERRUPTIBLE", NON_INTERRUPTIBLE},
	DEFINE_END
};
void autoEnum_fixup_BuildScriptingContextChildBehaviorFlags(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(BuildScriptingContextChildBehaviorFlagsEnum, "BuildScriptingContextChildBehaviorFlags");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct BuildScriptingVariable
#define TYPE_parse_BuildScriptingVariable BuildScriptingVariable
ParseTable parse_BuildScriptingVariable[] =
{
	{ "BuildScriptingVariable", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(BuildScriptingVariable), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "VarName",				TOK_STRING(BuildScriptingVariable, pVarName, 0), NULL },
	{ "VarValue",				TOK_STRING(BuildScriptingVariable, pVarValue, 0), NULL },
	{ "Comment",				TOK_STRING(BuildScriptingVariable, pComment, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_BuildScriptingVariable()
{
	int iSize = sizeof(BuildScriptingVariable);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_BuildScriptingVariable, iSize, "BuildScriptingVariable", NULL, "BuildScripting.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_BuildScriptingVariable[];
#define TYPE_parse_BuildScriptingVariable BuildScriptingVariable
extern ParseTable parse_BuildScriptingVariable[];
#define TYPE_parse_BuildScriptingVariable BuildScriptingVariable
extern ParseTable parse_BuildScriptingVariable[];
#define TYPE_parse_BuildScriptingVariable BuildScriptingVariable
//Structparser.exe autogenerated ParseTable for struct BuildScriptingVariableList
#define TYPE_parse_BuildScriptingVariableList BuildScriptingVariableList
ParseTable parse_BuildScriptingVariableList[] =
{
	{ "BuildScriptingVariableList", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(BuildScriptingVariableList), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "ScriptingVariables",				TOK_STRUCT(BuildScriptingVariableList, ppScriptingVariables, parse_BuildScriptingVariable) },
	{ "StartingVariables",				TOK_STRUCT(BuildScriptingVariableList, ppStartingVariables, parse_BuildScriptingVariable) },
	{ "ResettableStartingVariables",	TOK_STRUCT(BuildScriptingVariableList, ppResettableStartingVariables, parse_BuildScriptingVariable) },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_BuildScriptingVariableList()
{
	int iSize = sizeof(BuildScriptingVariableList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_BuildScriptingVariableList, iSize, "BuildScriptingVariableList", NULL, "BuildScripting.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_BuildScriptCommand[];
#define TYPE_parse_BuildScriptCommand BuildScriptCommand
//Structparser.exe autogenerated ParseTable for struct BuildScriptCommandList
#define TYPE_parse_BuildScriptCommandList BuildScriptCommandList
ParseTable parse_BuildScriptCommandList[] =
{
	{ "BuildScriptCommandList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(BuildScriptCommandList), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Command",				TOK_STRUCT(BuildScriptCommandList, ppCommands, parse_BuildScriptCommand) , 0 , "DEFAULT_FIELD = 1"},
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_BuildScriptCommandList()
{
	int iSize = sizeof(BuildScriptCommandList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_BuildScriptCommandList, iSize, "BuildScriptCommandList", NULL, "BuildScripting.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_BuildScriptCommandList[];
#define TYPE_parse_BuildScriptCommandList BuildScriptCommandList
extern ParseTable parse_BuildScriptingVariableList[];
#define TYPE_parse_BuildScriptingVariableList BuildScriptingVariableList
extern ParseTable parse_BuildScriptingContext[];
#define TYPE_parse_BuildScriptingContext BuildScriptingContext
extern ParseTable parse_BuildScriptingContext[];
#define TYPE_parse_BuildScriptingContext BuildScriptingContext
//Structparser.exe autogenerated ParseTable for struct BuildScriptingContext
#define TYPE_parse_BuildScriptingContext BuildScriptingContext
ParseTable parse_BuildScriptingContext[] =
{
	{ "BuildScriptingContext", 										TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(BuildScriptingContext), 0, NULL, 0, NULL },
	{ "{",															TOK_START, 0 },
	{ "ContextName",												TOK_ESTRING | TOK_STRING(BuildScriptingContext, pContextName, 0), NULL },
	{ "BuildScriptingFailTime",										TOK_AUTOINT(BuildScriptingContext, iBuildScriptingFailTime, 0), NULL },
	{ "FailAfterDelayCalled",										TOK_AUTOINT(BuildScriptingContext, bFailAfterDelayCalled, 0), NULL },
	{ "SkipCurrentStep",											TOK_AUTOINT(BuildScriptingContext, bSkipCurrentStep, 0), NULL },
	{ "FailureLinkString",											TOK_ESTRING | TOK_STRING(BuildScriptingContext, pFailureLinkString, 0), NULL },
	{ "InternalIncludeDepth",										TOK_AUTOINT(BuildScriptingContext, iInternalIncludeDepth, 0), NULL },
	{ "CurForDepth",												TOK_AUTOINT(BuildScriptingContext, iCurForDepth, 0), NULL },
	{ "InSpecialFailingModeWaitingForUninterruptibleChildContexts",	TOK_AUTOINT(BuildScriptingContext, bInSpecialFailingModeWaitingForUninterruptibleChildContexts, 0), NULL },
	{ "ForceAbort",													TOK_AUTOINT(BuildScriptingContext, bForceAbort, 0), NULL },
	{ "TestingOnly",												TOK_AUTOINT(BuildScriptingContext, bTestingOnly, 0), NULL },
	{ "AbortAndCloseInstantly",										TOK_AUTOINT(BuildScriptingContext, bAbortAndCloseInstantly, 0), NULL },
	{ "ScriptState",												TOK_AUTOINT(BuildScriptingContext, eScriptState, 0), enumBuildScriptStateEnum },
	{ "commandList",												TOK_EMBEDDEDSTRUCT(BuildScriptingContext, commandList, parse_BuildScriptCommandList)},
	{ "CurCommandNum",												TOK_AUTOINT(BuildScriptingContext, iCurCommandNum, 0), NULL },
	{ "ThereWereErrors",											TOK_AUTOINT(BuildScriptingContext, bThereWereErrors, 0), NULL },
	{ "FramesInState",												TOK_AUTOINT(BuildScriptingContext, iFramesInState, 0), NULL },
	{ "TimeEnteredState",											TOK_AUTOINT(BuildScriptingContext, iTimeEnteredState, 0), NULL },
	{ "ScriptStartTime",											TOK_AUTOINT(BuildScriptingContext, iScriptStartTime, 0), NULL },
	{ "CurDisplayString",											TOK_ESTRING | TOK_STRING(BuildScriptingContext, pCurDisplayString, 0), NULL },
	{ "CurStepString",												TOK_ESTRING | TOK_STRING(BuildScriptingContext, pCurStepString, 0), NULL },
	{ "FailureMessage",												TOK_ESTRING | TOK_STRING(BuildScriptingContext, pFailureMessage, 0), NULL },
	{ "DefaultDirectories",											TOK_STRINGARRAY(BuildScriptingContext, ppDefaultDirectories), NULL },
	{ "compileLogFileName",											TOK_FIXEDSTR(BuildScriptingContext, compileLogFileName), NULL },
	{ "MostRecentSystemCommandOutputFileName",						TOK_ESTRING | TOK_STRING(BuildScriptingContext, pMostRecentSystemCommandOutputFileName, 0), NULL },
	{ "variables",													TOK_EMBEDDEDSTRUCT(BuildScriptingContext, variables, parse_BuildScriptingVariableList)},
	{ "NumStartingVariables",										TOK_AUTOINT(BuildScriptingContext, iNumStartingVariables, 0), NULL },
	{ "Disabled",													TOK_AUTOINT(BuildScriptingContext, bDisabled, 0), NULL },
	{ "Children",													TOK_STRUCT(BuildScriptingContext, ppChildren, parse_BuildScriptingContext) },
	{ "DetachedChildren",											TOK_STRUCT(BuildScriptingContext, ppDetachedChildren, parse_BuildScriptingContext) },
	{ "Failing",													TOK_AUTOINT(BuildScriptingContext, bFailing, 0), NULL },
	{ "ChildBehaviorFlags",											TOK_AUTOINT(BuildScriptingContext, eChildBehaviorFlags, 0), BuildScriptingContextChildBehaviorFlagsEnum },
	{ "}",															TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_BuildScriptingContext()
{
	int iSize = sizeof(BuildScriptingContext);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_BuildScriptingContext, iSize, "BuildScriptingContext", NULL, "BuildScripting.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ChildBeginEndDef
#define TYPE_parse_ChildBeginEndDef ChildBeginEndDef
ParseTable parse_ChildBeginEndDef[] =
{
	{ "ChildBeginEndDef", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ChildBeginEndDef), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "BeginChildIndex",	TOK_AUTOINT(ChildBeginEndDef, iBeginChildIndex, 0), NULL },
	{ "EndChildIndex",		TOK_AUTOINT(ChildBeginEndDef, iEndChildIndex, 0), NULL },
	{ "Flags",				TOK_AUTOINT(ChildBeginEndDef, eFlags, 0), BuildScriptingContextChildBehaviorFlagsEnum },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ChildBeginEndDef()
{
	int iSize = sizeof(ChildBeginEndDef);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ChildBeginEndDef, iSize, "ChildBeginEndDef", NULL, "BuildScripting.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
