#ifndef __EARRAY_C_AST_H_
#define __EARRAY_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \earray.c
//autogeneratednocheckin

extern ParseTable parse_EarrayToStringWrapperStruct_Dummy[];
#define TYPE_parse_EarrayToStringWrapperStruct_Dummy EarrayToStringWrapperStruct_Dummy

extern ParseTable parse_EarrayToStringWrapperStruct[];
#define TYPE_parse_EarrayToStringWrapperStruct EarrayToStringWrapperStruct

#endif
