#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct EarrayToStringWrapperStruct_Dummy
#define TYPE_parse_EarrayToStringWrapperStruct_Dummy EarrayToStringWrapperStruct_Dummy
ParseTable parse_EarrayToStringWrapperStruct_Dummy[] =
{
	{ "EarrayToStringWrapperStruct_Dummy", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(EarrayToStringWrapperStruct_Dummy), 0, NULL, 0, NULL },
	{ "{",									TOK_START, 0 },
	{ "x",									TOK_AUTOINT(EarrayToStringWrapperStruct_Dummy, x, 0), NULL },
	{ "}",									TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_EarrayToStringWrapperStruct_Dummy()
{
	int iSize = sizeof(EarrayToStringWrapperStruct_Dummy);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_EarrayToStringWrapperStruct_Dummy, iSize, "EarrayToStringWrapperStruct_Dummy", NULL, "earray.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_EarrayToStringWrapperStruct_Dummy[];
#define TYPE_parse_EarrayToStringWrapperStruct_Dummy EarrayToStringWrapperStruct_Dummy
//Structparser.exe autogenerated ParseTable for struct EarrayToStringWrapperStruct
#define TYPE_parse_EarrayToStringWrapperStruct EarrayToStringWrapperStruct
ParseTable parse_EarrayToStringWrapperStruct[] =
{
	{ "EarrayToStringWrapperStruct", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(EarrayToStringWrapperStruct), 0, NULL, 0, NULL },
	{ "{",								TOK_START, 0 },
	{ "WrapperElements",				TOK_STRUCT(EarrayToStringWrapperStruct, ppWrapperElements, parse_EarrayToStringWrapperStruct_Dummy) },
	{ "}",								TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_EarrayToStringWrapperStruct()
{
	int iSize = sizeof(EarrayToStringWrapperStruct);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_EarrayToStringWrapperStruct, iSize, "EarrayToStringWrapperStruct", NULL, "earray.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
