#ifndef __ERROR_C_AST_H_
#define __ERROR_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \error.c
//autogeneratednocheckin

extern ParseTable parse_ErrorFilenameCache[];
#define TYPE_parse_ErrorFilenameCache ErrorFilenameCache

#endif
