#ifndef __EXPRESSIONFUNC_H_AST_H_
#define __EXPRESSIONFUNC_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \ExpressionFunc.h
//autogeneratednocheckin

//auto-generated staticdefine for enum ExprFuncFlags
//autogeneratednocheckin
extern StaticDefineInt ExprFuncFlagsEnum[];

extern ParseTable parse_ExprFuncDescContainer[];
#define TYPE_parse_ExprFuncDescContainer ExprFuncDescContainer

extern ParseTable parse_ExprFuncDescString[];
#define TYPE_parse_ExprFuncDescString ExprFuncDescString

extern ParseTable parse_ExprFuncArg[];
#define TYPE_parse_ExprFuncArg ExprFuncArg

extern ParseTable parse_ExprFuncDesc[];
#define TYPE_parse_ExprFuncDesc ExprFuncDesc

extern ParseTable parse_ExprFuncTable[];
#define TYPE_parse_ExprFuncTable ExprFuncTable

#endif
