#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct InstancedState
#define TYPE_parse_InstancedState InstancedState
ParseTable parse_InstancedState[] =
{
	{ "InstancedState", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(InstancedState), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "stateName",			TOK_FIXEDSTR(InstancedState, stateName), NULL },
	{ "MachinesInState",	TOK_AUTOINT(InstancedState, iMachinesInState, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_InstancedState()
{
	int iSize = sizeof(InstancedState);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_InstancedState, iSize, "InstancedState", NULL, "InstancedStateMachine.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_InstancedState[];
#define TYPE_parse_InstancedState InstancedState
//Structparser.exe autogenerated ParseTable for struct StateMachineType
#define TYPE_parse_StateMachineType StateMachineType
ParseTable parse_StateMachineType[] =
{
	{ "StateMachineType", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(StateMachineType), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "stateMachineName",	TOK_KEY | TOK_FIXEDSTR(StateMachineType, stateMachineName), NULL },
	{ "AllStateList",		TOK_STRUCT(StateMachineType, ppAllStateList, parse_InstancedState) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_StateMachineType()
{
	int iSize = sizeof(StateMachineType);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_StateMachineType, iSize, "StateMachineType", NULL, "InstancedStateMachine.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
