#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct SmtpBgEmailResult
#define TYPE_parse_SmtpBgEmailResult SmtpBgEmailResult
ParseTable parse_SmtpBgEmailResult[] =
{
	{ "SmtpBgEmailResult", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(SmtpBgEmailResult), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "ErrorString",		TOK_STRING(SmtpBgEmailResult, pErrorString, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_SmtpBgEmailResult()
{
	int iSize = sizeof(SmtpBgEmailResult);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_SmtpBgEmailResult, iSize, "SmtpBgEmailResult", NULL, "netsmtp.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
