#ifndef __TEXTPARSERHTML_C_AST_H_
#define __TEXTPARSERHTML_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \textparserHTML.c
//autogeneratednocheckin

extern ParseTable parse_FormState[];
#define TYPE_parse_FormState FormState

#endif
