#ifndef __TICKETNET_H_AST_H_
#define __TICKETNET_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \ticketnet.h
//autogeneratednocheckin

extern ParseTable parse_ImageData[];
#define TYPE_parse_ImageData ImageData

extern ParseTable parse_TicketData[];
#define TYPE_parse_TicketData TicketData

extern ParseTable parse_TicketRequestData[];
#define TYPE_parse_TicketRequestData TicketRequestData

extern ParseTable parse_TicketRequestResponse[];
#define TYPE_parse_TicketRequestResponse TicketRequestResponse

extern ParseTable parse_TicketRequestResponseList[];
#define TYPE_parse_TicketRequestResponseList TicketRequestResponseList

extern ParseTable parse_TicketRequestResponseWrapper[];
#define TYPE_parse_TicketRequestResponseWrapper TicketRequestResponseWrapper

#endif
