#ifndef GLOBALCOMM_H_
#define GLOBALCOMM_H_

#include "net/net.h"
#include "CrypticPorts.h"

// Random defines that will be used in various places

#define MAX_NAME_LEN 128



#define LIB_MSG_BIT (1<<16) // Must be larger than any command enum. If this is set, this is a library command
#define LIB_MSG_START (LIB_MSG_BIT+1) //where to start the library commands

#define GAME_MSG_SENDBITS 1 //number of bits to use when sending game commands

//FIXME this should be long while the client is still in the middle of its handshaking process, short afterwards=
#define CLIENT_LINK_TIMEOUT 300 // number of seconds before a client is disconnected due to lagging out
#define CLIENT_LINK_DEV_TIMEOUT 4800

//shared commands used to start at zero, and then a bunch of other command enums used DEPRECATED_SHAREDCMD_MAX to define
//the start of their own enums. Now the shared commands start at 240, but this #define is used to keep the old lists
//from having their values change.
#define DEPRECATED_SHAREDCMD_MAX 10

//command IDs are 8 bits. 240 thorugh 255 are for internal packet commands like PING, found in netPrivate.h. 220 through 240 are
//for SharedCmds, which are things that live above the net code but below normal code, such as multiplexing
#define FIRST_SHARED_CMD_ID 220

//shared commands between servers... all other servers' commands should start AFTER this
AUTO_ENUM;
typedef enum SharedCmdIDs
{
	SHAREDCMD_MULTIPLEX = FIRST_SHARED_CMD_ID, //this command is being sent through a "command multiplexer", which ships commands around
										//to multiple different places. For instance, a launcher ships commands between the log server,
										//the transaction server, and many map servers. Each multiplex commands contains to- and from-
										//internal link numbers, plus the actual message type, plus the actual message.




	SHAREDCMD_MULTIPLEX_REQUESTS_LINK, //this message is sent by a multiplex server to another server, requesting a link with a
										//specific ID. That server needs to be monitoring for this message, and, if it receives it, call
										//CreateRequestedMultiplexingManager

	SHAREDCMD_FILESENDINGMODE,

	SHAREDCMD_UNUSED_223,
	SHAREDCMD_UNUSED_224,
	SHAREDCMD_UNUSED_225,
	SHAREDCMD_UNUSED_226,
	SHAREDCMD_UNUSED_227,
	SHAREDCMD_UNUSED_228,
	SHAREDCMD_UNUSED_229,
	SHAREDCMD_UNUSED_230,
	SHAREDCMD_UNUSED_231,	
	SHAREDCMD_UNUSED_232,
	SHAREDCMD_UNUSED_233,
	SHAREDCMD_UNUSED_234,
	SHAREDCMD_UNUSED_235,	
	SHAREDCMD_UNUSED_236,
	SHAREDCMD_UNUSED_237,
	SHAREDCMD_UNUSED_238,
	SHAREDCMD_UNUSED_239,

	SHAREDCMD_MAX, //this can not be used, and must equal FIRST_INTERNAL_PACKET_CMD 
} SharedCmdIDs;




// These are the lowest level functions, the ones that don't correspond to a particular entity
AUTO_ENUM;
typedef enum ClientToServerMsg
{
	TOSERVER_GAME_MSG = DEPRECATED_SHAREDCMD_MAX, //Indicates game messages are following
	TOSERVER_GAME_LOGIN,
	TOSERVER_REQ_UPDATE,
	TOSERVER_LOCKED_UPDATE,
	TOSERVER_EDIT_MSG,
	TOSERVER_DONE_LOADING,
	TOSERVER_MOVEMENT_CLIENT,
	TOSERVER_START_GAME_SPECIFIC,
	TOSERVER_READY_FOR_GENERAL_UPDATES,
	TOSERVER_CLIENT_PATCHING_WORLD,	// indicates that the client is doing micropatching (worldZoneMapPatching)
} ClientToServerMsg;

enum
{
	TOCLIENT_GAME_MSG = COMM_MAX_CMD, //Indicates one or more game messages are coming
	TOCLIENT_WORLD_UPDATE,
	TOCLIENT_WORLD_PERIODIC_UPDATE,

	TOCLIENT_WORLD_REPLY,

	//the "once-per-frame" update... contains entity update and ref system update
	TOCLIENT_GENERAL_UPDATE,

	TOCLIENT_GAME_CONNECT_SUCCESS,
	TOCLIENT_GAME_CONNECT_FAILURE,
	TOCLIENT_GAME_LOGOUT,
	TOCLIENT_GAME_SERVER_ADDRESS,
	TOCLIENT_GAME_START_TRANSFER,
	TOCLIENT_GAME_TRANSFER_FAILED,

	TOCLIENT_DEBUG_BEACONSTUFF,

	TOCLIENT_MOVEMENT_CLIENT,

	TOCLIENT_LOGIN_SAFE_PERIOD_PASSED,

	TOCLIENT_ENTITY_DEBUG,

	LOGINSERVER_TO_CLIENT_LOGIN_FAILED,
	LOGINSERVER_TO_CLIENT_POSSIBLE_GAMESERVERS,
	LOGINSERVER_TO_CLIENT_POSSIBLE_CHARACTERS,
	LOGINSERVER_TO_CLIENT_CHARACTER_CREATION_DATA,
	LOGINSERVER_TO_CLIENT_SEND_REFDICT_DATA_UPDATES,
	LOGINSERVER_TO_CLIENT_RELOAD_CHARACTER_CHOICES,
	LOGINSERVER_TO_CLIENT_INVALID_DISPLAYNAME,
	LOGINSERVER_TO_CLIENT_DISPLAYNAME_RESPONSE,
	LOGINSERVER_TO_CLIENT_LOGIN_INFO,
	LOGINSERVER_TO_CLIENT_HEARTBEAT,
	LOGINSERVER_TO_CLIENT_NEWLY_CREATED_CHARACTER_ID,
	LOGINSERVER_TO_CLIENT_NOTIFYSEND,
	LOGINSERVER_TO_CLIENT_RANDOM_NAMES,
	LOGINSERVER_TO_CLIENT_FULL_CHARACTER_CHOICE,
	LOGINSERVER_TO_CLIENT_POSSIBLE_UGC_PROJECTS,
	LOGINSERVER_TO_CLIENT_UGC_IMPORT_PROJECT_SEARCH,
	LOGINSERVER_TO_CLIENT_SELECT_PLAYERTYPE,
	LOGINSERVER_TO_CLIENT_CSTORE_UPDATE,

	TO_CLIENT_DEBUG_MESSAGE,

	LOGINSERVER_TO_CLIENT_HERE_IS_EDIT_PERMISSION_COOKIE,
	LOGINSERVER_TO_CLIENT_HERE_IS_NUM_AHEAD_OF_YOU_IN_EDIT_QUEUE,

	TOCLIENT_MICROTRANSACTION_CATEGORY,
	LOGINSERVER_TO_CLIENT_MICROTRANSACTION_CATEGORY,
	LOGINSERVER_TO_CLIENT_JOIN_SESSION_SUCCEEDED,
	LOGINSERVER_TO_CLIENT_JOIN_SESSION_FAILED,

	LOGINSERVER_TO_CLIENT_UGC_REQUEST_MORE_REVIEWS,
	LOGINSERVER_TO_CLIENT_CREATE_SESSION_FAILED,
	LOGINSERVER_TO_CLIENT_CREATE_SESSION_SUCCEEDED,
	LOGINSERVER_TO_CLIENT_GAME_SESSION_INFO,
	LOGINSERVER_TO_CLIENT_GAME_PROGRESSION_NODE_LIST, // Obsolete
	LOGINSERVER_TO_CLIENT_CHATAUTHDATA,
	LOGINSERVER_TO_CLIENT_LOBBY_SWITCH_CHARACTERS_RESULT,
	LOGINSERVER_TO_CLIENT_SAVE_SESSION_FAILED,
	LOGINSERVER_TO_CLIENT_SAVE_SESSION_SUCCEEDED,
	LOGINSERVER_TO_CLIENT_GAME_SESSION_INFO_SAME_OR_DOES_NOT_EXIST,
	LOGINSERVER_TO_CLIENT_LIST_OF_OPEN_GAME_SESSIONS_NO_CHANGES, // Obsolete

	LOGINSERVER_TO_CLIENT_UGC_SEARCH_RESULTS,
	LOGINSERVER_TO_CLIENT_UGC_PROJECT_REQUEST_BY_ID_RESULTS,
	LOGINSERVER_TO_CLIENT_UGCPROJECTSERIES_CREATE_RESULT,
	LOGINSERVER_TO_CLIENT_UGCPROJECTSERIES_UPDATE_RESULT,
	LOGINSERVER_TO_CLIENT_HAS_GAD,
	LOGINSERVER_TO_CLIENT_JOIN_SESSION_REQUESTSENT,
	LOGINSERVER_TO_CLIENT_LIST_OF_GAME_SESSIONS_BY_GROUP,
	LOGINSERVER_TO_CLIENT_ENTERED_LOBBY,
	LOGINSERVER_TO_CLIENT_EXITED_LOBBY,

	LOGINSERVER_TO_CLIENT_LOADING_SCREENS,			// dynamic loading screens

	LOGINSERVER_TO_CLIENT_GAME_ACCOUNT_NUMERIC_PURCHASE_RESULT,
	LOGINSERVER_TO_CLIENT_GAME_SESSION_COUNT_BY_GROUP,
	LOGINSERVER_TO_CLIENT_GAME_CONTENT_NODE_REWARDS,

	LOGINSERVER_TO_CLIENT_REQUIRE_ONETIMECODE,
	LOGINSERVER_TO_CLIENT_SAVENEXTMACHINE,

	LOGINSERVER_TO_CLIENT_POSSIBLE_CHARACTERS_JSON,
	LOGINSERVER_TO_CLIENT_CHARACTER_CHOICE_VALID,
	LOGINSERVER_TO_CLIENT_NOTIFYSEND_STRUCT,
    LOGINSERVER_TO_CLIENT_GAMEPERMISSIONDEFS,

    LOGIN2_TO_CLIENT_CHARACTER_SELECTION_DATA,
    LOGIN2_TO_CLIENT_LOGIN_FAILED,
    LOGIN2_TO_CLIENT_CHARACTER_DETAIL,
    LOGIN2_TO_CLIENT_REDIRECT,
    LOGIN2_TO_CLIENT_REDIRECT_DONE,
    LOGIN2_TO_CLIENT_CLUSTER_STATUS,
	LOGIN2_TO_CLIENT_SUPPORTED_LANGUAGES,
};

// Make sure this doesn't change for backwards compat for the version mismatch packet.
STATIC_ASSERT(LOGINSERVER_TO_CLIENT_LOGIN_FAILED == 15);

// Gateway depends on the following packets not changing their values.
// If you must change these values, you'll need to modify /Gateway/cryptic_modules/proxy/LSConnection.jspp
//   with the new values.
// If removing a packet, an easier choice would be to leave in a dummy value
//   such as UNUSED_PACKET_NUMBER_XX where you pulled one out.
// If adding a packet, an easier choice would be to use any available
//   UNUSED_PACKET_NUMBERs or adding to the end.
STATIC_ASSERT(LOGINSERVER_TO_CLIENT_LOGIN_FAILED == 15);
STATIC_ASSERT(LOGINSERVER_TO_CLIENT_POSSIBLE_CHARACTERS == 17);
STATIC_ASSERT(LOGINSERVER_TO_CLIENT_SELECT_PLAYERTYPE == 31);
STATIC_ASSERT(LOGINSERVER_TO_CLIENT_REQUIRE_ONETIMECODE == 64);
STATIC_ASSERT(LOGINSERVER_TO_CLIENT_POSSIBLE_CHARACTERS_JSON == 66);
STATIC_ASSERT(LOGIN2_TO_CLIENT_CHARACTER_SELECTION_DATA == 70);
STATIC_ASSERT(LOGIN2_TO_CLIENT_LOGIN_FAILED == 71);



enum { // only add to the end, we need to maintain compatibility with different versions of patchclients
	TOVERSION_REQ = COMM_MAX_CMD,
};

enum { // only add to the end, we need to maintain compatibility with different versions of patchclients
	FROMVERSION_VERSION = COMM_MAX_CMD,

	// patchclient compatibility with some old loginservers.
	// feel free to add before and after, but keep the values the same.
	// we can probably get rid of these in a few months. -GG 10-02-07
	VERSION_TO_CLIENT = COMM_MAX_CMD+14, 
	VERSION_TO_CLIENT2 = COMM_MAX_CMD+15, // patchclient compatibility with some old loginservers. feel free to add after, but keep it ==15
};

AUTO_ENUM;
typedef enum ToLoginMsg
{
	TOLOGIN_CHOOSE_ACCOUNT = COMM_MAX_CMD,

	TOLOGIN_SET_TERMS_OF_USE,
	TOLOGIN_SET_PLAYER_TYPE,
	TOLOGIN_GET_POSSIBLE_CHARACTERS,
	TOLOGIN_GET_CHARACTER_CREATION_DATA,
	TOLOGIN_DELETE_CHARACTER,
	TOLOGIN_CHOOSE_CHARACTER,
	TOLOGIN_CONVERT_CHARACTER_PLAYERTYPE,
	TOLOGIN_GO_TO_CHARACTER_SELECT,
	TOLOGIN_REQUEST_GAMESERVER_CHOICES,	
	TOLOGIN_SEND_REFDICT_DATA_REQUESTS,
	TOLOGIN_CHOOSE_DESTINATION,
	TOLOGIN_TODB_IMPORT_CONTAINER,
	TOLOGIN_DOMINATE_SOULS,
	TOLOGIN_CHANGE_DISPLAYNAME,
	TOLOGIN_CHANGE_CHARACTER_NAME,
	TOLOGIN_REQUEST_RANDOM_NAMES,

	TOLOGIN_REQUEST_FULL_CHARACTER_CHOICE,

	TOLOGIN_REQUEST_POSSIBLE_UGC_CHOICES,
	UNUSED_PACKET_NUMBER_19,				// Feel free to use this slot.

	TOLOGIN_CHOOSE_UGC_PROJECT,
	TOLOGIN_ACCEPTED_UGC_PROJECT_CREATE_EULA,

	TOLOGIN_UNDELETE_CHARACTER,

	TOLOGIN_DELETE_UGC_PROJECT,

	TOLOGIN_CSTORE_ACTION,

	TOLOGIN_READY_TO_CHOOSE_UGC_PROJECT,

	// Used to ask the login server for the list of open game sessions
	TOLOGIN_UPDATE_CLIENT_LOBBY_INFO,

	// Used to ask the login server to join a game session
	TOLOGIN_REQUEST_JOIN_GAME_SESSION,

	// Used during a Steam Wallet auth/capture cycle
	TOLOGIN_STEAM_MICROTXN_AUTHZ_RESPONSE,

	TOLOGIN_UGC_REQUEST_MORE_REVIEWS,

	// Used to ask the login server to create/update a game session
	TOLOGIN_REQUEST_SAVE_GAME_SESSION,

	// Used to ask the login server for the game session information
	TOLOGIN_REQUEST_GAME_SESSION_INFO,

	// Tell login server that player wants to leave the lobby team
	TOLOGIN_REQUEST_LEAVE_GAME_SESSION,

	// Used to set the lobby ready flag
	TOLOGIN_SET_LOBBY_READY_FLAG,

	// Sets the game session ready for transfer so everyone can transfer to the game from the lobby
	TOLOGIN_SET_GAME_SESSION_READY_FOR_TRANSFER,

	// Tell the login server that player wants to quit their team
	TOLOGIN_REQUEST_LEAVE_CURRENT_TEAM,

	// Tell the login server that player wants to kick someone out of the game session
	TOLOGIN_REQUEST_KICK_PLAYER_FROM_SESSION,

	// Client asks the login server for the game server information for the game session
	TOLOGIN_REQUEST_GAME_SERVER_INFO_FOR_GAME_SESSION,

	// Client asks the login server for the list of game progression nodes
	TOLOGIN_REQUEST_GAME_PROGRESSION_NODE_LIST, // Obsolete

	// Sets the destination of the game session
	TOLOGIN_REQUEST_SET_SESSION_DESTINATION,

	// Client asks login server to retrieve ChatRelay data
	TOLOGIN_REQUEST_CHATRELAY,

	// Client requests the login server to update the character choice for the lobby
	TOLOGIN_UPDATE_LOBBY_CHARACTER_CHOICE,

	// Client asks the login server to send the PlayerInfo to the ChatServer
	TOLOGIN_UPDATE_CHAT_PLAYERINFO,

	// Client requests to create a UGCProjectSeries
	TOLOGIN_UGCPROJECTSERIES_CREATE,

	// Client requests to destroy a UGCProjectSeries
	TOLOGIN_UGCPROJECTSERIES_DESTROY,

	// Client requests to update a series
	TOLOGIN_UGCPROJECTSERIES_UPDATE,

	// Packets that mirror the ServerCmds in gslUGC_cmd.c
	TOLOGIN_UGC_SEACRH,
	TOLOGIN_UGC_SET_PLAYER_IS_REVIEWER,
	TOLOGIN_UGC_SET_SEARCH_EULA_ACCEPTED,
	TOLOGIN_UGC_PROJECT_REQUEST_BY_ID,

	// Client asks the login server to update their public login status
	TOLOGIN_CHANGE_LOGINSTATUS,

	// Client wants to invite another player to a team
	TOLOGIN_INVITE_FROM_LOBBY,

	// Client accepts an invite in the lobby
	TOLOGIN_ACCEPT_INVITE_IN_LOBBY,

	// Client declines an invite in the lobby
	TOLOGIN_DECLINE_INVITE_IN_LOBBY,

	// Client accepts a join request in the lobby
	TOLOGIN_ACCEPT_REQUEST_IN_LOBBY,

	// Client declines a join request in the lobby
	TOLOGIN_DECLINE_REQUEST_IN_LOBBY,

	// Client cancels a join request in the lobby
	TOLOGIN_CANCEL_REQUEST_IN_LOBBY,

	// Clients asks for the list of sessions in a specific group in the lobby
	TOLOGIN_REQUEST_GAME_SESSIONS_BY_GROUP,

	// Tell the login server that the player left the lobby
	TOLOGIN_PLAYER_LEFT_LOBBY,

	// Client asks the login server for the game server information in solo play mode
	TOLOGIN_REQUEST_GAME_SERVER_INFO_FROM_SOLO_PLAY,

	// Client wants to make a game account purchase using a numeric
	TOLOGIN_GAME_ACCOUNT_MAKE_NUMERIC_PURCHASE,

	// Client asks for the number of sessions in a specific group in the lobby
	TOLOGIN_REQUEST_GAME_SESSION_COUNT_BY_GROUP,

	// Client asks for the rewards for a game content node
	TOLOGIN_REQUEST_GAME_CONTENT_NODE_REWARDS,

	// Client asks the login server to complete pplayerchoicesrogression nodes. Only for access level 9.
	TOLOGIN_PROGRESSION_COMPLETE_THROUGH_NODE,

	// Client asks the login server to un-complete progression nodes. Only for access level 9.
	TOLOGIN_PROGRESSION_UNCOMPLETE_THROUGH_NODE,

	// Client sends a one-time code (and optionally machine name) for authentication
	TOLOGIN_ONETIMECODE,
	// Client sends a machine name (empty string = do not save)
	TOLOGIN_SAVENEXTMACHINE,

	// Get the character list as a JSON block. Sent in addition to (and after) TOLOGIN_GET_POSSIBLE_CHARACTERS
	TOLOGIN_GET_POSSIBLE_CHARACTERS_JSON,

	// A simplified character choice packet (for existing characters only) that only sends a couple ids.
	TOLOGIN_CHOOSE_CHARACTER_BY_CONTAINER_ID,

	//I'm a GatewayProxy pretending to be a game client, I'm now specifying the container ID of the GatewayServer
	//I want to connect to.
	TOLOGIN_HERE_IS_REQUESTED_GATEWAYSERVER_ID,

	// I'm a proxy pretending to be a game client, here is the real IP address of the client.
	TOLOGIN_SET_REQUEST_IP,

    //
    // Begin Login2 packets
    //
    TOLOGIN_LOGIN2_BEGIN_LOGIN,
    TOLOGIN_LOGIN2_REDIRECT,
    TOLOGIN_LOGIN2_SAVENEXTMACHINE,
    TOLOGIN_LOGIN2_ONETIMECODE,
    TOLOGIN_LOGIN2_REQUESTCHARACTERDETAIL,
    TOLOGIN_LOGIN2_CHOOSECHARACTER,
    TOLOGIN_LOGIN2_REQUESTMAPSEARCH,
    TOLOGIN_LOGIN2_REQUESTGAMESERVERADDRESS,
    TOLOGIN_LOGIN2_DELETE_CHARACTER,
    TOLOGIN_LOGIN2_RENAME_CHARACTER,
	TOLOGIN_LOGIN2_GAD_PURCHASE,
    TOLOGIN_LOGIN2_CREATECHARACTER,
    TOLOGIN_LOGIN2_SEND_REFDICT_DATA_REQUESTS,
    TOLOGIN_LOGIN2_GET_CHARACTER_CREATION_DATA,
} ToLoginMsg;

// Gateway depends on the following packets not changing their values.
// If you must change these values, you'll need to modify /Gateway/cryptic_modules/proxy/LSConnection.jspp
//   with the new values.
// If removing a packet, an easier choice would be to leave in a dummy value
//   such as UNUSED_PACKET_NUMBER_XX where you pulled one out.
// If adding a packet, an easier choice would be to use any available
//   UNUSED_PACKET_NUMBERs or adding to the end.
STATIC_ASSERT(TOLOGIN_SET_PLAYER_TYPE == 2)
STATIC_ASSERT(TOLOGIN_GET_POSSIBLE_CHARACTERS == 3)
STATIC_ASSERT(TOLOGIN_ONETIMECODE == 65)
STATIC_ASSERT(TOLOGIN_GET_POSSIBLE_CHARACTERS_JSON == 67)
STATIC_ASSERT(TOLOGIN_CHOOSE_CHARACTER_BY_CONTAINER_ID == 68)
STATIC_ASSERT(TOLOGIN_SET_REQUEST_IP == 70)
STATIC_ASSERT(TOLOGIN_LOGIN2_BEGIN_LOGIN == 71)
STATIC_ASSERT(TOLOGIN_LOGIN2_ONETIMECODE == 74)


// These are the library-handled game messages, the ones that are handled by the libs, but deal with an ent

enum
{
	GAMECLIENTLIB_CMD_PUBLIC = LIB_MSG_START,
	GAMECLIENTLIB_CMD_PRIVATE,
	GAMECLIENTLIB_SEND_PHYSICS,
	GAMECLIENTLIB_SEND_REFDICT_DATA_REQUESTS,
	GAMECLIENTLIB_SEND_TESTCLIENT_COMMAND_REQUESTS,
	GAMECLIENTLIB_SEND_SCREENSHOT,
};

enum
{
	GAMESERVERLIB_CMD_PUBLIC = LIB_MSG_START,
	GAMESERVERLIB_CMD_PRIVATE,
	GAMESERVERLIB_CON_PRINTF, 
	GAMESERVERLIB_CHATCMD_UNKNOWN,
};

enum
{
	CHATRELAY_CMD_PUBLIC = GAMESERVERLIB_CMD_PUBLIC,
	CHATRELAY_CMD_PRIVATE = GAMESERVERLIB_CMD_PRIVATE,
	CHATRELAY_AUTHENTICATE,
	CHATRELAY_FAKE_AUTHENTICATE,
};


enum
{
	TO_LAUNCHER_ERROR = DEPRECATED_SHAREDCMD_MAX,
	TO_LAUNCHER_SETCONTROLLERSCRIPTINGRESULT,
	TO_LAUNCHER_REPORTCLIENTSTATE,
	TO_LAUNCHER_I_AM_XBOX_CLIENT,

//sent by cryptic error - now 
	TO_LAUNCHER_PROCESS_CRASHED_OR_ASSERTED__DEPRECATED,
	TO_LAUNCHER_PROCESS_BEGAN_CRASH_OR_ASSERT,
	TO_LAUNCHER_PROCESS_COMPLETED_CRASH_OR_ASSERT,
	TO_LAUNCHER_PROCESS_REPORTING_FPS,

	TO_LAUNCHER_CONTROLLERSCRIPTINGPAUSE,

	//hey, launcher, I launched a totally owned child process. If you ever kill me,
	//kill this bad boy as well
	TO_LAUNCHER_PROCESS_REPORTING_CHILD_PROCESS,

	TO_LAUNCHER_CLIENT_REQUESTS_OPEN_MONITORING_URL,

	TO_LAUNCHER_MAX,
};

enum
{
	FROM_LAUNCHERDEBUG_COMMAND = DEPRECATED_SHAREDCMD_MAX,

	FROM_LAUNCHERDEBUG_MAX,
};

enum
{
	TO_CONTINUOUSBUILDER_SUBSTATE = DEPRECATED_SHAREDCMD_MAX,
	TO_CONTINUOUSBUILDER_SUBSUBSTATE,
	TO_CONTINUOUSBUILDER_COMMENT,

	TO_CONTINUOUSBUILDER_STOP_ERRORTRACKING,
	TO_CONTINUOUSBUILDER_START_ERRORTRACKING,

	TO_CONTINUOUSBUILDER_PAUSE_TIMEOUT,

	TO_CONTINUOUSBUILDER_MAX,
};

enum
{
	TO_ERRORTRACKER_ERROR = DEPRECATED_SHAREDCMD_MAX,

	TO_ERRORTRACKER_DUMP_START,
	TO_ERRORTRACKER_DUMP_CONTINUE,
	TO_ERRORTRACKER_DUMP_FINISH,
	TO_ERRORTRACKER_SYMSRV_DONE, 
	TO_ERRORTRACKER_SYMSRV_STATUS_UPDATE,
	TO_ERRORTRACKER_MEMORY_DUMP,
	TO_ERRORTRACKER_DUMP_DESCRIPTION_ONLY,
	TO_ERRORTRACKER_DUMP_CANCELLED,
	TO_ERRORTRACKER_MEMORY_DUMP_START,
	TO_ERRORTRACKER_MEMORY_DUMP_CONTINUE,
	TO_ERRORTRACKER_MEMORY_DUMP_END,
	TO_ERRORTRACKER_DUMP_DESCRIPTION_UPDATE,
	TO_ERRORTRACKER_GENERICFILE_START,
	TO_ERRORTRACKER_GENERICFILE_CONTINUE,
	TO_ERRORTRACKER_GENERICFILE_END,
	TO_ERRORTRACKER_SYMSRV_MEM_OVERLIMIT,
	TO_ERRORTRACKER_SYMSRV_MODULE_FAILURE,
	TO_ERRORTRACKER_NEWSLAVE,
	TO_ERRORTRACKER_SWITCH_CONTEXT,

	TO_ERRORTRACKER_MAX,
};

enum
{
	TO_TICKETTRACKER_ERROR = 16, 
	TO_TICKETTRACKER_REQUEST_STATUS,
	TO_TICKETTRACKER_REQUEST_LABEL,
	TO_TICKETTRACKER_TICKET_EDIT,
	TO_TICKETTRACKER_TICKET_CLOSE,

	TO_TICKETTRACKER_MAX,
};


enum
{
	FROM_ERRORTRACKER_DUMPFLAGS = DEPRECATED_SHAREDCMD_MAX,
	FROM_ERRORTRACKER_CANCEL_DUMP,
	FROM_ERRORTRACKER_ERRRESPONSE,
	FROM_ERRORTRACKER_SYMLOOKUP,
	FROM_ERRORTRACKER_STATUS_UPDATE,
	FROM_ERRORTRACKER_RECEIVED, // generic receipt notice

	FROM_ERRORTRACKER_MAX,
};

enum
{
	FROM_TICKETTRACKER_ERRFLAGS = 15,
	FROM_TICKETTRACKER_STATUS,

	FROM_TICKETTRACER_MAX,
};

enum
{
	STATE_ERRORTRACKER_NONE = 0,
	STATE_ERRORTRACKER_RECEIVED,
	STATE_ERRORTRACKER_PARSEENTRY,
	STATE_ERRORTRACKER_STACKWALK,
	STATE_ERRORTRACKER_MERGE,
	STATE_ERRORTRACKER_IMAGECOPY,
	STATE_ERRORTRACKER_DONE,
};

enum
{
	TO_GAMESERVER_SCREENSHOT = DEPRECATED_SHAREDCMD_MAX,
};

enum
{
	FROM_MCP_TO_NEWCONTROLLERTRACKER_REQUEST_SHARD_LIST = DEPRECATED_SHAREDCMD_MAX,
	FROM_MCP_TO_NEWCONTROLLERTRACKER_REQUEST_LAST_MINUTE_FILES,

	//involves no security at all
	FROM_MCP_TO_NEWCONTROLLERTRACKER_REQUEST_XBOX_SHARD_LIST,
};

enum
{
	FROM_NEWCONTROLLERTRACKER_TO_MCP_HERE_IS_SHARD_LIST = DEPRECATED_SHAREDCMD_MAX,
	FROM_NEWCONTROLLERTRACKER_TO_MCP_HERE_ARE_LAST_MINUTE_FILES,
};

enum
{
	FROM_NEWCONTROLLERTRACKER_TO_SHARD_GLOBALCHAT_ONLINE = DEPRECATED_SHAREDCMD_MAX,
};

enum
{
	FROM_CRITICALSYSTEM_TO_CONTROLLERTRACKER_HERE_IS_GENERIC_STATUS = DEPRECATED_SHAREDCMD_MAX,
	FROM_CRITICALSYSTEM_TO_CONTROLLERTRACKER_HERE_IS_ALERT,
	FROM_ERRORTRACKER_TO_CONTROLLERTRACKER_CRASH_REPORT,
	FROM_CRITICALSYSTEM_TO_CONTROLLERTRACKER_HERE_IS_LOG,

	FROM_CRITICALSYSTEM_TO_CONTROLLERTRACKER_HERE_IS_COMMAND_RESULT,
};

enum
{
	FROM_CONTROLLERTRACKER_TO_CRITICALSYSTEM_HERE_IS_ALERT_FROM_SOMEONE_ELSE_ABOUT_YOU = DEPRECATED_SHAREDCMD_MAX,

	//calls the StatusReporting_ShutdownSafely() latelinked function, so only does something for
	//systems that specifically want to be shut-down-able in this fashion
	FROM_CONTROLLERTRACKER_TO_CRITICALSYSTEM_SAFE_SHUTDOWN,

	//will only do something if gbAllowCommandsOverStatusReportingLinks is true, executes the command,
	//gets the result, returns it with FROM_CRITICALSYSTEM_TO_CONTROLLERTRACKER_HERE_IS_COMMAND_RESULT
	FROM_CONTROLLERTRACKER_TO_CRITICALSYSTEM_COMMAND,
};

//moved accountserver stuff here from serverlib because it is used by StandaloneMCP
// NOTE - only add new items at the end.  Do not delete or add items in the middle,
//  or you will break compatibility with deployed account server!
AUTO_ENUM;
typedef enum
{
	TO_ACCOUNTSERVER_LOGIN = DEPRECATED_SHAREDCMD_MAX,
	TO_ACCOUNTSERVER_CHANGEPASSWORD,			// Deprecated
	TO_ACCOUNTSERVER_CREATEACCOUNT,				// Deprecated
	TO_ACCOUNTSERVER_DELETEACCOUNT,				// Deprecated
	TO_ACCOUNTSERVER_GENERATEKEYS,				// Deprecated
	TO_ACCOUNTSERVER_GETUNUSEDKEY,				// Deprecated
	TO_ACCOUNTSERVER_ACTIVATEKEY,				// Deprecated
	TO_ACCOUNTSERVER_CREATEKEYGROUP,			// Deprecated
	TO_ACCOUNTSERVER_LOGIN_CONFIRM,
	TO_ACCOUNTSERVER_GIVEPERMISSIONS,
	TO_ACCOUNTSERVER_REQUEST_LOGINSALT,

	TO_ACCOUNTSERVER_CHANGEPERSONALINFO,		// Deprecated

	TO_ACCOUNTSERVER_PLAYERPLAYTIMEUPDATE,		// Deprecated

	TO_ACCOUNTSERVER_LOGIN_NEW,					// Deprecated
	TO_ACCOUNTSERVER_LOGINVALIDATE,

	// Product Key Generation commands
	TO_ACCOUNTSERVER_GET_PRODUCTLIST,			// Deprecated
	TO_ACCOUNTSERVER_GET_PKGROUPS,
	TO_ACCOUNTSERVER_CREATE_KEYBATCH,
	TO_ACCOUNTSERVER_ADDKEYS,

	// For setting per-product flags (eg. bans)
	TO_ACCOUNTSERVER_SETPRODUCTFLAG,			// Deprecated

	// For Chat Server-related commands
	TO_ACCOUNTSERVER_DISPLAYNAME_REQUEST,
	TO_ACCOUNTSERVER_UNKNOWN_ACCOUNT,
	TO_ACCOUNTSERVER_CHATSERVER_CONNECT,

	// Clearing product flags
	TO_ACCOUNTSERVER_CLEARPRODUCTFLAG,			// Deprecated

	// Log system specs
	TO_ACCOUNTSERVER_LOGSPECS,

	// Display-name change requests from trusted sources
	TO_ACCOUNTSERVER_DISPLAYNAME_CHANGE,

	// XBOX Specific Login Message
	TO_ACCOUNTSERVER_LOGIN_XBOX,

	// XBOX Account Creation Message
	TO_ACCOUNTSERVER_CREATE_ACCOUNT_XBOX,

	// Request Account Server version
	TO_ACCOUNTSERVER_VERSION,

	// Login with MachineID
	TO_ACCOUNTSERVER_LOGIN_MACHINEID,

	// Request to generate a one-time code for a specified account and ticket ID
	TO_ACCOUNTSERVER_GENERATE_ONETIMECODE,
	// Send the One-Time Code validation
	TO_ACCOUNTSERVER_ONETIMECODE,
	// Send just the machine-name
	TO_ACCOUNTSERVER_SAVENEXTMACHINE,

	// anything with NVPSTRUCT in it means that it basically consists of a struct being sent
	// via ParserSendStructAsCheckedNameValuePairs, which ensure safe forward/backwards compatibility

	// I got your salt, here is the login information ready to be credentialed
	TO_ACCOUNTSERVER_NVPSTRUCT_LOGIN,

	// Here is the salt the trusted server wants the account server to use for the upcoming login
	TO_ACCOUNTSERVER_TRUSTED_SET_SALT,
	// The IP address for the actual requester (used by login proxies)
	TO_ACCOUNTSERVER_TRUSTED_SET_REQUEST_IP,

	TO_ACCOUNTSERVER_MAX
} AccountServerCmd;

// NOTE - only add new items at the end.  Do not delete or add items in the middle,
//  or you will break compatibility with deployed account server!
enum
{
	FROM_ACCOUNTSERVER_LOGIN = DEPRECATED_SHAREDCMD_MAX,			// No longer implemented: RSA-encrypted login ticket
	FROM_ACCOUNTSERVER_FAILED,							// DEPRECATED for login packet responses, use FROM_ACCOUNTSERVER_LOGIN_FAILED or TO_ACCOUNTSERVER_LOGINVALIDATE instead
	FROM_ACCOUNTSERVER_CREATED,
	FROM_ACCOUNTSERVER_MODIFIED,
	FROM_ACCOUNTSERVER_DELETED,
	FROM_ACCOUNTSERVER_CREATEDKEYS,
	FROM_ACCOUNTSERVER_UNUSEDKEY,
	FROM_ACCOUNTSERVER_KEYACTIVATED,
	FROM_ACCOUNTSERVER_KEYGROUPCREATED,
	FROM_ACCOUNTSERVER_ACCOUNTINFO,
	FROM_ACCOUNTSERVER_LOGINSALT,
	FROM_ACCOUNTSERVER_LOGIN_NEW,						// this is for the ticket ID
	FROM_ACCOUNTSERVER_LOGINVALIDATION,
	FROM_ACCOUNTSERVER_PKGROUPS,						// Product Key Generation response
	FROM_ACCOUNTSERVER_PKBATCHCREATED,					// Product Key Generation response
	FROM_ACCOUNTSERVER_PKCREATED,						// Product Key Generation response
	FROM_ACCOUNTSERVER_PRODUCTLIST,						// Deprecated
	FROM_ACCOUNTSERVER_BAN_RESPONSE,					// Account Banning
	FROM_ACCOUNTSERVER_INVALID_NAME,					// Display Name changes
	FROM_ACCOUNTSERVER_LOGIN_XBOX,						// No longer implemented: XUID Login Success Response
	FROM_ACCOUNTSERVER_LOGIN_FAILED_XBOX,				// XUID Login Failure Response
	FROM_ACCOUNTSERVER_CREATE_ACCOUNT_SUCCESS_XBOX,		// XBOX Account Creation Success Message
	FROM_ACCOUNTSERVER_CREATE_ACCOUNT_FAILED_XBOX,		// XBOX Account Creation Failure Message
	FROM_ACCOUNTSERVER_VERSION,							// Account Server version response
	FROM_ACCOUNTSERVER_LOGIN_FAILED,					// TO_ACCOUNTSERVER_LOGIN_NEW failed
	FROM_ACCOUNTSERVER_LOGINVALIDATE_FAILED,			// TO_ACCOUNTSERVER_LOGINVALIDATE failed
	FROM_ACCOUNTSERVER_ONETIMECODEVALIDATE_RESPONSE,    // OneTimeCode validation response

	//anything with NVPSTRUCT in it means that it basically consists of a struct being sent
	//via ParserSendStructAsCheckedNameValuePairs, which ensure safe forward/backwards compatibility
	FROM_ACCOUNTSERVER_NVPSTRUCT_LOGIN_SALT,

	FROM_ACCOUNTSERVER_MAX
};

// Login type
AUTO_ENUM;
typedef enum AccountLoginType
{
	ACCOUNTLOGINTYPE_Default = 0, // currently functionally equivalent to _Cryptic
	ACCOUNTLOGINTYPE_Cryptic,
	ACCOUNTLOGINTYPE_PerfectWorld,
	ACCOUNTLOGINTYPE_CrypticAndPW,
	ACCOUNTLOGINTYPE_Max,
} AccountLoginType;

// Login failure reason
// WARNING: Never change the order of this enum.  Always add new values at the end.
// If you add new values here, you should also update these locations:
// 1) FoldFailureCode() and LegacyFailureText() in AccountServer.c
// 2) accountValidatorGetFailureReasonByCode() in accountnet.c
// 3) XMLRPCConvertFailureCode() in XMLInterface.c
// 4) FROM_ACCOUNTSERVER_LOGIN_FAILED in gclAccountHandleInput() in gclLogin.c
// 5) /data/ui/messages/LoginStatus.ms for each game (unless handling in (4) is special)
// 6) C:\src\Core\CrypticLauncher\manualstrings.txt under # accountnet error messages
AUTO_ENUM;
typedef enum LoginFailureCode {
	LoginFailureCode_Unknown = 0,							// Never sent by AS, but possibly returned by accountValidatorGetFailureCode()
	LoginFailureCode_Ok,									// Internal use only

	LoginFailureCode_NotFound,								// Generic failure, account not found
	LoginFailureCode_BadPassword,							// Never sent by AS, for security; LoginFailureCode_NotFound is used instead
	LoginFailureCode_RateLimit,								// Failed due to rate limiting
	LoginFailureCode_Disabled,								// Account disabled
	LoginFailureCode_UnlinkedPWCommonAccount,				// PW account needs manual linking before it can log in
	LoginFailureCode_InvalidTicket,							// Login validate: The ticket is not valid.
	LoginFailureCode_DisabledLinked,						// Login disabled because it has been linked already
	LoginFailureCode_InvalidLoginType,                      // AccountLoginType received was invalid
	LoginFailureCode_Banned,                                // Temporary account-wide ban (game-agnostic) (used by PWE)
	LoginFailureCode_NewMachineID,                          // Login from an unknown machine ID - send one-time-code auth
	LoginFailureCode_CrypticDisabled,						// Cryptic Account Login with DisallowCrypticAndPwLoginType
} LoginFailureCode;

// Validate failure reason
AUTO_ENUM;
typedef enum LoginValidateFailureCode {
	LoginValidateFailureCode_InvalidTicket = 2,
} LoginValidateFailureCode;

AUTO_ENUM;
typedef enum AccountServerProxyCmd
{
	TO_ACCOUNTSERVER_PROXY_DEPRECATED_1 = DEPRECATED_SHAREDCMD_MAX,		// was TO_ACCOUNTSERVER_PROXY_ACCOUNT_INFO
	TO_ACCOUNTSERVER_PROXY_SET,
	TO_ACCOUNTSERVER_PROXY_COMMIT,
	TO_ACCOUNTSERVER_PROXY_ROLLBACK,
	TO_ACCOUNTSERVER_PROXY_BEGIN,
	TO_ACCOUNTSERVER_PROXY_DEPRECATED_2,						// was TO_ACCOUNTSERVER_PROXY_KEEP
	TO_ACCOUNTSERVER_PROXY_DEPRECATED_3,						// was TO_ACCOUNTSERVER_PROXY_END
	TO_ACCOUNTSERVER_PROXY_PAYMENT_METHODS,
	TO_ACCOUNTSERVER_PROXY_DEPRECATED_4,						// was TO_ACCOUNTSERVER_PROXY_PERMISSIONS
	TO_ACCOUNTSERVER_PROXY_REQUEST_ALL_KEY_VALUES,
	TO_ACCOUNTSERVER_PROXY_REQUEST_ACCOUNT_ID_BY_DISPLAY_NAME,
	TO_ACCOUNTSERVER_PROXY_LOGOUT_NOTIFICATION,
	TO_ACCOUNTSERVER_PROXY_PROTOCOL_VERSION,
	TO_ACCOUNTSERVER_PROXY_SIMPLE_SET,
	TO_ACCOUNTSERVER_PROXY_GET_SUBBED_TIME,
	TO_ACCOUNTSERVER_PROXY_REQUEST_RECRUIT_INFO,
	TO_ACCOUNTSERVER_PROXY_DEPRECATED_5,						// was TO_ACCOUNTSERVER_PROXY_DISCOUNT_INFO
	TO_ACCOUNTSERVER_PROXY_AUTHCAPTURE,
	TO_ACCOUNTSERVER_PROXY_CAPTURE,
	TO_ACCOUNTSERVER_PROXY_DEPRECATED_6,						// was TO_ACCOUNTSERVER_PROXY_DISCOUNT_INFO_NEW
	TO_ACCOUNTSERVER_PROXY_CREATE_TICKET_FOR_ONLINE_ACCOUNT,
	TO_ACCOUNTSERVER_PROXY_GET,
	TO_ACCOUNTSERVER_PROXY_GET_LINKING_STATUS,
	TO_ACCOUNTSERVER_PROXY_EVENT_REQUEST,
	TO_ACCOUNTSERVER_PROXY_CREATE_CURRENCY,
	TO_ACCOUNTSERVER_PROXY_MOVE,
	TO_ACCOUNTSERVER_PROXY_COMMIT_MOVE,
	TO_ACCOUNTSERVER_PROXY_ROLLBACK_MOVE,
	TO_ACCOUNTSERVER_PROXY_PLAYED_TIME,
	TO_ACCOUNTSERVER_PROXY_ACCOUNT_DATA,
	TO_ACCOUNTSERVER_PROXY_NUM_CHARACTERS,

	TO_ACCOUNTSERVER_PROXY_MAX
} AccountServerProxyCmd;

enum
{
	FROM_ACCOUNTSERVER_PROXY_DEPRECATED_1 = DEPRECATED_SHAREDCMD_MAX,		// was FROM_ACCOUNTSERVER_PROXY_ACCOUNT_INFO
	FROM_ACCOUNTSERVER_PROXY_SET_RESULT,
	FROM_ACCOUNTSERVER_PROXY_ACK,
	FROM_ACCOUNTSERVER_PROXY_PAYMENT_METHODS,
	FROM_ACCOUNTSERVER_PROXY_DEPRECATED_2,						// was FROM_ACCOUNTSERVER_PROXY_PERMISSIONS
	FROM_ACCOUNTSERVER_PROXY_PRODUCTS,
	FROM_ACCOUNTSERVER_PROXY_ALL_KEY_VALUES,
	FROM_ACCOUNTSERVER_PROXY_KEY_VALUE,
	FROM_ACCOUNTSERVER_PROXY_REMOVE_KEY,
	FROM_ACCOUNTSERVER_PROXY_REQUEST_ACCOUNT_ID_BY_DISPLAY_NAME,
	FROM_ACCOUNTSERVER_PROXY_PROTOCOL_VERSION,
	FROM_ACCOUNTSERVER_PROXY_SIMPLE_SET,
	FROM_ACCOUNTSERVER_PROXY_SUBBED_TIME,
	FROM_ACCOUNTSERVER_PROXY_RECRUIT_INFO,
	FROM_ACCOUNTSERVER_PROXY_ALL_KEY_VALUES_PLAYERID,
	FROM_ACCOUNTSERVER_PROXY_DEPRECATED_3,						// was FROM_ACCOUNTSERVER_PROXY_DISCOUNT_INFO
	FROM_ACCOUNTSERVER_PROXY_AUTHCAPTURE,
	FROM_ACCOUNTSERVER_PROXY_CAPTURE,
	FROM_ACCOUNTSERVER_PROXY_DEPRECATED_4,						// was FROM_ACCOUNTSERVER_PROXY_DISCOUNT_INFO_NEW
	FROM_ACCOUNTSERVER_PROXY_TICKET_FOR_ONLINE_ACCOUNT,
	FROM_ACCOUNTSERVER_PROXY_DISCOUNTS,
	FROM_ACCOUNTSERVER_PROXY_GET_RESULT,
	FROM_ACCOUNTSERVER_PROXY_LINKING_STATUS,
	FROM_ACCOUNTSERVER_PROXY_MOVE_RESULT,
	FROM_ACCOUNTSERVER_PROXY_PLAYED_TIME,
	FROM_ACCOUNTSERVER_PROXY_DISPLAY_NAME,
	FROM_ACCOUNTSERVER_PROXY_ACCOUNT_DATA,

	FROM_ACCOUNTSERVER_PROXY_MAX
};



//controller comm stuff is here because clients need it for debug-only server monitoring
AUTO_ENUM;
typedef enum ToControllerMsg
{
	TO_CONTROLLER_CONNECT = DEPRECATED_SHAREDCMD_MAX,
	TO_CONTROLLER_DISCONNECT,

	TO_CONTROLLER_BIGGREENBUTTON,
	TO_CONTROLLER_MCP_REQUESTS_RESET,
	TO_CONTROLLER_MCP_REQUESTS_HIDE_SERVER,
	TO_CONTROLLER_MCP_REQUESTS_LOCAL_STATUS,

	TO_CONTROLLER_REQUEST_SERVER_CREATION, //UNUSED can be removed/replaced

	TO_CONTROLLER_REQUEST_SERVER_LIST,

	TO_CONTROLLER_MCP_REQUESTS_SERVER_LIST,

	TO_CONTROLLER_MCP_REQUESTS_MONITORING_COMMAND,

	TO_CONTROLLER_HERE_ARE_LAUNCHERS_IPS,

	TO_CONTROLLER_SETTING_SERVER_STATE,

	TO_CONTROLLER_ERROR_DIALOG_FOR_MCP,

	TO_CONTROLLER_SET_GAMESERVERS_START_IN_DEBUGGER,

	TO_CONTROLLER_HERE_ARE_SERVERTYPE_COMMANDLINES,

	TO_CONTROLLER_MCP_IS_READY,

	TO_CONTROLLER_LAUNCHER_RELAYING_ERRORS,

	TO_CONTROLLER_LAUNCHER_RELAYING_SCRIPT_RESULT,

	TO_CONTROLLER_LAUNCHER_RELAYING_CLIENT_STATE,

	TO_CONTROLLER_RUN_SCRIPT,

	TO_CONTROLLER_MCP_REQUESTS_XPATH_FOR_HTTP__DEPRECATED,

	TO_CONTROLLER_HERE_IS_REQUESTED_MONITORING_INFO,

	TO_CONTROLLER_HERE_IS_REQUESTED_MONITORING_COMMAND_RESULT,

	//something like TransactionServerGlobalInfo is being sent 
	//by a server type that can't call a REMOTE_COMMAND
	TO_CONTROLLER_HERE_IS_GLOBAL_SERVER_MONITORING_SUMMARY, 

	TO_CONTROLLER_MCP_REQUESTS_MONITORING_JPEG,

	TO_CONTROLLER_HERE_IS_REQUESTED_MONITORING_JPEG,

	TO_CONTROLLER_HERE_IS_ALERT,

	TO_CONTROLLER_MCP_REQUESTS_XPATH_FOR_HTTP,

	TO_CONTROLLER_MCP_REQUESTS_FILE_SERVING,
	
	TO_CONTROLLER_FILE_SERVING_FULFILLED,

	TO_CONTROLLER_KEEP_ALIVE,

	TO_CONTROLLER_PID_OF_NEW_SERVER,

	TO_CONTROLLER_LAUNCHER_REQUESTS_LOCAL_EXES_FOR_MIRRORING,

	TO_CONTROLLER_LAUNCHER_GOT_LOCAL_EXES_FOR_MIRRORING,

	TO_CONTROLLER_HERE_IS_GLOBAL_LOGSERVER_INFO,

	TO_CONTROLLER_HERE_IS_DATA_MIRRORING_REPORT,

	//use carefully... takes a string and tries to cmdparse it on the controller
	TO_CONTROLLER_EXECUTE_COMMAND_STRING,

	TO_CONTROLLER_LAUNCHER_WANTS_BYTES_FROM_FILE,

	TO_CONTROLLER_LAUNCHER_REPORTING_DYN_HOG_PRUNING_SUCCESS,
	TO_CONTROLLER_LAUNCHER_REPORTING_DYN_HOG_PRUNING_FAILURE,
	TO_CONTROLLER_LAUNCHER_REPORTING_DYN_HOG_PRUNING_COMMENT,

	TO_CONTROLLER_MCP_SETS_EXE_NAME_AND_DIR,

	TO_CONTROLLER_LAUNCHER_RELAYING_SCRIPT_PAUSE_REQUEST,

	TO_CONTROLLER_LAUNCHER_REQUESTING_EXE_FROM_NAME_AND_CRC,

	TO_CONTROLLER_HERE_ARE_SYSTEM_SPECS,

	TO_CONTROLLER_REQUESTING_TIMESS2000,

	TO_CONTROLLER_FILE_SERVING_HANDSHAKE,

	TO_CONTROLLER_MAX,
} ToControllerMsg;



AUTO_ENUM;
typedef enum FromControllerMsg
{
	FROM_CONTROLLER_CONNECTIONRESULT = DEPRECATED_SHAREDCMD_MAX,
	FROM_CONTROLLER_KILLYOURSELF,
	FROM_CONTROLLER_INCCOOKIE,
	FROM_CONTROLLER_REQUESTING_MONITORING_INFO,

	FROM_CONTROLLER_IAMDYING,

	FROM_CONTROLLER_HERE_IS_LOCAL_STATUS,

	FROM_CONTROLLER_HERE_IS_SERVER_LIST_FOR_MCP,

	FROM_CONTROLLER_HERE_IS_ERROR_DIALOG_FOR_MCP,

	FROM_CONTROLLER_SCRIPT_UPDATE_FOR_MCP,
	FROM_CONTROLLER_SCRIPT_STATE_FOR_MCP,

	FROM_CONTROLLER_RELAY_COMMAND_TO_XBOX_CLIENT,

	FROM_CONTROLLER_HERE_IS_XPATH_HTTP_FOR_MCP,

	FROM_CONTROLLER_MONITORING_COMMAND_RETURN,

	FROM_CONTROLLER_REQUESTING_MONITORING_COMMAND,

	FROM_CONTROLLER_HERE_IS_JPEG_FOR_MCP,

	FROM_CONTROLLER_REQUESTING_MONITORING_JPEG,

	FROM_CONTROLLER_FILE_SERVING_RETURN,

	FROM_CONTRLLER_REQUESTING_FILE_SERVING,

	FROM_CONTROLLER_REQUEST_BEGIN_KEEPALIVE,

//certain special servers (trans server, multiplexers) get special notifications when servers crash or restart
	FROM_CONTROLLER__SERVERSPECIFIC__SERVER_CRASHED,
	FROM_CONTROLLER__SERVERSPECIFIC__SERVER_RESTARTED,

	FROM_CONTROLLER_AUTO_SETTING_COMMANDS,

	FROM_CONTROLLER_HERE_IS_LOCAL_NOTE,

	FROM_CONTROLLER_HERE_IS_SHARD_CLUSTER_OVERVIEW,

	FROM_CONTROLLER_HERE_IS_TIMESS2000,

	//only sent to monitoring MCP, tells it to open up a specific URL
	FROM_CONTROLLER_OPEN_URL_FOR_MONITORING,

	FROM_CONTROLLER_MAX,
} FromControllerMsg;

enum
{
	TO_GLOBALCHATSERVER_CONNECT = DEPRECATED_SHAREDCMD_MAX,
	TO_GLOBALCHATSERVER_COMMAND,
	TO_GLOBALCHATSERVER_ACCOUNT_REQUEST,
	TO_GLOBALCHATSERVER_CHANNEL_REQUEST,

	// These commands are received from the Account Server
	TO_GLOBALCHATSERVER_DISPLAYNAME_TRANS,
	TO_GLOBALCHATSERVER_CREATEACCOUNT,
	TO_GLOBALCHATSERVER_DISPLAYNAME_UPDATE,

	// These commands manipulate metric measurements
	TO_GLOBALCHATSERVER_RESET_METRICS,
	TO_GLOBALCHATSERVER_METRICS_REQUEST,

	// Register a connected local shard and information about it
	TO_GLOBALCHATSERVER_REGISTER_SHARD, // deprecated, see *_EX

	// This is also from the account server
	TO_GLOBALCHATSERVER_REMOVEACCOUNT, 

	TO_GLOBALCHATSERVER_REGISTER_SHARD_EX,
};

enum
{
	FROM_GLOBALCHATSERVER_COMMAND = DEPRECATED_SHAREDCMD_MAX,
	FROM_GLOBALCHATSERVER_ACCOUNT_LIST,
	FROM_GLOBALCHATSERVER_CHANNEL_LIST,
	FROM_GLOBALCHATSERVER_CHANNEL_DELETE, 
	FROM_GLOBALCHATSERVER_MESSAGE,
	FROM_GLOBALCHATSERVER_ALERT,
	FROM_GLOBALCHATSERVER_METRICS,
	FROM_GLOBALCHATSERVER_SHARDINFO_REQUEST,
	FROM_GLOBALCHATSERVER_VERSIONINFO,
};


enum
{
	TO_OBJECTDB_TRANSFER_CHARACTER = DEPRECATED_SHAREDCMD_MAX,
};

// For Test Server communication
enum
{
	TO_TESTSERVER_SET_GLOBAL = DEPRECATED_SHAREDCMD_MAX,
	TO_TESTSERVER_GET_GLOBAL,
	TO_TESTSERVER_PUSH_METRIC,
	TO_TESTSERVER_GET_METRIC,
	TO_TESTSERVER_CLEAR_GLOBAL,

	TO_TESTSERVER_I_AM_A_TESTCLIENT,
	TO_TESTSERVER_TESTCLIENT_ID,
	TO_TESTSERVER_TESTCLIENT_ENTITY_ID,
	TO_TESTSERVER_TESTCLIENT_STATUS,
};

enum
{
	FROM_TESTSERVER_HERE_IS_GLOBAL = DEPRECATED_SHAREDCMD_MAX,
	FROM_TESTSERVER_HERE_IS_METRIC,
	FROM_TESTSERVER_TESTCLIENT_ID,
	FROM_TESTSERVER_TESTCLIENT_COMMAND,
	FROM_TESTSERVER_TESTCLIENT_DIE,
};

enum
{
	TO_MACHINESTATUS_HERE_IS_UPDATE = DEPRECATED_SHAREDCMD_MAX,
};

enum
{
	FROM_MACHINESTATUS_HIDE_ALL = DEPRECATED_SHAREDCMD_MAX,
	FROM_MACHINESTATUS_SHOW_ALL,
};

// Commands from a PatchClientLib patcher to a client using PatchClientLibStatusMonitoring.
enum
{
	FROM_PATCHCLIENT_FOR_STATUSREPORTING_UPDATE = DEPRECATED_SHAREDCMD_MAX,
};

// Commands to a PatchClientLib patcher from a client using PatchClientLibStatusMonitoring.
enum
{
	TO_PATCHCLIENT_FOR_STATUSREPORTING_ABORT = DEPRECATED_SHAREDCMD_MAX,
};

enum
{
	FROM_CB_TO_CBMONITOR_RUNBEGAN = DEPRECATED_SHAREDCMD_MAX,
	FROM_CB_TO_CBMONITOR_RUNENDED,
	FROM_CB_TO_CBMONITOR_VARIABLESET,
	FROM_CB_TO_CBMONITOR_STATESET,
	FROM_CB_TO_CBMONITOR_HEARTBEAT,
	FROM_CB_TO_CBMONITOR_CONNECT,
	FROM_CB_TO_CBMONITOR_BUILDERCOMMENT,
	FROM_CB_TO_CBMONITOR_BUILDERPLEXLOGDIRS,
};


enum
{
	TO_NOTESSERVER_REQUESTING_NOTES = DEPRECATED_SHAREDCMD_MAX,
	TO_NOTESSERVER_SETTING_NOTE,
};

enum
{
	FROM_NOTESSERVER_HERE_ARE_NOTES = DEPRECATED_SHAREDCMD_MAX,
	FROM_NOTESSERVER_HERE_IS_SERVER_INFO,
};



enum
{
	MULTIPLEXED_MAKEBINS_MASTER_TO_SLAVE_HERE_IS_ZMAP_TO_BIN = DEPRECATED_SHAREDCMD_MAX,
	MULTIPLEXED_MAKEBINS_MASTER_TO_SLAVE_ALL_DONE,
};

enum
{
	MULTIPLEXED_MAKEBINS_SLAVE_TO_MASTER_REQUESTING_ZMAP = DEPRECATED_SHAREDCMD_MAX,
	MULTIPLEXED_MAKEBINS_SLAVE_TO_MASTER_REPORTING_COMPLETION,
	MULTIPLEXED_MAKEBINS_SLAVE_TO_MASTER_TOUCHED_BIN_FILE,
};


enum
{
	TO_NEWCONTROLLERTRACKER_FROM_SHARD_HERE_IS_SHARD_INFO = DEPRECATED_SHAREDCMD_MAX,
	TO_NEWCONTROLLERTRACKER_FROM_SHARD_HERE_ARE_LAST_MINUTE_FILES,
	TO_NEWCONTROLLERTRACKER_FROM_SHARD_HERE_IS_SHARD_PERF_INFO,
	TO_NEWCONTROLLERTRACKER_FROM_GLOBAL_CHATSERVER_ONLINE_MESSAGE,
	TO_NEWCONTROLLERTRACKER_FROM_SHARD_HERE_ARE_LOGINSERVER_IPS,

	//special command sent by the SetShardVersionOnCT.exe app... does nothing if the named
	//shard is currently active, if it's not active, and if there's a perm shard with that
	//name, sets the patch command line and version string
	TO_NEWCONTROLLERTRACKER_HERE_IS_VERSION_FOR_OFFLINE_SHARD,

	TO_NEWCONTROLLERTRACKER_FROM_SHARD_HERE_ARE_LOGINSERVER_IPS_AND_PORTS,
};

enum
{
	TO_OVERLORD_HERE_ARE_FORWARDED_SERVER_STATUSES = DEPRECATED_SHAREDCMD_MAX,
};






// Below here, moved over from serverlib.h, where linking madness was going to ensue

enum
{
	LOGCLIENT_LOGPRINTF = DEPRECATED_SHAREDCMD_MAX,
	LOGCLIENT_HEREARECATEGORYNAMES,
};

AUTO_ENUM;
typedef enum TransClientPacketType
{
	TRANSCLIENT_REQUEST_NEW_TRANSACTION = DEPRECATED_SHAREDCMD_MAX,
	TRANSCLIENT_TRANSACTIONFAILED,
	TRANSCLIENT_TRANSACTIONSUCCEEDED,
	TRANSCLIENT_TRANSACTIONBLOCKED,
	TRANSCLIENT_TRANSACTIONCANCELCONFIRMED,
	TRANSCLIENT_TRANSACTIONPOSSIBLE,

	//an optimization
	//sent only when a locking atomic transaction has only one base transaction... so if it succeeds,
	//it can confirm immediately as there is no possibility of unrolling
	TRANSCLIENT_TRANSACTIONPOSSIBLEANDCONFIRMED,

	TRANSCLIENT_REGISTERCLIENTINFO,
	TRANSCLIENT_SENDTRANSSERVERCOMMANDANDCOMMENT,
	TRANSCLIENT_UPDATESFROMLOCALTRANS,
	TRANSCLIENT_SETTRANSVARIABLE,

	//the transaction server has a simple-packet-sending mode where it simply takes a packet that one
	//server sent it and sends it off to another one without doing any transactiony stuff at all
	TRANSCLIENT_SEND_PACKET_SIMPLE,

	//debugging only. the LTM requests the type/ID of the owner of a specified container
	TRANSCLIENT_DBG_REQUESTCONTAINEROWNER,

	//some transactions have completed slowly... do some debugging magic with this information
	TRANSCLIENT_DBG_LAGGEDTRANSACTION,

	//a single transaction was very slow locally in the auto trans update CB. Register this with the tracker
	//for sorting purposes
	TRANSCLIENT_REGISTER_SLOW_TRANSCALLBACK_WITH_TRACKER,

	//simple packet, but to send to another shard in the shard cluster
	TRANSCLIENT_SEND_PACKET_SIMPLE_OTHER_SHARD,
} TransClientPacketType;



AUTO_ENUM;
typedef enum enumTransServerMessagesToLTMs
{
	//sent by the transaction server to local transaction managers
	TRANSSERVER_REQUEST_SINGLE_TRANSACTION = DEPRECATED_SHAREDCMD_MAX,
	TRANSSERVER_CANCEL_TRANSACTION,
	TRANSSERVER_CONFIRM_TRANSACTION,

	//sent by the transaction server to transaction request managers
	TRANSSERVER_TRANSACTION_COMPLETE,

	//sent by the transaction server to the DB server
	TRANSSERVER_TRANSACTION_DBUPDATE,

	//your connection attempt has either failed or succeeded. Here is the result...
	TRANSSERVER_CONNECTION_RESULT,

	//a simple packet has been sent to you (a no-return remote command, or a call to 
	//GetPacketToSendThroughTransactionServer()
	TRANSSERVER_SEND_PACKET_SIMPLE,

	//the simple packet you sent could not be delivered
	TRANSSERVER_SIMPLE_PACKET_ERROR,

	//here is the owner type/ID you requested
	TRANSSERVER_HERE_IS_OWNER,
} enumTransServerMessagesToLTMs;

AUTO_ENUM AEN_APPEND_OTHER_TO_ME(ToControllerMsg);
typedef enum LauncherAnswer 
{
	LAUNCHERANSWER_PROCESS_CLOSED = TO_CONTROLLER_MAX,
	LAUNCHERANSWER_PROCESS_CRASHED,
	LAUNCHERANSWER_PROCESSES,
	LAUNCHER_ANSWER_CRYPTIC_ERROR_IS_FINISHED_WITH_SERVER,
	LAUNCHER_ANSWER_CLIENT_REQUESTS_OPEN_MONITORING_URL,
} LauncherAnswer;

enum 
{
	INTERSHARDCOMM_REQUEST_CMD = DEPRECATED_SHAREDCMD_MAX,
};

AUTO_ENUM AEN_APPEND_OTHER_TO_ME(FromControllerMsg);
typedef enum LauncherQueryCommands
{
	LAUNCHERQUERY_REGISTEREXISTINGPROCESS = FROM_CONTROLLER_MAX,
	LAUNCHERQUERY_STARTPROCESS,
	LAUNCHERQUERY_GAMEVERSION,
	LAUNCHERQUERY_KILLPROCESS,
	LAUNCHERQUERY_HIDEPROCESS,
	LAUNCHERQUERY_IGNOREPROCESS,
	LAUNCHERQUERY_SETDIRECTORYCONTENTS,
	LAUNCHERQUERY_GETAMANUALDUMP,
	LAUNCHERQUERY_HEREARELOCALEXECRCS,
	LAUNCHERQUERY_HEREAREREQUESTEDEXES,
	LAUNCHERQUERY_CONTROLLERTIME,
	LAUNCHERQUERY_VERBOSEPROCLISTLOGGING,
	LAUNCHERQUERY_BEGINGETTINGFILES,
	LAUNCHERQUERY_HEREAREREQUESTEDBYTESFROMFILE,
	LAUNCHERQUERY_KILLALLBYNAME,
	LAUNCHERQUERY_REQUEST_DYN_HOG_PRUNING,
	LAUNCHERQUERY_REQUEST_LAUNCH_AND_QUERY_PROCESS,
	LAUNCHERQUERY_SETLOGSERVER,
	LAUNCHERQUERY_FILEREQUESTFULFILLED,

} LauncherQueryCommands;


enum
{
	TO_NEWCONTROLLERTRACKER_FROM_MASTER_HERE_IS_STATIC_DATA = DEPRECATED_SHAREDCMD_MAX,
};


enum
{
	LOGSERVER_TO_LOGPARSER_HERE_ARE_LOGS = DEPRECATED_SHAREDCMD_MAX,
	LOGSERVER_TO_LOGPARSER_ABOUT_TO_DIE,
};

enum
{
	SHARDCLUSTER_CONTROLLER_REQUEST_STATUS = DEPRECATED_SHAREDCMD_MAX,
	SHARDCLUSTER_CONTROLLER_HERE_IS_STATUS,
};

enum
{
	SHARDCLUSTER_TRANSACTIONSERVER_HERE_IS_COMMAND = DEPRECATED_SHAREDCMD_MAX,
	SHARDCLUSTER_TRANSACTIONSERVER_COMMAND_RECEIPT,
};

enum
{
	CONTROLLER_TO_CLUSTERCONTROLLER__STATUS = DEPRECATED_SHAREDCMD_MAX,
	CONTROLLER_TO_CLUSTERCONTROLLER__COMMAND_RETURN,
	CONTROLLER_TO_CLUSTERCONTROLLER__HERE_ARE_AUTO_SETTINGS,
	CONTROLLER_TO_CLUSTERCONTROLLER__HERE_ARE_SHARD_VARIABLES,
};

enum
{
	CLUSTERCONTROLLER_TO_CONTROLLER__COMMAND = DEPRECATED_SHAREDCMD_MAX,
	CLUSTERCONTROLLER_TO_CONTROLLER__SENDFILE,
	CLUSTERCONTROLLER_TO_CONTROLLER__KILLYOURSELF,
	CLUSTERCONTROLLER_TO_CONTROLLER__REQUEST_AUTO_SETTINGS,
	CLUSTERCONTROLLER_TO_CONTROLLER__REQUEST_SHARD_VARIABLES,
};


#endif
