#include "textparser.h"
//autogeneratednocheckin
extern ParseTable parse_AICivilianPathLeg[];
#define TYPE_parse_AICivilianPathLeg AICivilianPathLeg
extern ParseTable parse_AICivilianPathLeg[];
#define TYPE_parse_AICivilianPathLeg AICivilianPathLeg
extern ParseTable parse_ACGDelNode[];
#define TYPE_parse_ACGDelNode ACGDelNode
extern ParseTable parse_ACGDelLine[];
#define TYPE_parse_ACGDelLine ACGDelLine
extern ParseTable parse_AICivilianPathIntersection[];
#define TYPE_parse_AICivilianPathIntersection AICivilianPathIntersection
extern ParseTable parse_AICivilianPathPoint[];
#define TYPE_parse_AICivilianPathPoint AICivilianPathPoint
extern ParseTable parse_AICivilianPathPointIntersection[];
#define TYPE_parse_AICivilianPathPointIntersection AICivilianPathPointIntersection
extern ParseTable parse_AICivIntersectionCurve[];
#define TYPE_parse_AICivIntersectionCurve AICivIntersectionCurve
//Structparser.exe autogenerated ParseTable for struct AICivilianPathInfo
#define TYPE_parse_AICivilianPathInfo AICivilianPathInfo
ParseTable parse_AICivilianPathInfo[] =
{
	{ "AICivilianPathInfo", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(AICivilianPathInfo), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "legs",					TOK_STRUCT(AICivilianPathInfo, legs, parse_AICivilianPathLeg) },
	{ "deletedLegs",			TOK_STRUCT(AICivilianPathInfo, deletedLegs, parse_AICivilianPathLeg) },
	{ "deletedNodes",			TOK_STRUCT(AICivilianPathInfo, deletedNodes, parse_ACGDelNode) },
	{ "deletedLines",			TOK_STRUCT(AICivilianPathInfo, deletedLines, parse_ACGDelLine) },
	{ "intersects",				TOK_STRUCT(AICivilianPathInfo, intersects, parse_AICivilianPathIntersection) },
	{ "pathPoints",				TOK_STRUCT(AICivilianPathInfo, pathPoints, parse_AICivilianPathPoint) },
	{ "pathPointIntersections",	TOK_STRUCT(AICivilianPathInfo, pathPointIntersections, parse_AICivilianPathPointIntersection) },
	{ "IntersectionCurves",		TOK_STRUCT(AICivilianPathInfo, eaIntersectionCurves, parse_AICivIntersectionCurve) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_AICivilianPathInfo()
{
	int iSize = sizeof(AICivilianPathInfo);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_AICivilianPathInfo, iSize, "AICivilianPathInfo", NULL, "aiCivLegGeneration.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ACGDelNode
#define TYPE_parse_ACGDelNode ACGDelNode
ParseTable parse_ACGDelNode[] =
{
	{ "ACGDelNode", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ACGDelNode), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "type",			TOK_AUTOINT(ACGDelNode, type, 0), NULL },
	{ "pos",			TOK_VEC3(ACGDelNode, pos), NULL },
	{ "delState",		TOK_AUTOINT(ACGDelNode, delState, 0), CivGenStateEnum },
	{ "delSubState",	TOK_AUTOINT(ACGDelNode, delSubState, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ACGDelNode()
{
	int iSize = sizeof(ACGDelNode);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ACGDelNode, iSize, "ACGDelNode", NULL, "aiCivLegGeneration.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ACGDelNode[];
#define TYPE_parse_ACGDelNode ACGDelNode
//Structparser.exe autogenerated ParseTable for struct ACGDelNodeList
#define TYPE_parse_ACGDelNodeList ACGDelNodeList
ParseTable parse_ACGDelNodeList[] =
{
	{ "ACGDelNodeList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ACGDelNodeList), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "nodes",			TOK_STRUCT(ACGDelNodeList, nodes, parse_ACGDelNode) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ACGDelNodeList()
{
	int iSize = sizeof(ACGDelNodeList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ACGDelNodeList, iSize, "ACGDelNodeList", NULL, "aiCivLegGeneration.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ACGDelLine
#define TYPE_parse_ACGDelLine ACGDelLine
ParseTable parse_ACGDelLine[] =
{
	{ "ACGDelLine", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ACGDelLine), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "type",		TOK_AUTOINT(ACGDelLine, type, 0), NULL },
	{ "start",		TOK_VEC3(ACGDelLine, start), NULL },
	{ "end",		TOK_VEC3(ACGDelLine, end), NULL },
	{ "delState",	TOK_AUTOINT(ACGDelLine, delState, 0), CivGenStateEnum },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ACGDelLine()
{
	int iSize = sizeof(ACGDelLine);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ACGDelLine, iSize, "ACGDelLine", NULL, "aiCivLegGeneration.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ACGDelLine[];
#define TYPE_parse_ACGDelLine ACGDelLine
//Structparser.exe autogenerated ParseTable for struct ACGDelLineList
#define TYPE_parse_ACGDelLineList ACGDelLineList
ParseTable parse_ACGDelLineList[] =
{
	{ "ACGDelLineList", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ACGDelLineList), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "list",			TOK_STRUCT(ACGDelLineList, list, parse_ACGDelLine) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ACGDelLineList()
{
	int iSize = sizeof(ACGDelLineList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ACGDelLineList, iSize, "ACGDelLineList", NULL, "aiCivLegGeneration.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
