#include "textparser.h"

//auto-generated staticdefine for enum FragileTargetType
//autogeneratednocheckin
StaticDefineInt FragileTargetTypeEnum[] =
{
	DEFINE_INT
	{ "TargetOnly", kFragileTarget_TargetOnly},
	{ "SourceOnly", kFragileTarget_SourceOnly},
	DEFINE_END
};
void autoEnum_fixup_FragileTargetType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(FragileTargetTypeEnum, "FragileTargetType");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct FragileScale
#define TYPE_parse_FragileScale FragileScale
ParseTable parse_FragileScale[] =
{
	{ "FragileScale", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(FragileScale), 0, NULL, 0, NULL },
	{ "offAttrib",		TOK_STRUCTPARAM | TOK_AUTOINT(FragileScale, offAttrib, 0), AttribTypeEnum },
	{ "Scale",			TOK_STRUCTPARAM | TOK_F32(FragileScale, fScale, 0), NULL },
	{ "\n",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_FragileScale()
{
	int iSize = sizeof(FragileScale);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_FragileScale, iSize, "FragileScale", NULL, "AttribModFragility.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_FragileScale[];
#define TYPE_parse_FragileScale FragileScale
extern ParseTable parse_CharacterAttribs[];
#define TYPE_parse_CharacterAttribs CharacterAttribs
//Structparser.exe autogenerated ParseTable for struct FragileScaleSet
#define TYPE_parse_FragileScaleSet FragileScaleSet
ParseTable parse_FragileScaleSet[] =
{
	{ "FragileScaleSet", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(FragileScaleSet), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Name",				TOK_STRUCTPARAM | TOK_KEY | TOK_STRING(FragileScaleSet, pchName, 0), NULL },
	{ "DefaultScale",		TOK_F32(FragileScaleSet, fScaleDefault, 0), NULL },
	{ "Scale",				TOK_STRUCT(FragileScaleSet, ppScales, parse_FragileScale) },
	{ "pattrScale",			TOK_NO_TEXT_SAVE | TOK_OPTIONALSTRUCT(FragileScaleSet, pattrScale, parse_CharacterAttribs) },
	{ "TargetType",			TOK_AUTOINT(FragileScaleSet, eTargetType, 0), FragileTargetTypeEnum  ,  TOK_FORMAT_FLAGS},
	{ "IgnoreTags",			TOK_AUTOINT(FragileScaleSet, eIgnoreTags, 0), PowerTagsEnum  ,  TOK_FORMAT_FLAGS},
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_FragileScaleSet()
{
	int iSize = sizeof(FragileScaleSet);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_FragileScaleSet, iSize, "FragileScaleSet", NULL, "AttribModFragility.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_CombatPoolDef[];
#define TYPE_parse_CombatPoolDef CombatPoolDef
extern ParseTable parse_PowerTagsStruct[];
#define TYPE_parse_PowerTagsStruct PowerTagsStruct
//Structparser.exe autogenerated ParseTable for struct ModDefFragility
#define TYPE_parse_ModDefFragility ModDefFragility
ParseTable parse_ModDefFragility[] =
{
	{ "ModDefFragility", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ModDefFragility), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "ExprBlockHealth",		TOK_OPTIONALLATEBINDSTRUCT(ModDefFragility, pExprHealth) },
	{ "TableHealth",			TOK_POOL_STRING | TOK_STRING(ModDefFragility, cpchTableHealth, 0), NULL },
	{ "Pool",					TOK_EMBEDDEDSTRUCT(ModDefFragility, pool, parse_CombatPoolDef)},
	{ "Proportion",				TOK_F32(ModDefFragility, fProportion, 0), NULL },
	{ "ScaleIn",				TOK_REFERENCE(ModDefFragility, hScaleIn, 0, "FragileScaleSet") },
	{ "ScaleOut",				TOK_REFERENCE(ModDefFragility, hScaleOut, 0, "FragileScaleSet") },
	{ "TagsExclude",			TOK_EMBEDDEDSTRUCT(ModDefFragility, tagsExclude, parse_PowerTagsStruct)},
	{ "MagnitudeIsHealth",		TOK_BIT, 0, 8, NULL},
	{ "SourceOnlyIn",			TOK_BIT, 0, 8, NULL},
	{ "SourceOnlyOut",			TOK_BIT, 0, 8, NULL},
	{ "UseResistIn",			TOK_BIT, 0, 8, NULL},
	{ "UseResistOut",			TOK_BIT, 0, 8, NULL},
	{ "FragileWhileDelayed",	TOK_BIT, 0, 8, NULL},
	{ "FragileToSameApply",		TOK_BIT, 0, 8, NULL},
	{ "Unkillable",				TOK_BIT, 0, 8, NULL},
	{ "ReplaceKeepsHealth",		TOK_BIT, 0, 8, NULL},
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
void FindAutoStructBitField(char *pStruct, int iAllocedSizeInWords, ParseTable *pTPIColumn);
int autoStruct_fixup_ModDefFragility()
{
	int iSize = sizeof(ModDefFragility);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ModDefFragility, iSize, "ModDefFragility", NULL, "AttribModFragility.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	{
		int iSizeInWords = (sizeof(ModDefFragility) + 7) / 4;
		ModDefFragility *pTemp = alloca(iSizeInWords * 4);
		memset(pTemp, 0, iSizeInWords * 4);
		pTemp->bMagnitudeIsHealth = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[9]);
		pTemp->bMagnitudeIsHealth = 0;
		pTemp->bSourceOnlyIn = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[10]);
		pTemp->bSourceOnlyIn = 0;
		pTemp->bSourceOnlyOut = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[11]);
		pTemp->bSourceOnlyOut = 0;
		pTemp->bUseResistIn = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[12]);
		pTemp->bUseResistIn = 0;
		pTemp->bUseResistOut = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[13]);
		pTemp->bUseResistOut = 0;
		pTemp->bFragileWhileDelayed = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[14]);
		pTemp->bFragileWhileDelayed = 0;
		pTemp->bFragileToSameApply = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[15]);
		pTemp->bFragileToSameApply = 0;
		pTemp->bUnkillable = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[16]);
		pTemp->bUnkillable = 0;
		pTemp->bReplaceKeepsHealth = ~0;
		FindAutoStructBitField((char*)pTemp, iSizeInWords, &parse_ModDefFragility[17]);
		pTemp->bReplaceKeepsHealth = 0;
	}
	return 0;
};
void DoAutoStructLateBind(ParseTable *pTPI, int iColumnIndex, char *pOtherTPIName);
void autoStruct_lateFixup_ModDefFragility(void)
{
	DoAutoStructLateBind(parse_ModDefFragility, 2, "Expression");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ModFragility
#define TYPE_parse_ModFragility ModFragility
ParseTable parse_ModFragility[] =
{
	{ "ModFragility", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ModFragility), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "fHealth",			TOK_PERSIST | TOK_NO_TRANSACT | TOK_F32(ModFragility, fHealth, 0), NULL },
	{ "fHealthMax",			TOK_PERSIST | TOK_NO_TRANSACT | TOK_F32(ModFragility, fHealthMax, 0), NULL },
	{ "fHealthOriginal",	TOK_PERSIST | TOK_NO_TRANSACT | TOK_F32(ModFragility, fHealthOriginal, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ModFragility()
{
	int iSize = sizeof(ModFragility);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ModFragility, iSize, "ModFragility", NULL, "AttribModFragility.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
