#ifndef __ATTRIBMOD_H_AST_H_
#define __ATTRIBMOD_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \AttribMod.h
//autogeneratednocheckin

//auto-generated staticdefine for enum ModTarget
//autogeneratednocheckin
extern StaticDefineInt ModTargetEnum[];

//auto-generated staticdefine for enum ModType
//autogeneratednocheckin
extern StaticDefineInt ModTypeEnum[];

//auto-generated staticdefine for enum StackEntity
//autogeneratednocheckin
extern StaticDefineInt StackEntityEnum[];

//auto-generated staticdefine for enum StackType
//autogeneratednocheckin
extern StaticDefineInt StackTypeEnum[];

//auto-generated staticdefine for enum ModHitTest
//autogeneratednocheckin
extern StaticDefineInt ModHitTestEnum[];

//auto-generated staticdefine for enum CombatEventResponse
//autogeneratednocheckin
extern StaticDefineInt CombatEventResponseEnum[];

//auto-generated staticdefine for enum ModExpirationReason
//autogeneratednocheckin
extern StaticDefineInt ModExpirationReasonEnum[];

//auto-generated staticdefine for enum ModExpirationEntity
//autogeneratednocheckin
extern StaticDefineInt ModExpirationEntityEnum[];

extern ParseTable parse_AttribSet[];
#define TYPE_parse_AttribSet AttribSet

extern ParseTable parse_AttribSets[];
#define TYPE_parse_AttribSets AttribSets

extern ParseTable parse_PowerTagsStruct[];
#define TYPE_parse_PowerTagsStruct PowerTagsStruct

extern ParseTable parse_ModExpiration[];
#define TYPE_parse_ModExpiration ModExpiration

extern ParseTable parse_AttribModDefParams[];
#define TYPE_parse_AttribModDefParams AttribModDefParams

extern ParseTable polyTable_AttribModDefParams[];

extern ParseTable parse_AttribModAnimFX[];
#define TYPE_parse_AttribModAnimFX AttribModAnimFX

extern ParseTable parse_AttribModDef[];
#define TYPE_parse_AttribModDef AttribModDef

extern ParseTable parse_PowerApplyStrength[];
#define TYPE_parse_PowerApplyStrength PowerApplyStrength

//This is the autogenerated non-const copy of PowerApplyStrength
//Here are some struct prototypes for PowerApplyStrength

typedef struct PowerApplyStrength_AutoGen_NoConst { 
	REF_TO ( PowerDef ) hdef ; 
	U32 uiVersion ; 
	F32 * pfModStrengths ; 
	F32 * pfModStrAdd ; 
	S32 * piModFlags ; 
	F32 * pfModCritThreshold ; 
	} 
PowerApplyStrength_AutoGen_NoConst ; 



extern ParseTable parse_PowerClone[];
#define TYPE_parse_PowerClone PowerClone

//This is the autogenerated non-const copy of PowerClone
//Here are some struct prototypes for PowerClone

typedef struct PowerClone_AutoGen_NoConst { 
	REF_TO ( PowerDef ) hdef ; 
	int iLevel ; 
	F32 fTableScale ; 
	} 
PowerClone_AutoGen_NoConst ; 



extern ParseTable parse_AttribModSourceDetails[];
#define TYPE_parse_AttribModSourceDetails AttribModSourceDetails

//This is the autogenerated non-const copy of AttribModSourceDetails
//Here are some struct prototypes for AttribModSourceDetails
typedef struct PowerClone_AutoGen_NoConst PowerClone_AutoGen_NoConst;
typedef struct PACritical_AutoGen_NoConst PACritical_AutoGen_NoConst;

typedef struct AttribModSourceDetails_AutoGen_NoConst { 
	REF_TO ( CharacterClass ) hClass ; 
	int iLevel ; 
	int iIdxMulti ; 
	F32 fTableScale ; 
	PowerClone_AutoGen_NoConst * * ppEnhancements ; 
	PACritical_AutoGen_NoConst * pCritical ; 
	EntityRef erTargetApplication ; 
	Vec3 vecTargetApplication ; 
	S64 iItemID ; 
	U8 bLevelAdjusting : 1 ; 
	} 
AttribModSourceDetails_AutoGen_NoConst ; 



extern ParseTable parse_AttribModParams[];
#define TYPE_parse_AttribModParams AttribModParams

//This is the autogenerated non-const copy of AttribModParams
//Here are some struct prototypes for AttribModParams

typedef struct AttribModParams_AutoGen_NoConst { 
	Vec3 vecParam ; 
	Vec3 vecTarget ; 
	float fFacing ; 
	Vec3 vecOffset ; 
	EntityRef erParam ; 
	S32 iParam ; 
	REF_TO ( WorldInteractionNode ) hNodeParam ; 
	CommandQueue * pCommandQueue ; 
	ExprLocalData * * localData ; 
	AttribType eDynamicCachedType ; 
	} 
AttribModParams_AutoGen_NoConst ; 



extern ParseTable parse_AttribStat[];
#define TYPE_parse_AttribStat AttribStat

extern ParseTable parse_AttribModLink[];
#define TYPE_parse_AttribModLink AttribModLink

extern ParseTable parse_AttribMod[];
#define TYPE_parse_AttribMod AttribMod

//This is the autogenerated non-const copy of AttribMod
//Here are some struct prototypes for AttribMod
typedef struct AttribModParams_AutoGen_NoConst AttribModParams_AutoGen_NoConst;
typedef struct ModFragility_AutoGen_NoConst ModFragility_AutoGen_NoConst;
typedef struct Power_AutoGen_NoConst Power_AutoGen_NoConst;
typedef struct PowerSubtargetChoice_AutoGen_NoConst PowerSubtargetChoice_AutoGen_NoConst;
typedef struct PowerApplyStrength_AutoGen_NoConst PowerApplyStrength_AutoGen_NoConst;
typedef struct AttribModSourceDetails_AutoGen_NoConst AttribModSourceDetails_AutoGen_NoConst;

typedef struct AttribMod_AutoGen_NoConst { 
	EntityRef erOwner ; 
	EntityRef erSource ; 
	Vec3 vecSource ; 
	AttribModDef * pDef ; 
	REF_TO ( PowerDef ) hPowerDef ; 
	U32 uiVersion ; 
	U32 uiDefIdx ; 
	U32 uiApplyID ; 
	U32 uiActIDServer ; 
	U32 uiPowerID ; 
	S32 iPowerIDSub ; 
	S16 iPowerIDLinkedSub ; 
	EntityRef erPersonal ; 
	U32 uiRandomSeedActivation ; 
	AttribModParams_AutoGen_NoConst * pParams ; 
	U32 uiAnimFXID ; 
	F32 fHue ; 
	U32 uiTimestamp ; 
	F32 fAnimFXDelay ; 
	U32 bActive : 1 ; 
	U32 bIgnored : 1 ; 
	U32 bDisabled : 1 ; 
	U32 bContinuingAnimFXOn : 1 ; 
	U32 bConditionalAnimFXOn : 1 ; 
	U32 bNotifiedAI : 1 ; 
	U32 bNotifiedPVP : 1 ; 
	U32 bNotifiedGameEvent : 1 ; 
	U32 bCheckSource : 1 ; 
	U32 bCheckLunge : 1 ; 
	U32 bNew : 1 ; 
	U32 bResistPositive : 1 ; 
	U32 bResistNegative : 1 ; 
	U32 bProcessOfflineTimeOnLogin : 1 ; 
	U32 bDeathPeekCompleted : 1 ; 
	U32 bPostFirstTickApply : 1 ; 
	U32 bProcessedDisplayNameTraker : 1 ; 
	F32 fDuration ; 
	F32 fDurationOriginal ; 
	F32 fMagnitude ; 
	F32 fMagnitudeOriginal ; 
	ModFragility_AutoGen_NoConst * pFragility ; 
	F32 fAvoidance ; 
	F32 fTimer ; 
	U32 uiPeriod ; 
	F32 fCheckTimer ; 
	F32 fPredictionOffset ; 
	EntityRef erCreated ; 
	Power_AutoGen_NoConst * * ppPowersCreated ; 
	PowerSubtargetChoice_AutoGen_NoConst * pSubtarget ; 
	PowerApplyStrength_AutoGen_NoConst * * ppApplyStrengths ; 
	AttribModSourceDetails_AutoGen_NoConst * pSourceDetails ; 
	union { 
		AttribModLink * * eaAttribModLinks ; 
		AttribModLink * pAttribModLink ; 
		} 
	; 
	CombatTrackerFlag eFlags ; 
	} 
AttribMod_AutoGen_NoConst ; 



extern ParseTable parse_AttribModNet[];
#define TYPE_parse_AttribModNet AttribModNet

#endif
