/***************************************************************************
*     Copyright (c) 2005-2006, Cryptic Studios
*     All Rights Reserved
*     Confidential Property of Cryptic Studios
***************************************************************************/

#ifndef GSLSENDTOCLIENT_H_
#define GSLSENDTOCLIENT_H_

#include "GlobalComm.h"
#include "EntityNet.h"
#include "ReferenceSystem.h"

typedef struct ChatData ChatData;
typedef struct ClientLink ClientLink;
typedef struct Entity Entity;
typedef enum CmdContextFlag CmdContextFlag;
typedef struct CmdContext CmdContext;
typedef enum enumCmdContextHowCalled enumCmdContextHowCalled;
typedef struct CmdParseStructList CmdParseStructList;

#define	START_PACKET( pakx, e, cmd )														\
	if(entGetPlayer(e) && entGetNetLink(e))													\
	{																						\
		static PacketTracker *__pTracker;													\
		Packet* pakx;																		\
		Packet* pak_START_PACKET;															\
		ONCE(__pTracker = PacketTrackerFind("START_PACKET", 0, #cmd));						\
		if (!entGetPlayer(e)->msgPak)														\
		{																					\
			entGetPlayer(e)->msgPak = pktCreateWithTracker(entGetNetLink(e),TOCLIENT_GAME_MSG, __pTracker);		\
			/*pktSendBitsPack(entGetPlayer(e)->msgPak, 1, TOCLIENT_GAME_MSG);*/				\
			entSendRef(entGetPlayer(e)->msgPak, entGetRef(e));								\
		}																					\
		pakx = pak_START_PACKET = entGetPlayer(e)->msgPak;									\
		START_BIT_COUNT(pakx, #cmd);														\
		pktSendBits(pakx, 1, !!(cmd & LIB_MSG_BIT));										\
		pktSendBitsPack(pakx, GAME_MSG_SENDBITS, cmd & ~LIB_MSG_BIT);							


#define	END_PACKET STOP_BIT_COUNT(pak_START_PACKET);}

// Set a CSR listener, to which feedback will be forwarded
void gslSetCSRListener(Entity *e, GlobalType listenerType, ContainerID listenerID, const char *listenerName, const char *listenerAccount, U32 uSecondsToListen, AccessLevel listenerLevel);

// Sends a message to the CSR listener, if there is one
void gslSendCSRFeedback(Entity *ent, const char *string);

// Sends a printf to the specified client, which gets displayed with conPrintf
void gslSendPrintf( Entity* client, FORMAT_STR const char *fmt, ... );
#define gslSendPrintf(client, fmt, ...) gslSendPrintf(client, FORMAT_STRING_CHECKED(fmt), __VA_ARGS__)

// Returns an "unknown command" packet for a cmd executed from the Chat Window
void gslSendUnknownChatWindowCmd( Entity* client, const char *cmdString);

// Sends command strings to the specified client
// You should probably be using the AUTO_COMMAND wrappers instead
void gslSendPublicCommand( Entity *e, CmdContextFlag iFlags, const char *s, enumCmdContextHowCalled eHow, CmdParseStructList *pStructs);
void gslSendPrivateCommand( Entity *e, CmdContextFlag iFlags, const char *s, enumCmdContextHowCalled eHow, CmdParseStructList *pStructs);
void gslSendFastCommand( Entity *e, CmdContextFlag iFlags, const char *s, enumCmdContextHowCalled eHow, bool bPrivate, CmdParseStructList *pStructs);
void gslSendPublicCommandf(Entity *e, CmdContextFlag iFlags, FORMAT_STR const char *fmt, ...);
#define gslSendPublicCommandf(e, iFlags, fmt, ...) gslSendPublicCommandf(e, iFlags, FORMAT_STRING_CHECKED(fmt), __VA_ARGS__)
void gslSendPrivateCommandf(Entity *e, CmdContextFlag iFlags, FORMAT_STR const char *fmt, ...);
#define gslSendPrivateCommandf(e, iFlags, fmt, ...) gslSendPrivateCommandf(e, iFlags, FORMAT_STRING_CHECKED(fmt), __VA_ARGS__)

// I removed SendPrivateCommandToAll, to encourag people to use the autogenerated 
// command wrappers, in order to guarantee safety
// -BZ

// Login succeeded, continue the process
void gslSendLoginSuccess(ClientLink *link);

// Login failed, with the attached reason
void gslSendLoginFailure(ClientLink *cLink, const char * reason);

// Player needs to logout of the server
void gslSendForceLogout(ClientLink *cLink, const char * reason);

// The world changed, this is the update
void gslSendWorldUpdate(ClientLink *link, int full_update, bool bRecordSkyTime);

// Sends all general updates
void gslSendGeneralUpdates(void);

//containerID 0 means send to all
void gslBroadcastMessage(U32 iContainerID, char *pTitle, char *pMessage, CmdContext *context);

// Send a full update for the specified link
void gslQueueFullUpdateForLink(ClientLink *link);

#endif
