#if _PS3


#define _MATH_PERM_X  0,1,2,3
#define _MATH_PERM_Y  4,5,6,7
#define _MATH_PERM_Z  8,9,10,11
#define _MATH_PERM_W  12,13,14,15
#define _MATH_PERM_A  16,17,18,19
#define _MATH_PERM_B  20,21,22,23
#define _MATH_PERM_C  24,25,26,27
#define _MATH_PERM_D  28,29,30,31
#define _MATH_PERM_x  0,1,2,3			/* don't care, put x in ther for now */


#define __vzero()  ((vec_float4)(0.0f))
#define __vone()   ((vec_float4)(1.0f))
#define PLATFORMCAST_vec_float4(x) (vec_float4)(x)

#define GLOBALCONST static const

GLOBALCONST vec_uint4 _MATH_MASK_0xF000 = { 0xffffffff, 0, 0, 0 };
GLOBALCONST vec_uint4 _MATH_MASK_0x0F00 = { 0, 0xffffffff, 0, 0 };
GLOBALCONST vec_uint4 _MATH_MASK_0x00F0 = { 0, 0, 0xffffffff, 0 };
GLOBALCONST vec_uint4 _MATH_MASK_0x000F = { 0, 0, 0, 0xffffffff };

GLOBALCONST vec_float4 _MATH_UNIT_1000  = { 1.0f, 0.0f, 0.0f, 0.0f };
GLOBALCONST vec_float4 _MATH_UNIT_0100  = { 0.0f, 1.0f, 0.0f, 0.0f };
GLOBALCONST vec_float4 _MATH_UNIT_0010  = { 0.0f, 0.0f, 1.0f, 0.0f };
GLOBALCONST vec_float4 _MATH_UNIT_0001  = { 0.0f, 0.0f, 0.0f, 1.0f };
GLOBALCONST vec_float4 _MATH_UNIT_1111  = { 1.0f, 1.0f, 1.0f, 1.0f };

GLOBALCONST vec_uchar16 _MATH_PERM_WWWW = { _MATH_PERM_X, _MATH_PERM_Y, _MATH_PERM_A, _MATH_PERM_B };
GLOBALCONST vec_uchar16 _MATH_PERM_ZWCD = { _MATH_PERM_Z, _MATH_PERM_W, _MATH_PERM_C, _MATH_PERM_D };
GLOBALCONST vec_uchar16 _MATH_PERM_XZBX = { _MATH_PERM_X, _MATH_PERM_Z, _MATH_PERM_B, _MATH_PERM_X };
GLOBALCONST vec_uchar16 _MATH_PERM_CXXX = { _MATH_PERM_C, _MATH_PERM_X, _MATH_PERM_X, _MATH_PERM_X };
GLOBALCONST vec_uchar16 _MATH_PERM_YAXX = { _MATH_PERM_Y, _MATH_PERM_A, _MATH_PERM_X, _MATH_PERM_X };
GLOBALCONST vec_uchar16 _MATH_PERM_XAZC = { _MATH_PERM_X, _MATH_PERM_A, _MATH_PERM_Z, _MATH_PERM_C };
GLOBALCONST vec_uchar16 _MATH_PERM_YXWZ = { _MATH_PERM_Y, _MATH_PERM_X, _MATH_PERM_W, _MATH_PERM_Z };
GLOBALCONST vec_uchar16 _MATH_PERM_YBWD = { _MATH_PERM_Y, _MATH_PERM_B, _MATH_PERM_W, _MATH_PERM_D };

GLOBALCONST vec_uchar16 _MATH_PERM_XYZx = { _MATH_PERM_X, _MATH_PERM_Y, _MATH_PERM_Z, _MATH_PERM_x };
GLOBALCONST vec_uchar16 _MATH_PERM_WABx = { _MATH_PERM_W, _MATH_PERM_A, _MATH_PERM_B, _MATH_PERM_x };
GLOBALCONST vec_uchar16 _MATH_PERM_CDXx = { _MATH_PERM_C, _MATH_PERM_D, _MATH_PERM_X, _MATH_PERM_x };
GLOBALCONST vec_uchar16 _MATH_PERM_YZWx = { _MATH_PERM_Y, _MATH_PERM_Z, _MATH_PERM_W, _MATH_PERM_x };

GLOBALCONST vec_uchar16 _MATH_PERM_YZXx = { _MATH_PERM_Y, _MATH_PERM_Z, _MATH_PERM_X, _MATH_PERM_x };
GLOBALCONST vec_uchar16 _MATH_PERM_ZXYx = { _MATH_PERM_Z, _MATH_PERM_X, _MATH_PERM_Y, _MATH_PERM_x };

GLOBALCONST vec_uchar16 _MATH_PERM_YXXx = { _MATH_PERM_Y, _MATH_PERM_X, _MATH_PERM_X, _MATH_PERM_x };
GLOBALCONST vec_uchar16 _MATH_PERM_ZZYx = { _MATH_PERM_Z, _MATH_PERM_Z, _MATH_PERM_Y, _MATH_PERM_x };

GLOBALCONST vec_uchar16 _MATH_PERM_XYZA = { _MATH_PERM_X, _MATH_PERM_Y, _MATH_PERM_Z, _MATH_PERM_A };
GLOBALCONST vec_uchar16 _MATH_PERM_YZAB = { _MATH_PERM_Y, _MATH_PERM_Z, _MATH_PERM_A, _MATH_PERM_B };


#else
#if _XBOX
#define ShuffleWrap(i0, i1, i2, i3)	XMVectorPermuteControl(i3, i2, 4+i1, 4+i0)
#else
#define ShuffleWrap(i0, i1, i2, i3)	_MM_SHUFFLE( i0, i1, i2, i3 )
#endif

#define S_XXXX          ShuffleWrap( 0, 0, 0, 0 )
#define S_XXXY          ShuffleWrap( 1, 0, 0, 0 )
#define S_XXXZ          ShuffleWrap( 2, 0, 0, 0 )
#define S_XXXW          ShuffleWrap( 3, 0, 0, 0 )
#define S_XXYX          ShuffleWrap( 0, 1, 0, 0 )
#define S_XXYY          ShuffleWrap( 1, 1, 0, 0 )
#define S_XXYZ          ShuffleWrap( 2, 1, 0, 0 )
#define S_XXYW          ShuffleWrap( 3, 1, 0, 0 )
#define S_XXZX          ShuffleWrap( 0, 2, 0, 0 )
#define S_XXZY          ShuffleWrap( 1, 2, 0, 0 )
#define S_XXZZ          ShuffleWrap( 2, 2, 0, 0 )
#define S_XXZW          ShuffleWrap( 3, 2, 0, 0 )
#define S_XXWX          ShuffleWrap( 0, 3, 0, 0 )
#define S_XXWY          ShuffleWrap( 1, 3, 0, 0 )
#define S_XXWZ          ShuffleWrap( 2, 3, 0, 0 )
#define S_XXWW          ShuffleWrap( 3, 3, 0, 0 )
#define S_XYXX          ShuffleWrap( 0, 0, 1, 0 )
#define S_XYXY          ShuffleWrap( 1, 0, 1, 0 )
#define S_XYXZ          ShuffleWrap( 2, 0, 1, 0 )
#define S_XYXW          ShuffleWrap( 3, 0, 1, 0 )
#define S_XYYX          ShuffleWrap( 0, 1, 1, 0 )
#define S_XYYY          ShuffleWrap( 1, 1, 1, 0 )
#define S_XYYZ          ShuffleWrap( 2, 1, 1, 0 )
#define S_XYYW          ShuffleWrap( 3, 1, 1, 0 )
#define S_XYZX          ShuffleWrap( 0, 2, 1, 0 )
#define S_XYZY          ShuffleWrap( 1, 2, 1, 0 )
#define S_XYZZ          ShuffleWrap( 2, 2, 1, 0 )
#define S_XYZW          ShuffleWrap( 3, 2, 1, 0 )
#define S_XYWX          ShuffleWrap( 0, 3, 1, 0 )
#define S_XYWY          ShuffleWrap( 1, 3, 1, 0 )
#define S_XYWZ          ShuffleWrap( 2, 3, 1, 0 )
#define S_XYWW          ShuffleWrap( 3, 3, 1, 0 )
#define S_XZXX          ShuffleWrap( 0, 0, 2, 0 )
#define S_XZXY          ShuffleWrap( 1, 0, 2, 0 )
#define S_XZXZ          ShuffleWrap( 2, 0, 2, 0 )
#define S_XZXW          ShuffleWrap( 3, 0, 2, 0 )
#define S_XZYX          ShuffleWrap( 0, 1, 2, 0 )
#define S_XZYY          ShuffleWrap( 1, 1, 2, 0 )
#define S_XZYZ          ShuffleWrap( 2, 1, 2, 0 )
#define S_XZYW          ShuffleWrap( 3, 1, 2, 0 )
#define S_XZZX          ShuffleWrap( 0, 2, 2, 0 )
#define S_XZZY          ShuffleWrap( 1, 2, 2, 0 )
#define S_XZZZ          ShuffleWrap( 2, 2, 2, 0 )
#define S_XZZW          ShuffleWrap( 3, 2, 2, 0 )
#define S_XZWX          ShuffleWrap( 0, 3, 2, 0 )
#define S_XZWY          ShuffleWrap( 1, 3, 2, 0 )
#define S_XZWZ          ShuffleWrap( 2, 3, 2, 0 )
#define S_XZWW          ShuffleWrap( 3, 3, 2, 0 )
#define S_XWXX          ShuffleWrap( 0, 0, 3, 0 )
#define S_XWXY          ShuffleWrap( 1, 0, 3, 0 )
#define S_XWXZ          ShuffleWrap( 2, 0, 3, 0 )
#define S_XWXW          ShuffleWrap( 3, 0, 3, 0 )
#define S_XWYX          ShuffleWrap( 0, 1, 3, 0 )
#define S_XWYY          ShuffleWrap( 1, 1, 3, 0 )
#define S_XWYZ          ShuffleWrap( 2, 1, 3, 0 )
#define S_XWYW          ShuffleWrap( 3, 1, 3, 0 )
#define S_XWZX          ShuffleWrap( 0, 2, 3, 0 )
#define S_XWZY          ShuffleWrap( 1, 2, 3, 0 )
#define S_XWZZ          ShuffleWrap( 2, 2, 3, 0 )
#define S_XWZW          ShuffleWrap( 3, 2, 3, 0 )
#define S_XWWX          ShuffleWrap( 0, 3, 3, 0 )
#define S_XWWY          ShuffleWrap( 1, 3, 3, 0 )
#define S_XWWZ          ShuffleWrap( 2, 3, 3, 0 )
#define S_XWWW          ShuffleWrap( 3, 3, 3, 0 )
#define S_YXXX          ShuffleWrap( 0, 0, 0, 1 )
#define S_YXXY          ShuffleWrap( 1, 0, 0, 1 )
#define S_YXXZ          ShuffleWrap( 2, 0, 0, 1 )
#define S_YXXW          ShuffleWrap( 3, 0, 0, 1 )
#define S_YXYX          ShuffleWrap( 0, 1, 0, 1 )
#define S_YXYY          ShuffleWrap( 1, 1, 0, 1 )
#define S_YXYZ          ShuffleWrap( 2, 1, 0, 1 )
#define S_YXYW          ShuffleWrap( 3, 1, 0, 1 )
#define S_YXZX          ShuffleWrap( 0, 2, 0, 1 )
#define S_YXZY          ShuffleWrap( 1, 2, 0, 1 )
#define S_YXZZ          ShuffleWrap( 2, 2, 0, 1 )
#define S_YXZW          ShuffleWrap( 3, 2, 0, 1 )
#define S_YXWX          ShuffleWrap( 0, 3, 0, 1 )
#define S_YXWY          ShuffleWrap( 1, 3, 0, 1 )
#define S_YXWZ          ShuffleWrap( 2, 3, 0, 1 )
#define S_YXWW          ShuffleWrap( 3, 3, 0, 1 )
#define S_YYXX          ShuffleWrap( 0, 0, 1, 1 )
#define S_YYXY          ShuffleWrap( 1, 0, 1, 1 )
#define S_YYXZ          ShuffleWrap( 2, 0, 1, 1 )
#define S_YYXW          ShuffleWrap( 3, 0, 1, 1 )
#define S_YYYX          ShuffleWrap( 0, 1, 1, 1 )
#define S_YYYY          ShuffleWrap( 1, 1, 1, 1 )
#define S_YYYZ          ShuffleWrap( 2, 1, 1, 1 )
#define S_YYYW          ShuffleWrap( 3, 1, 1, 1 )
#define S_YYZX          ShuffleWrap( 0, 2, 1, 1 )
#define S_YYZY          ShuffleWrap( 1, 2, 1, 1 )
#define S_YYZZ          ShuffleWrap( 2, 2, 1, 1 )
#define S_YYZW          ShuffleWrap( 3, 2, 1, 1 )
#define S_YYWX          ShuffleWrap( 0, 3, 1, 1 )
#define S_YYWY          ShuffleWrap( 1, 3, 1, 1 )
#define S_YYWZ          ShuffleWrap( 2, 3, 1, 1 )
#define S_YYWW          ShuffleWrap( 3, 3, 1, 1 )
#define S_YZXX          ShuffleWrap( 0, 0, 2, 1 )
#define S_YZXY          ShuffleWrap( 1, 0, 2, 1 )
#define S_YZXZ          ShuffleWrap( 2, 0, 2, 1 )
#define S_YZXW          ShuffleWrap( 3, 0, 2, 1 )
#define S_YZYX          ShuffleWrap( 0, 1, 2, 1 )
#define S_YZYY          ShuffleWrap( 1, 1, 2, 1 )
#define S_YZYZ          ShuffleWrap( 2, 1, 2, 1 )
#define S_YZYW          ShuffleWrap( 3, 1, 2, 1 )
#define S_YZZX          ShuffleWrap( 0, 2, 2, 1 )
#define S_YZZY          ShuffleWrap( 1, 2, 2, 1 )
#define S_YZZZ          ShuffleWrap( 2, 2, 2, 1 )
#define S_YZZW          ShuffleWrap( 3, 2, 2, 1 )
#define S_YZWX          ShuffleWrap( 0, 3, 2, 1 )
#define S_YZWY          ShuffleWrap( 1, 3, 2, 1 )
#define S_YZWZ          ShuffleWrap( 2, 3, 2, 1 )
#define S_YZWW          ShuffleWrap( 3, 3, 2, 1 )
#define S_YWXX          ShuffleWrap( 0, 0, 3, 1 )
#define S_YWXY          ShuffleWrap( 1, 0, 3, 1 )
#define S_YWXZ          ShuffleWrap( 2, 0, 3, 1 )
#define S_YWXW          ShuffleWrap( 3, 0, 3, 1 )
#define S_YWYX          ShuffleWrap( 0, 1, 3, 1 )
#define S_YWYY          ShuffleWrap( 1, 1, 3, 1 )
#define S_YWYZ          ShuffleWrap( 2, 1, 3, 1 )
#define S_YWYW          ShuffleWrap( 3, 1, 3, 1 )
#define S_YWZX          ShuffleWrap( 0, 2, 3, 1 )
#define S_YWZY          ShuffleWrap( 1, 2, 3, 1 )
#define S_YWZZ          ShuffleWrap( 2, 2, 3, 1 )
#define S_YWZW          ShuffleWrap( 3, 2, 3, 1 )
#define S_YWWX          ShuffleWrap( 0, 3, 3, 1 )
#define S_YWWY          ShuffleWrap( 1, 3, 3, 1 )
#define S_YWWZ          ShuffleWrap( 2, 3, 3, 1 )
#define S_YWWW          ShuffleWrap( 3, 3, 3, 1 )
#define S_ZXXX          ShuffleWrap( 0, 0, 0, 2 )
#define S_ZXXY          ShuffleWrap( 1, 0, 0, 2 )
#define S_ZXXZ          ShuffleWrap( 2, 0, 0, 2 )
#define S_ZXXW          ShuffleWrap( 3, 0, 0, 2 )
#define S_ZXYX          ShuffleWrap( 0, 1, 0, 2 )
#define S_ZXYY          ShuffleWrap( 1, 1, 0, 2 )
#define S_ZXYZ          ShuffleWrap( 2, 1, 0, 2 )
#define S_ZXYW          ShuffleWrap( 3, 1, 0, 2 )
#define S_ZXZX          ShuffleWrap( 0, 2, 0, 2 )
#define S_ZXZY          ShuffleWrap( 1, 2, 0, 2 )
#define S_ZXZZ          ShuffleWrap( 2, 2, 0, 2 )
#define S_ZXZW          ShuffleWrap( 3, 2, 0, 2 )
#define S_ZXWX          ShuffleWrap( 0, 3, 0, 2 )
#define S_ZXWY          ShuffleWrap( 1, 3, 0, 2 )
#define S_ZXWZ          ShuffleWrap( 2, 3, 0, 2 )
#define S_ZXWW          ShuffleWrap( 3, 3, 0, 2 )
#define S_ZYXX          ShuffleWrap( 0, 0, 1, 2 )
#define S_ZYXY          ShuffleWrap( 1, 0, 1, 2 )
#define S_ZYXZ          ShuffleWrap( 2, 0, 1, 2 )
#define S_ZYXW          ShuffleWrap( 3, 0, 1, 2 )
#define S_ZYYX          ShuffleWrap( 0, 1, 1, 2 )
#define S_ZYYY          ShuffleWrap( 1, 1, 1, 2 )
#define S_ZYYZ          ShuffleWrap( 2, 1, 1, 2 )
#define S_ZYYW          ShuffleWrap( 3, 1, 1, 2 )
#define S_ZYZX          ShuffleWrap( 0, 2, 1, 2 )
#define S_ZYZY          ShuffleWrap( 1, 2, 1, 2 )
#define S_ZYZZ          ShuffleWrap( 2, 2, 1, 2 )
#define S_ZYZW          ShuffleWrap( 3, 2, 1, 2 )
#define S_ZYWX          ShuffleWrap( 0, 3, 1, 2 )
#define S_ZYWY          ShuffleWrap( 1, 3, 1, 2 )
#define S_ZYWZ          ShuffleWrap( 2, 3, 1, 2 )
#define S_ZYWW          ShuffleWrap( 3, 3, 1, 2 )
#define S_ZZXX          ShuffleWrap( 0, 0, 2, 2 )
#define S_ZZXY          ShuffleWrap( 1, 0, 2, 2 )
#define S_ZZXZ          ShuffleWrap( 2, 0, 2, 2 )
#define S_ZZXW          ShuffleWrap( 3, 0, 2, 2 )
#define S_ZZYX          ShuffleWrap( 0, 1, 2, 2 )
#define S_ZZYY          ShuffleWrap( 1, 1, 2, 2 )
#define S_ZZYZ          ShuffleWrap( 2, 1, 2, 2 )
#define S_ZZYW          ShuffleWrap( 3, 1, 2, 2 )
#define S_ZZZX          ShuffleWrap( 0, 2, 2, 2 )
#define S_ZZZY          ShuffleWrap( 1, 2, 2, 2 )
#define S_ZZZZ          ShuffleWrap( 2, 2, 2, 2 )
#define S_ZZZW          ShuffleWrap( 3, 2, 2, 2 )
#define S_ZZWX          ShuffleWrap( 0, 3, 2, 2 )
#define S_ZZWY          ShuffleWrap( 1, 3, 2, 2 )
#define S_ZZWZ          ShuffleWrap( 2, 3, 2, 2 )
#define S_ZZWW          ShuffleWrap( 3, 3, 2, 2 )
#define S_ZWXX          ShuffleWrap( 0, 0, 3, 2 )
#define S_ZWXY          ShuffleWrap( 1, 0, 3, 2 )
#define S_ZWXZ          ShuffleWrap( 2, 0, 3, 2 )
#define S_ZWXW          ShuffleWrap( 3, 0, 3, 2 )
#define S_ZWYX          ShuffleWrap( 0, 1, 3, 2 )
#define S_ZWYY          ShuffleWrap( 1, 1, 3, 2 )
#define S_ZWYZ          ShuffleWrap( 2, 1, 3, 2 )
#define S_ZWYW          ShuffleWrap( 3, 1, 3, 2 )
#define S_ZWZX          ShuffleWrap( 0, 2, 3, 2 )
#define S_ZWZY          ShuffleWrap( 1, 2, 3, 2 )
#define S_ZWZZ          ShuffleWrap( 2, 2, 3, 2 )
#define S_ZWZW          ShuffleWrap( 3, 2, 3, 2 )
#define S_ZWWX          ShuffleWrap( 0, 3, 3, 2 )
#define S_ZWWY          ShuffleWrap( 1, 3, 3, 2 )
#define S_ZWWZ          ShuffleWrap( 2, 3, 3, 2 )
#define S_ZWWW          ShuffleWrap( 3, 3, 3, 2 )
#define S_WXXX          ShuffleWrap( 0, 0, 0, 3 )
#define S_WXXY          ShuffleWrap( 1, 0, 0, 3 )
#define S_WXXZ          ShuffleWrap( 2, 0, 0, 3 )
#define S_WXXW          ShuffleWrap( 3, 0, 0, 3 )
#define S_WXYX          ShuffleWrap( 0, 1, 0, 3 )
#define S_WXYY          ShuffleWrap( 1, 1, 0, 3 )
#define S_WXYZ          ShuffleWrap( 2, 1, 0, 3 )
#define S_WXYW          ShuffleWrap( 3, 1, 0, 3 )
#define S_WXZX          ShuffleWrap( 0, 2, 0, 3 )
#define S_WXZY          ShuffleWrap( 1, 2, 0, 3 )
#define S_WXZZ          ShuffleWrap( 2, 2, 0, 3 )
#define S_WXZW          ShuffleWrap( 3, 2, 0, 3 )
#define S_WXWX          ShuffleWrap( 0, 3, 0, 3 )
#define S_WXWY          ShuffleWrap( 1, 3, 0, 3 )
#define S_WXWZ          ShuffleWrap( 2, 3, 0, 3 )
#define S_WXWW          ShuffleWrap( 3, 3, 0, 3 )
#define S_WYXX          ShuffleWrap( 0, 0, 1, 3 )
#define S_WYXY          ShuffleWrap( 1, 0, 1, 3 )
#define S_WYXZ          ShuffleWrap( 2, 0, 1, 3 )
#define S_WYXW          ShuffleWrap( 3, 0, 1, 3 )
#define S_WYYX          ShuffleWrap( 0, 1, 1, 3 )
#define S_WYYY          ShuffleWrap( 1, 1, 1, 3 )
#define S_WYYZ          ShuffleWrap( 2, 1, 1, 3 )
#define S_WYYW          ShuffleWrap( 3, 1, 1, 3 )
#define S_WYZX          ShuffleWrap( 0, 2, 1, 3 )
#define S_WYZY          ShuffleWrap( 1, 2, 1, 3 )
#define S_WYZZ          ShuffleWrap( 2, 2, 1, 3 )
#define S_WYZW          ShuffleWrap( 3, 2, 1, 3 )
#define S_WYWX          ShuffleWrap( 0, 3, 1, 3 )
#define S_WYWY          ShuffleWrap( 1, 3, 1, 3 )
#define S_WYWZ          ShuffleWrap( 2, 3, 1, 3 )
#define S_WYWW          ShuffleWrap( 3, 3, 1, 3 )
#define S_WZXX          ShuffleWrap( 0, 0, 2, 3 )
#define S_WZXY          ShuffleWrap( 1, 0, 2, 3 )
#define S_WZXZ          ShuffleWrap( 2, 0, 2, 3 )
#define S_WZXW          ShuffleWrap( 3, 0, 2, 3 )
#define S_WZYX          ShuffleWrap( 0, 1, 2, 3 )
#define S_WZYY          ShuffleWrap( 1, 1, 2, 3 )
#define S_WZYZ          ShuffleWrap( 2, 1, 2, 3 )
#define S_WZYW          ShuffleWrap( 3, 1, 2, 3 )
#define S_WZZX          ShuffleWrap( 0, 2, 2, 3 )
#define S_WZZY          ShuffleWrap( 1, 2, 2, 3 )
#define S_WZZZ          ShuffleWrap( 2, 2, 2, 3 )
#define S_WZZW          ShuffleWrap( 3, 2, 2, 3 )
#define S_WZWX          ShuffleWrap( 0, 3, 2, 3 )
#define S_WZWY          ShuffleWrap( 1, 3, 2, 3 )
#define S_WZWZ          ShuffleWrap( 2, 3, 2, 3 )
#define S_WZWW          ShuffleWrap( 3, 3, 2, 3 )
#define S_WWXX          ShuffleWrap( 0, 0, 3, 3 )
#define S_WWXY          ShuffleWrap( 1, 0, 3, 3 )
#define S_WWXZ          ShuffleWrap( 2, 0, 3, 3 )
#define S_WWXW          ShuffleWrap( 3, 0, 3, 3 )
#define S_WWYX          ShuffleWrap( 0, 1, 3, 3 )
#define S_WWYY          ShuffleWrap( 1, 1, 3, 3 )
#define S_WWYZ          ShuffleWrap( 2, 1, 3, 3 )
#define S_WWYW          ShuffleWrap( 3, 1, 3, 3 )
#define S_WWZX          ShuffleWrap( 0, 2, 3, 3 )
#define S_WWZY          ShuffleWrap( 1, 2, 3, 3 )
#define S_WWZZ          ShuffleWrap( 2, 2, 3, 3 )
#define S_WWZW          ShuffleWrap( 3, 2, 3, 3 )
#define S_WWWX          ShuffleWrap( 0, 3, 3, 3 )
#define S_WWWY          ShuffleWrap( 1, 3, 3, 3 )
#define S_WWWZ          ShuffleWrap( 2, 3, 3, 3 )
#define S_WWWW          ShuffleWrap( 3, 3, 3, 3 )

#endif
