#pragma once

#define PROCESSOR_ANY 					-1
#define PROCESSOR_0_0 					0 // CPU 0 HT 0
#define PROCESSOR_0_1 					1 // CPU 0 HT 1
#define PROCESSOR_1_0 					2 // CPU 1 HT 0
#define PROCESSOR_1_1 					3 // CPU 1 HT 1
#define PROCESSOR_2_0 					4 // CPU 2 HT 0
#define PROCESSOR_2_1 					5 // CPU 2 HT 1


#define THREADINDEX_MAIN 				PROCESSOR_0_0
#define THREADINDEX_RENDER				PROCESSOR_1_0

#ifdef _XBOX

	#define THREADINDEX_DATASTREAMING	PROCESSOR_2_0 // AUDIO driver runs on this w/ ultra high priority, so don't put anything not interruptible here

	#define THREADINDEX_MISC			PROCESSOR_2_1
	#define THREADINDEX_WORLDCOLL		PROCESSOR_2_1
	#define THREADINDEX_MUTEX			PROCESSOR_2_1
	#define THREADINDEX_LOGWRITER		PROCESSOR_2_1
	#define THREADINDEX_NETSEND			PROCESSOR_2_1
	#define THREADINDEX_ERRORSEND		PROCESSOR_2_1
	#define THREADINDEX_ZOCCLUSION		PROCESSOR_2_1
	#define THREADINDEX_PHYSX_COOKER	PROCESSOR_2_1

#define THREAD_MASK(i) (1 << (i))
	// Currently using 2nd 2 CPUs, both threads, can remove from 1_0 if we ever get RenderThread bound again
	#define THREADMASK_PHYSX			(THREAD_MASK(PROCESSOR_1_0)|THREAD_MASK(PROCESSOR_1_1)|THREAD_MASK(PROCESSOR_2_0)|THREAD_MASK(PROCESSOR_2_1))

	#define THREADINDEX_ANIMTHREAD_0 	PROCESSOR_0_1
	#define THREADINDEX_ANIMTHREAD_1 	PROCESSOR_2_1

	// Currently not using these three by default
	#define THREADINDEX_ANIMTHREAD_2 	PROCESSOR_2_0 // dangerous because this is the audio core
	#define THREADINDEX_ANIMTHREAD_3 	PROCESSOR_0_1
	#define THREADINDEX_ANIMTHREAD_4 	PROCESSOR_0_1

#else

	#define THREADINDEX_DATASTREAMING	PROCESSOR_ANY

	#define THREADINDEX_MISC			PROCESSOR_ANY 
	#define THREADINDEX_WORLDCOLL		PROCESSOR_ANY
	#define THREADINDEX_MUTEX			PROCESSOR_ANY
	#define THREADINDEX_LOGWRITER		PROCESSOR_ANY
	#define THREADINDEX_NETSEND			PROCESSOR_ANY
	#define THREADINDEX_ERRORSEND		PROCESSOR_ANY
	#define THREADINDEX_ZOCCLUSION		PROCESSOR_ANY
	#define THREADINDEX_PHYSX_COOKER	PROCESSOR_ANY


	#define THREADINDEX_ANIMTHREAD_0 	PROCESSOR_ANY
	#define THREADINDEX_ANIMTHREAD_1 	PROCESSOR_ANY

	// Currently not using these three by default
	#define THREADINDEX_ANIMTHREAD_2 	PROCESSOR_ANY
	#define THREADINDEX_ANIMTHREAD_3 	PROCESSOR_ANY
	#define THREADINDEX_ANIMTHREAD_4 	PROCESSOR_ANY

#endif
