#ifndef __LOCALTRANSACTIONMANAGER_C_AST_H_
#define __LOCALTRANSACTIONMANAGER_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \LocalTransactionManager.c
//autogeneratednocheckin

extern ParseTable parse_HandleTransactionTracker[];
#define TYPE_parse_HandleTransactionTracker HandleTransactionTracker

extern ParseTable parse_SimpleRemoteCommandTracker[];
#define TYPE_parse_SimpleRemoteCommandTracker SimpleRemoteCommandTracker

#endif
