#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct TestingContainer
#define TYPE_parse_TestingContainer TestingContainer
ParseTable parse_TestingContainer[] =
{
	{ "TestingContainer", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(TestingContainer), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "uID",				TOK_PERSIST | TOK_KEY | TOK_AUTOINT(TestingContainer, uID, 0), NULL },
	{ "array",				TOK_PERSIST | TOK_INTARRAY(TestingContainer, array),  NULL},
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_TestingContainer()
{
	int iSize = sizeof(TestingContainer);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_TestingContainer, iSize, "TestingContainer", NULL, "objTesting.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
