//This file contains data and prototypes for latelinks. It is autogenerated by StructParser

//autogeneratednocheckin
#include "LateLinkSupport.h"

//Stuff relating to DEFAULT_LATELINK_AttemptToBootPlayerWithBooter(), defined in I:\Night\Night\src\libs\ServerLib\PlayerBooter.c
extern void DEFAULT_LATELINK_AttemptToBootPlayerWithBooter(ContainerID arg0, U32 arg1, void* arg2);
typedef void AttemptToBootPlayerWithBooter_LATELINK_FPTYPE_INTERNAL(ContainerID arg0, U32 arg1, void* arg2);
AttemptToBootPlayerWithBooter_LATELINK_FPTYPE_INTERNAL *AttemptToBootPlayerWithBooter_LATELINK_FP = NULL;
char *AttemptToBootPlayerWithBooter_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_AttemptToBootPlayerWithBooter(void)
{
	AttemptToBootPlayerWithBooter_LATELINK_FP = DEFAULT_LATELINK_AttemptToBootPlayerWithBooter;
	TestLateLinkArgString(&AttemptToBootPlayerWithBooter_LATELINK_ARGSTRING, "void ContainerID U32 char * ", "AttemptToBootPlayerWithBooter");
}
void AttemptToBootPlayerWithBooter(ContainerID arg0, U32 arg1, void* arg2)
{
	AttemptToBootPlayerWithBooter_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for AttemptToBootPlayerWithBooter(), defined in I:\Night\Night\src\libs\ServerLib\pub\PlayerBooter.h
extern char *AttemptToBootPlayerWithBooter_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__PlayerBooter_h_ServerLib_0_AttemptToBootPlayerWithBooter(void)
{
	TestLateLinkArgString(&AttemptToBootPlayerWithBooter_LATELINK_ARGSTRING, "void ContainerID U32 char * ", "AttemptToBootPlayerWithBooter");
}

//Stuff relating to LATELINK_OVERRIDE_AutoSetting_CmdWasCalled(), defined in I:\Night\Night\src\libs\ServerLib\AutoSettings.c
extern void OVERRIDE_LATELINK_AutoSetting_CmdWasCalled(void* arg0, enumCmdContextHowCalled arg1, void* arg2);
typedef void AutoSetting_CmdWasCalled_LATELINK_FPTYPE_INTERNAL(void* arg0, enumCmdContextHowCalled arg1, void* arg2);
extern AutoSetting_CmdWasCalled_LATELINK_FPTYPE_INTERNAL *AutoSetting_CmdWasCalled_LATELINK_FP;
extern char *AutoSetting_CmdWasCalled_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_AutoSetting_CmdWasCalled(void)
{
	AutoSetting_CmdWasCalled_LATELINK_FP = OVERRIDE_LATELINK_AutoSetting_CmdWasCalled;
	TestLateLinkArgString(&AutoSetting_CmdWasCalled_LATELINK_ARGSTRING, "void const Cmd * enumCmdContextHowCalled const char * ", "AutoSetting_CmdWasCalled");
}

//Stuff relating to LATELINK_OVERRIDE_AutoSetting_PacketOfCommandsFromController(), defined in I:\Night\Night\src\libs\ServerLib\AutoSettings.c
extern void OVERRIDE_LATELINK_AutoSetting_PacketOfCommandsFromController(void* arg0);
typedef void AutoSetting_PacketOfCommandsFromController_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern AutoSetting_PacketOfCommandsFromController_LATELINK_FPTYPE_INTERNAL *AutoSetting_PacketOfCommandsFromController_LATELINK_FP;
extern char *AutoSetting_PacketOfCommandsFromController_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_AutoSetting_PacketOfCommandsFromController(void)
{
	AutoSetting_PacketOfCommandsFromController_LATELINK_FP = OVERRIDE_LATELINK_AutoSetting_PacketOfCommandsFromController;
	TestLateLinkArgString(&AutoSetting_PacketOfCommandsFromController_LATELINK_ARGSTRING, "void Packet * ", "AutoSetting_PacketOfCommandsFromController");
}

//Stuff relating to LATELINK_OVERRIDE_ConnectedToController_ServerSpecificStuff(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void OVERRIDE_LATELINK_ConnectedToController_ServerSpecificStuff(void);
typedef void ConnectedToController_ServerSpecificStuff_LATELINK_FPTYPE_INTERNAL(void);
extern ConnectedToController_ServerSpecificStuff_LATELINK_FPTYPE_INTERNAL *ConnectedToController_ServerSpecificStuff_LATELINK_FP;
extern char *ConnectedToController_ServerSpecificStuff_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ConnectedToController_ServerSpecificStuff(void)
{
	ConnectedToController_ServerSpecificStuff_LATELINK_FP = OVERRIDE_LATELINK_ConnectedToController_ServerSpecificStuff;
	TestLateLinkArgString(&ConnectedToController_ServerSpecificStuff_LATELINK_ARGSTRING, "void ", "ConnectedToController_ServerSpecificStuff");
}

//Stuff relating to LATELINK_OVERRIDE_ControllerScript_Failed(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void OVERRIDE_LATELINK_ControllerScript_Failed(void* arg0);
typedef void ControllerScript_Failed_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern ControllerScript_Failed_LATELINK_FPTYPE_INTERNAL *ControllerScript_Failed_LATELINK_FP;
extern char *ControllerScript_Failed_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ControllerScript_Failed(void)
{
	ControllerScript_Failed_LATELINK_FP = OVERRIDE_LATELINK_ControllerScript_Failed;
	TestLateLinkArgString(&ControllerScript_Failed_LATELINK_ARGSTRING, "void char * ", "ControllerScript_Failed");
}

//Stuff relating to LATELINK_OVERRIDE_ControllerScript_Succeeded(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void OVERRIDE_LATELINK_ControllerScript_Succeeded(void);
typedef void ControllerScript_Succeeded_LATELINK_FPTYPE_INTERNAL(void);
extern ControllerScript_Succeeded_LATELINK_FPTYPE_INTERNAL *ControllerScript_Succeeded_LATELINK_FP;
extern char *ControllerScript_Succeeded_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ControllerScript_Succeeded(void)
{
	ControllerScript_Succeeded_LATELINK_FP = OVERRIDE_LATELINK_ControllerScript_Succeeded;
	TestLateLinkArgString(&ControllerScript_Succeeded_LATELINK_ARGSTRING, "void ", "ControllerScript_Succeeded");
}

//Stuff relating to DEFAULT_LATELINK_DoYouOwnContainerReturn_Internal(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_DoYouOwnContainerReturn_Internal(int arg0, bool arg1, bool arg2);
typedef void DoYouOwnContainerReturn_Internal_LATELINK_FPTYPE_INTERNAL(int arg0, bool arg1, bool arg2);
DoYouOwnContainerReturn_Internal_LATELINK_FPTYPE_INTERNAL *DoYouOwnContainerReturn_Internal_LATELINK_FP = NULL;
char *DoYouOwnContainerReturn_Internal_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_DoYouOwnContainerReturn_Internal(void)
{
	DoYouOwnContainerReturn_Internal_LATELINK_FP = DEFAULT_LATELINK_DoYouOwnContainerReturn_Internal;
	TestLateLinkArgString(&DoYouOwnContainerReturn_Internal_LATELINK_ARGSTRING, "void int bool bool ", "DoYouOwnContainerReturn_Internal");
}
void DoYouOwnContainerReturn_Internal(int arg0, bool arg1, bool arg2)
{
	DoYouOwnContainerReturn_Internal_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for DoYouOwnContainerReturn_Internal(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *DoYouOwnContainerReturn_Internal_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_5_DoYouOwnContainerReturn_Internal(void)
{
	TestLateLinkArgString(&DoYouOwnContainerReturn_Internal_LATELINK_ARGSTRING, "void int bool bool ", "DoYouOwnContainerReturn_Internal");
}

//Stuff relating to DEFAULT_LATELINK_GatewayNotifyLockStatus(), defined in I:\Night\Night\src\libs\ServerLib\GatewayUtil.c
extern void DEFAULT_LATELINK_GatewayNotifyLockStatus(bool arg0);
typedef void GatewayNotifyLockStatus_LATELINK_FPTYPE_INTERNAL(bool arg0);
GatewayNotifyLockStatus_LATELINK_FPTYPE_INTERNAL *GatewayNotifyLockStatus_LATELINK_FP = NULL;
char *GatewayNotifyLockStatus_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_GatewayNotifyLockStatus(void)
{
	GatewayNotifyLockStatus_LATELINK_FP = DEFAULT_LATELINK_GatewayNotifyLockStatus;
	TestLateLinkArgString(&GatewayNotifyLockStatus_LATELINK_ARGSTRING, "void bool ", "GatewayNotifyLockStatus");
}
void GatewayNotifyLockStatus(bool arg0)
{
	GatewayNotifyLockStatus_LATELINK_FP(arg0);
}

//Stuff relating to LATELINK declaration for GatewayNotifyLockStatus(), defined in I:\Night\Night\src\libs\ServerLib\pub\GatewayUtil.h
extern char *GatewayNotifyLockStatus_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GatewayUtil_h_ServerLib_0_GatewayNotifyLockStatus(void)
{
	TestLateLinkArgString(&GatewayNotifyLockStatus_LATELINK_ARGSTRING, "void bool ", "GatewayNotifyLockStatus");
}

//Stuff relating to LATELINK_OVERRIDE_GetAntiZombificationCookie(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern U32 OVERRIDE_LATELINK_GetAntiZombificationCookie(void);
typedef U32 GetAntiZombificationCookie_LATELINK_FPTYPE_INTERNAL(void);
extern GetAntiZombificationCookie_LATELINK_FPTYPE_INTERNAL *GetAntiZombificationCookie_LATELINK_FP;
extern char *GetAntiZombificationCookie_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetAntiZombificationCookie(void)
{
	GetAntiZombificationCookie_LATELINK_FP = OVERRIDE_LATELINK_GetAntiZombificationCookie;
	TestLateLinkArgString(&GetAntiZombificationCookie_LATELINK_ARGSTRING, "U32 ", "GetAntiZombificationCookie");
}

//Stuff relating to LATELINK declaration for GetAppGlobalID(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h
extern char *GetAppGlobalID_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_ServerLib_0_GetAppGlobalID(void)
{
	TestLateLinkArgString(&GetAppGlobalID_LATELINK_ARGSTRING, "U32 ", "GetAppGlobalID");
}

//Stuff relating to LATELINK_OVERRIDE_GetAppGlobalID(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern U32 OVERRIDE_LATELINK_GetAppGlobalID(void);
typedef U32 GetAppGlobalID_LATELINK_FPTYPE_INTERNAL(void);
extern GetAppGlobalID_LATELINK_FPTYPE_INTERNAL *GetAppGlobalID_LATELINK_FP;
extern char *GetAppGlobalID_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetAppGlobalID(void)
{
	GetAppGlobalID_LATELINK_FP = OVERRIDE_LATELINK_GetAppGlobalID;
	TestLateLinkArgString(&GetAppGlobalID_LATELINK_ARGSTRING, "U32 ", "GetAppGlobalID");
}

//Stuff relating to LATELINK declaration for GetAppIDStr(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h
extern char *GetAppIDStr_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_ServerLib_1_GetAppIDStr(void)
{
	TestLateLinkArgString(&GetAppIDStr_LATELINK_ARGSTRING, "void * ", "GetAppIDStr");
}

//Stuff relating to LATELINK_OVERRIDE_GetAppIDStr(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void* OVERRIDE_LATELINK_GetAppIDStr(void);
typedef void* GetAppIDStr_LATELINK_FPTYPE_INTERNAL(void);
extern GetAppIDStr_LATELINK_FPTYPE_INTERNAL *GetAppIDStr_LATELINK_FP;
extern char *GetAppIDStr_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetAppIDStr(void)
{
	GetAppIDStr_LATELINK_FP = OVERRIDE_LATELINK_GetAppIDStr;
	TestLateLinkArgString(&GetAppIDStr_LATELINK_ARGSTRING, "void * ", "GetAppIDStr");
}

//Stuff relating to LATELINK declaration for GetCommandsForGenericServerMonitoringPage(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h
extern char *GetCommandsForGenericServerMonitoringPage_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__HttpXpathSupport_h_ServerLib_4_GetCommandsForGenericServerMonitoringPage(void)
{
	TestLateLinkArgString(&GetCommandsForGenericServerMonitoringPage_LATELINK_ARGSTRING, "void GenericServerInfoForHttpXpath * ", "GetCommandsForGenericServerMonitoringPage");
}

//Stuff relating to LATELINK_OVERRIDE_GetControllerHost(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void* OVERRIDE_LATELINK_GetControllerHost(void);
typedef void* GetControllerHost_LATELINK_FPTYPE_INTERNAL(void);
extern GetControllerHost_LATELINK_FPTYPE_INTERNAL *GetControllerHost_LATELINK_FP;
extern char *GetControllerHost_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetControllerHost(void)
{
	GetControllerHost_LATELINK_FP = OVERRIDE_LATELINK_GetControllerHost;
	TestLateLinkArgString(&GetControllerHost_LATELINK_ARGSTRING, "char * ", "GetControllerHost");
}

//Stuff relating to DEFAULT_LATELINK_GetControllerTrackerHost(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void* DEFAULT_LATELINK_GetControllerTrackerHost(void);
typedef void* GetControllerTrackerHost_LATELINK_FPTYPE_INTERNAL(void);
GetControllerTrackerHost_LATELINK_FPTYPE_INTERNAL *GetControllerTrackerHost_LATELINK_FP = NULL;
char *GetControllerTrackerHost_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_GetControllerTrackerHost(void)
{
	GetControllerTrackerHost_LATELINK_FP = DEFAULT_LATELINK_GetControllerTrackerHost;
	TestLateLinkArgString(&GetControllerTrackerHost_LATELINK_ARGSTRING, "char * ", "GetControllerTrackerHost");
}
void* GetControllerTrackerHost(void)
{
	return GetControllerTrackerHost_LATELINK_FP();
}

//Stuff relating to LATELINK declaration for GetControllerTrackerHost(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *GetControllerTrackerHost_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_10_GetControllerTrackerHost(void)
{
	TestLateLinkArgString(&GetControllerTrackerHost_LATELINK_ARGSTRING, "char * ", "GetControllerTrackerHost");
}

//Stuff relating to LATELINK declaration for GetCustomServerInfoStructForHttp(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h
extern char *GetCustomServerInfoStructForHttp_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__HttpXpathSupport_h_ServerLib_0_GetCustomServerInfoStructForHttp(void)
{
	TestLateLinkArgString(&GetCustomServerInfoStructForHttp_LATELINK_ARGSTRING, "void UrlArgumentList * ParseTable * * void * * ", "GetCustomServerInfoStructForHttp");
}

//Stuff relating to LATELINK declaration for GetExtraInfoForLogPrintf(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h
extern char *GetExtraInfoForLogPrintf_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__logging_h_ServerLib_1_GetExtraInfoForLogPrintf(void)
{
	TestLateLinkArgString(&GetExtraInfoForLogPrintf_LATELINK_ARGSTRING, "const char * ", "GetExtraInfoForLogPrintf");
}

//Stuff relating to DEFAULT_LATELINK_GetHeadShot_ReturnInternal(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_GetHeadShot_ReturnInternal(void* arg0, void* arg1, U32 arg2);
typedef void GetHeadShot_ReturnInternal_LATELINK_FPTYPE_INTERNAL(void* arg0, void* arg1, U32 arg2);
GetHeadShot_ReturnInternal_LATELINK_FPTYPE_INTERNAL *GetHeadShot_ReturnInternal_LATELINK_FP = NULL;
char *GetHeadShot_ReturnInternal_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_GetHeadShot_ReturnInternal(void)
{
	GetHeadShot_ReturnInternal_LATELINK_FP = DEFAULT_LATELINK_GetHeadShot_ReturnInternal;
	TestLateLinkArgString(&GetHeadShot_ReturnInternal_LATELINK_ARGSTRING, "void TextParserBinaryBlock * char * U32 ", "GetHeadShot_ReturnInternal");
}
void GetHeadShot_ReturnInternal(void* arg0, void* arg1, U32 arg2)
{
	GetHeadShot_ReturnInternal_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for GetHeadShot_ReturnInternal(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *GetHeadShot_ReturnInternal_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_13_GetHeadShot_ReturnInternal(void)
{
	TestLateLinkArgString(&GetHeadShot_ReturnInternal_LATELINK_ARGSTRING, "void TextParserBinaryBlock * char * U32 ", "GetHeadShot_ReturnInternal");
}

//Stuff relating to DEFAULT_LATELINK_GetLocalTransactionManagerArraySizes(), defined in I:\Night\Night\src\libs\ServerLib\LocalTransactionManager.c
extern void DEFAULT_LATELINK_GetLocalTransactionManagerArraySizes(void* arg0, void* arg1);
typedef void GetLocalTransactionManagerArraySizes_LATELINK_FPTYPE_INTERNAL(void* arg0, void* arg1);
GetLocalTransactionManagerArraySizes_LATELINK_FPTYPE_INTERNAL *GetLocalTransactionManagerArraySizes_LATELINK_FP = NULL;
char *GetLocalTransactionManagerArraySizes_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_GetLocalTransactionManagerArraySizes(void)
{
	GetLocalTransactionManagerArraySizes_LATELINK_FP = DEFAULT_LATELINK_GetLocalTransactionManagerArraySizes;
	TestLateLinkArgString(&GetLocalTransactionManagerArraySizes_LATELINK_ARGSTRING, "void int * int * ", "GetLocalTransactionManagerArraySizes");
}
void GetLocalTransactionManagerArraySizes(void* arg0, void* arg1)
{
	GetLocalTransactionManagerArraySizes_LATELINK_FP(arg0, arg1);
}

//Stuff relating to LATELINK declaration for GetLocalTransactionManagerArraySizes(), defined in I:\Night\Night\src\libs\ServerLib\LocalTransactionManager_Internal.h
extern char *GetLocalTransactionManagerArraySizes_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__LocalTransactionManager_Internal_h_ServerLib_0_GetLocalTransactionManagerArraySizes(void)
{
	TestLateLinkArgString(&GetLocalTransactionManagerArraySizes_LATELINK_ARGSTRING, "void int * int * ", "GetLocalTransactionManagerArraySizes");
}

//Stuff relating to LATELINK declaration for GetLoggingStatusString(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h
extern char *GetLoggingStatusString_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__logging_h_ServerLib_2_GetLoggingStatusString(void)
{
	TestLateLinkArgString(&GetLoggingStatusString_LATELINK_ARGSTRING, "char * ", "GetLoggingStatusString");
}

//Stuff relating to LATELINK declaration for GetLoggingStatusString(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h
extern char *GetLoggingStatusString_LATELINK_ARGSTRING;
static void LL_PROT_ARUN__logging_h_ServerLib_3_GetLoggingStatusString(void)
{
	TestLateLinkArgString(&GetLoggingStatusString_LATELINK_ARGSTRING, "char * ", "GetLoggingStatusString");
}

//Stuff relating to LATELINK_OVERRIDE_GetLoggingStatusString(), defined in I:\Night\Night\src\libs\ServerLib\LogComm.c
extern void* OVERRIDE_LATELINK_GetLoggingStatusString(void);
typedef void* GetLoggingStatusString_LATELINK_FPTYPE_INTERNAL(void);
extern GetLoggingStatusString_LATELINK_FPTYPE_INTERNAL *GetLoggingStatusString_LATELINK_FP;
extern char *GetLoggingStatusString_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_GetLoggingStatusString(void)
{
	GetLoggingStatusString_LATELINK_FP = OVERRIDE_LATELINK_GetLoggingStatusString;
	TestLateLinkArgString(&GetLoggingStatusString_LATELINK_ARGSTRING, "char * ", "GetLoggingStatusString");
}

//Stuff relating to DEFAULT_LATELINK_GetQAControllerTrackerHost(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void* DEFAULT_LATELINK_GetQAControllerTrackerHost(void);
typedef void* GetQAControllerTrackerHost_LATELINK_FPTYPE_INTERNAL(void);
GetQAControllerTrackerHost_LATELINK_FPTYPE_INTERNAL *GetQAControllerTrackerHost_LATELINK_FP = NULL;
char *GetQAControllerTrackerHost_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_GetQAControllerTrackerHost(void)
{
	GetQAControllerTrackerHost_LATELINK_FP = DEFAULT_LATELINK_GetQAControllerTrackerHost;
	TestLateLinkArgString(&GetQAControllerTrackerHost_LATELINK_ARGSTRING, "char * ", "GetQAControllerTrackerHost");
}
void* GetQAControllerTrackerHost(void)
{
	return GetQAControllerTrackerHost_LATELINK_FP();
}

//Stuff relating to LATELINK declaration for GetQAControllerTrackerHost(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *GetQAControllerTrackerHost_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_11_GetQAControllerTrackerHost(void)
{
	TestLateLinkArgString(&GetQAControllerTrackerHost_LATELINK_ARGSTRING, "char * ", "GetQAControllerTrackerHost");
}

//Stuff relating to DEFAULT_LATELINK_GoAheadAndDie_ServerSpecific(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_GoAheadAndDie_ServerSpecific(void);
typedef void GoAheadAndDie_ServerSpecific_LATELINK_FPTYPE_INTERNAL(void);
GoAheadAndDie_ServerSpecific_LATELINK_FPTYPE_INTERNAL *GoAheadAndDie_ServerSpecific_LATELINK_FP = NULL;
char *GoAheadAndDie_ServerSpecific_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_GoAheadAndDie_ServerSpecific(void)
{
	GoAheadAndDie_ServerSpecific_LATELINK_FP = DEFAULT_LATELINK_GoAheadAndDie_ServerSpecific;
	TestLateLinkArgString(&GoAheadAndDie_ServerSpecific_LATELINK_ARGSTRING, "void ", "GoAheadAndDie_ServerSpecific");
}
void GoAheadAndDie_ServerSpecific(void)
{
	GoAheadAndDie_ServerSpecific_LATELINK_FP();
}

//Stuff relating to LATELINK declaration for GoAheadAndDie_ServerSpecific(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *GoAheadAndDie_ServerSpecific_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_6_GoAheadAndDie_ServerSpecific(void)
{
	TestLateLinkArgString(&GoAheadAndDie_ServerSpecific_LATELINK_ARGSTRING, "void ", "GoAheadAndDie_ServerSpecific");
}

//Stuff relating to LATELINK declaration for HandleMonitoringCommandRequestFromPacket(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h
extern char *HandleMonitoringCommandRequestFromPacket_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__HttpXpathSupport_h_ServerLib_1_HandleMonitoringCommandRequestFromPacket(void)
{
	TestLateLinkArgString(&HandleMonitoringCommandRequestFromPacket_LATELINK_ARGSTRING, "void Packet * NetLink * ", "HandleMonitoringCommandRequestFromPacket");
}

//Stuff relating to LATELINK_OVERRIDE_HandleMonitoringCommandRequestFromPacket(), defined in I:\Night\Night\src\libs\ServerLib\RemoteXMLRPC.c
extern void OVERRIDE_LATELINK_HandleMonitoringCommandRequestFromPacket(void* arg0, void* arg1);
typedef void HandleMonitoringCommandRequestFromPacket_LATELINK_FPTYPE_INTERNAL(void* arg0, void* arg1);
extern HandleMonitoringCommandRequestFromPacket_LATELINK_FPTYPE_INTERNAL *HandleMonitoringCommandRequestFromPacket_LATELINK_FP;
extern char *HandleMonitoringCommandRequestFromPacket_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_HandleMonitoringCommandRequestFromPacket(void)
{
	HandleMonitoringCommandRequestFromPacket_LATELINK_FP = OVERRIDE_LATELINK_HandleMonitoringCommandRequestFromPacket;
	TestLateLinkArgString(&HandleMonitoringCommandRequestFromPacket_LATELINK_ARGSTRING, "void Packet * NetLink * ", "HandleMonitoringCommandRequestFromPacket");
}

//Stuff relating to LATELINK_OVERRIDE_IncAntiZombificationCoookie(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void OVERRIDE_LATELINK_IncAntiZombificationCoookie(void);
typedef void IncAntiZombificationCoookie_LATELINK_FPTYPE_INTERNAL(void);
extern IncAntiZombificationCoookie_LATELINK_FPTYPE_INTERNAL *IncAntiZombificationCoookie_LATELINK_FP;
extern char *IncAntiZombificationCoookie_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_IncAntiZombificationCoookie(void)
{
	IncAntiZombificationCoookie_LATELINK_FP = OVERRIDE_LATELINK_IncAntiZombificationCoookie;
	TestLateLinkArgString(&IncAntiZombificationCoookie_LATELINK_ARGSTRING, "void ", "IncAntiZombificationCoookie");
}

//Stuff relating to LATELINK declaration for IsAppServerBasedType(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h
extern char *IsAppServerBasedType_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_ServerLib_3_IsAppServerBasedType(void)
{
	TestLateLinkArgString(&IsAppServerBasedType_LATELINK_ARGSTRING, "bool ", "IsAppServerBasedType");
}

//Stuff relating to LATELINK declaration for IsGameServerBasedType(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h
extern char *IsGameServerBasedType_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_ServerLib_2_IsGameServerBasedType(void)
{
	TestLateLinkArgString(&IsGameServerBasedType_LATELINK_ARGSTRING, "bool ", "IsGameServerBasedType");
}

//Stuff relating to LATELINK declaration for LoggingResizeHappened(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h
extern char *LoggingResizeHappened_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__logging_h_ServerLib_4_LoggingResizeHappened(void)
{
	TestLateLinkArgString(&LoggingResizeHappened_LATELINK_ARGSTRING, "void int int int int ", "LoggingResizeHappened");
}

//Stuff relating to DEFAULT_LATELINK_NewContainerLocallyCreated(), defined in I:\Night\Night\src\libs\ServerLib\objects\objServerTransactions.c
extern void DEFAULT_LATELINK_NewContainerLocallyCreated(GlobalType arg0);
typedef void NewContainerLocallyCreated_LATELINK_FPTYPE_INTERNAL(GlobalType arg0);
NewContainerLocallyCreated_LATELINK_FPTYPE_INTERNAL *NewContainerLocallyCreated_LATELINK_FP = NULL;
char *NewContainerLocallyCreated_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_NewContainerLocallyCreated(void)
{
	NewContainerLocallyCreated_LATELINK_FP = DEFAULT_LATELINK_NewContainerLocallyCreated;
	TestLateLinkArgString(&NewContainerLocallyCreated_LATELINK_ARGSTRING, "void GlobalType ", "NewContainerLocallyCreated");
}
void NewContainerLocallyCreated(GlobalType arg0)
{
	NewContainerLocallyCreated_LATELINK_FP(arg0);
}

//Stuff relating to LATELINK declaration for NewContainerLocallyCreated(), defined in I:\Night\Night\src\libs\ServerLib\objects\objTransactionCommands.h
extern char *NewContainerLocallyCreated_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__objTransactionCommands_h_ServerLib_0_NewContainerLocallyCreated(void)
{
	TestLateLinkArgString(&NewContainerLocallyCreated_LATELINK_ARGSTRING, "void GlobalType ", "NewContainerLocallyCreated");
}

//Stuff relating to LATELINK declaration for ProdSpecificGlobalConfigSetup(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h
extern char *ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_ServerLib_4_ProdSpecificGlobalConfigSetup(void)
{
	TestLateLinkArgString(&ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING, "void ", "ProdSpecificGlobalConfigSetup");
}

//Stuff relating to LATELINK_OVERRIDE_RemotelyVerifyNoReturnLogging(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void OVERRIDE_LATELINK_RemotelyVerifyNoReturnLogging(void* arg0, GlobalType arg1);
typedef void RemotelyVerifyNoReturnLogging_LATELINK_FPTYPE_INTERNAL(void* arg0, GlobalType arg1);
extern RemotelyVerifyNoReturnLogging_LATELINK_FPTYPE_INTERNAL *RemotelyVerifyNoReturnLogging_LATELINK_FP;
extern char *RemotelyVerifyNoReturnLogging_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_RemotelyVerifyNoReturnLogging(void)
{
	RemotelyVerifyNoReturnLogging_LATELINK_FP = OVERRIDE_LATELINK_RemotelyVerifyNoReturnLogging;
	TestLateLinkArgString(&RemotelyVerifyNoReturnLogging_LATELINK_ARGSTRING, "void const char * GlobalType ", "RemotelyVerifyNoReturnLogging");
}

//Stuff relating to DEFAULT_LATELINK_SendDebugTransferMessageToClient(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_SendDebugTransferMessageToClient(U32 arg0, void* arg1);
typedef void SendDebugTransferMessageToClient_LATELINK_FPTYPE_INTERNAL(U32 arg0, void* arg1);
SendDebugTransferMessageToClient_LATELINK_FPTYPE_INTERNAL *SendDebugTransferMessageToClient_LATELINK_FP = NULL;
char *SendDebugTransferMessageToClient_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_SendDebugTransferMessageToClient(void)
{
	SendDebugTransferMessageToClient_LATELINK_FP = DEFAULT_LATELINK_SendDebugTransferMessageToClient;
	TestLateLinkArgString(&SendDebugTransferMessageToClient_LATELINK_ARGSTRING, "void U32 char * ", "SendDebugTransferMessageToClient");
}
void SendDebugTransferMessageToClient(U32 arg0, void* arg1)
{
	SendDebugTransferMessageToClient_LATELINK_FP(arg0, arg1);
}

//Stuff relating to LATELINK declaration for SendDebugTransferMessageToClient(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *SendDebugTransferMessageToClient_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_4_SendDebugTransferMessageToClient(void)
{
	TestLateLinkArgString(&SendDebugTransferMessageToClient_LATELINK_ARGSTRING, "void U32 char * ", "SendDebugTransferMessageToClient");
}

//Stuff relating to DEFAULT_LATELINK_ServerLib_GetNumGSMachines(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern int DEFAULT_LATELINK_ServerLib_GetNumGSMachines(void);
typedef int ServerLib_GetNumGSMachines_LATELINK_FPTYPE_INTERNAL(void);
ServerLib_GetNumGSMachines_LATELINK_FPTYPE_INTERNAL *ServerLib_GetNumGSMachines_LATELINK_FP = NULL;
char *ServerLib_GetNumGSMachines_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_ServerLib_GetNumGSMachines(void)
{
	ServerLib_GetNumGSMachines_LATELINK_FP = DEFAULT_LATELINK_ServerLib_GetNumGSMachines;
	TestLateLinkArgString(&ServerLib_GetNumGSMachines_LATELINK_ARGSTRING, "int ", "ServerLib_GetNumGSMachines");
}
int ServerLib_GetNumGSMachines(void)
{
	return ServerLib_GetNumGSMachines_LATELINK_FP();
}

//Stuff relating to LATELINK declaration for ServerLib_GetNumGSMachines(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *ServerLib_GetNumGSMachines_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_7_ServerLib_GetNumGSMachines(void)
{
	TestLateLinkArgString(&ServerLib_GetNumGSMachines_LATELINK_ARGSTRING, "int ", "ServerLib_GetNumGSMachines");
}

//Stuff relating to LATELINK_OVERRIDE_SetShardClusterOverview(), defined in I:\Night\Night\src\libs\ServerLib\ShardCluster.c
extern void OVERRIDE_LATELINK_SetShardClusterOverview(void* arg0);
typedef void SetShardClusterOverview_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern SetShardClusterOverview_LATELINK_FPTYPE_INTERNAL *SetShardClusterOverview_LATELINK_FP;
extern char *SetShardClusterOverview_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_SetShardClusterOverview(void)
{
	SetShardClusterOverview_LATELINK_FP = OVERRIDE_LATELINK_SetShardClusterOverview;
	TestLateLinkArgString(&SetShardClusterOverview_LATELINK_ARGSTRING, "void Cluster_Overview * ", "SetShardClusterOverview");
}

//Stuff relating to LATELINK declaration for SetShardClusterOverview(), defined in I:\Night\Night\src\libs\ServerLib\pub\ShardCluster.h
extern char *SetShardClusterOverview_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ShardCluster_h_ServerLib_0_SetShardClusterOverview(void)
{
	TestLateLinkArgString(&SetShardClusterOverview_LATELINK_ARGSTRING, "void Cluster_Overview * ", "SetShardClusterOverview");
}

//Stuff relating to LATELINK declaration for ShardClusterOverviewChanged(), defined in I:\Night\Night\src\libs\ServerLib\pub\ShardCluster.h
extern char *ShardClusterOverviewChanged_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ShardCluster_h_ServerLib_1_ShardClusterOverviewChanged(void)
{
	TestLateLinkArgString(&ShardClusterOverviewChanged_LATELINK_ARGSTRING, "void ", "ShardClusterOverviewChanged");
}

//Stuff relating to LATELINK_OVERRIDE_ShardCommon_GetClusterName(), defined in I:\Night\Night\src\libs\ServerLib\ShardCluster.c
extern void* OVERRIDE_LATELINK_ShardCommon_GetClusterName(void);
typedef void* ShardCommon_GetClusterName_LATELINK_FPTYPE_INTERNAL(void);
extern ShardCommon_GetClusterName_LATELINK_FPTYPE_INTERNAL *ShardCommon_GetClusterName_LATELINK_FP;
extern char *ShardCommon_GetClusterName_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ShardCommon_GetClusterName(void)
{
	ShardCommon_GetClusterName_LATELINK_FP = OVERRIDE_LATELINK_ShardCommon_GetClusterName;
	TestLateLinkArgString(&ShardCommon_GetClusterName_LATELINK_ARGSTRING, "char * ", "ShardCommon_GetClusterName");
}

//Stuff relating to DEFAULT_LATELINK_SpecialMapTypeCorruptionAlertHandling(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern bool DEFAULT_LATELINK_SpecialMapTypeCorruptionAlertHandling(void* arg0, void* arg1);
typedef bool SpecialMapTypeCorruptionAlertHandling_LATELINK_FPTYPE_INTERNAL(void* arg0, void* arg1);
SpecialMapTypeCorruptionAlertHandling_LATELINK_FPTYPE_INTERNAL *SpecialMapTypeCorruptionAlertHandling_LATELINK_FP = NULL;
char *SpecialMapTypeCorruptionAlertHandling_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_SpecialMapTypeCorruptionAlertHandling(void)
{
	SpecialMapTypeCorruptionAlertHandling_LATELINK_FP = DEFAULT_LATELINK_SpecialMapTypeCorruptionAlertHandling;
	TestLateLinkArgString(&SpecialMapTypeCorruptionAlertHandling_LATELINK_ARGSTRING, "bool const char * const char * ", "SpecialMapTypeCorruptionAlertHandling");
}
bool SpecialMapTypeCorruptionAlertHandling(void* arg0, void* arg1)
{
	return SpecialMapTypeCorruptionAlertHandling_LATELINK_FP(arg0, arg1);
}

//Stuff relating to LATELINK declaration for SpecialMapTypeCorruptionAlertHandling(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *SpecialMapTypeCorruptionAlertHandling_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_9_SpecialMapTypeCorruptionAlertHandling(void)
{
	TestLateLinkArgString(&SpecialMapTypeCorruptionAlertHandling_LATELINK_ARGSTRING, "bool const char * const char * ", "SpecialMapTypeCorruptionAlertHandling");
}

//Stuff relating to LATELINK_OVERRIDE_SystemIsReadyForAlerts(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern bool OVERRIDE_LATELINK_SystemIsReadyForAlerts(void);
typedef bool SystemIsReadyForAlerts_LATELINK_FPTYPE_INTERNAL(void);
extern SystemIsReadyForAlerts_LATELINK_FPTYPE_INTERNAL *SystemIsReadyForAlerts_LATELINK_FP;
extern char *SystemIsReadyForAlerts_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_SystemIsReadyForAlerts(void)
{
	SystemIsReadyForAlerts_LATELINK_FP = OVERRIDE_LATELINK_SystemIsReadyForAlerts;
	TestLateLinkArgString(&SystemIsReadyForAlerts_LATELINK_ARGSTRING, "bool ", "SystemIsReadyForAlerts");
}

//Stuff relating to DEFAULT_LATELINK_TextureServerReturn(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_TextureServerReturn(int arg0, void* arg1, void* arg2);
typedef void TextureServerReturn_LATELINK_FPTYPE_INTERNAL(int arg0, void* arg1, void* arg2);
TextureServerReturn_LATELINK_FPTYPE_INTERNAL *TextureServerReturn_LATELINK_FP = NULL;
char *TextureServerReturn_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_TextureServerReturn(void)
{
	TextureServerReturn_LATELINK_FP = DEFAULT_LATELINK_TextureServerReturn;
	TestLateLinkArgString(&TextureServerReturn_LATELINK_ARGSTRING, "void int TextParserBinaryBlock * char * ", "TextureServerReturn");
}
void TextureServerReturn(int arg0, void* arg1, void* arg2)
{
	TextureServerReturn_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for TextureServerReturn(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *TextureServerReturn_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_12_TextureServerReturn(void)
{
	TestLateLinkArgString(&TextureServerReturn_LATELINK_ARGSTRING, "void int TextParserBinaryBlock * char * ", "TextureServerReturn");
}

//Stuff relating to DEFAULT_LATELINK_UpdateJobLogging_Internal(), defined in I:\Night\Night\src\libs\ServerLib\JobManagerSupport.c
extern void DEFAULT_LATELINK_UpdateJobLogging_Internal(U32 arg0, void* arg1, void* arg2);
typedef void UpdateJobLogging_Internal_LATELINK_FPTYPE_INTERNAL(U32 arg0, void* arg1, void* arg2);
UpdateJobLogging_Internal_LATELINK_FPTYPE_INTERNAL *UpdateJobLogging_Internal_LATELINK_FP = NULL;
char *UpdateJobLogging_Internal_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_UpdateJobLogging_Internal(void)
{
	UpdateJobLogging_Internal_LATELINK_FP = DEFAULT_LATELINK_UpdateJobLogging_Internal;
	TestLateLinkArgString(&UpdateJobLogging_Internal_LATELINK_ARGSTRING, "void U32 char * char * ", "UpdateJobLogging_Internal");
}
void UpdateJobLogging_Internal(U32 arg0, void* arg1, void* arg2)
{
	UpdateJobLogging_Internal_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for UpdateJobLogging_Internal(), defined in I:\Night\Night\src\libs\ServerLib\pub\JobManagerSupport.h
extern char *UpdateJobLogging_Internal_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__JobManagerSupport_h_ServerLib_0_UpdateJobLogging_Internal(void)
{
	TestLateLinkArgString(&UpdateJobLogging_Internal_LATELINK_ARGSTRING, "void U32 char * char * ", "UpdateJobLogging_Internal");
}

//Stuff relating to LATELINK_OVERRIDE_XMLRPC_DispatchEntityCommand(), defined in I:\Night\Night\src\libs\ServerLib\RemoteXMLRPC.c
extern void* OVERRIDE_LATELINK_XMLRPC_DispatchEntityCommand(void* arg0, void* arg1, ContainerID arg2);
typedef void* XMLRPC_DispatchEntityCommand_LATELINK_FPTYPE_INTERNAL(void* arg0, void* arg1, ContainerID arg2);
extern XMLRPC_DispatchEntityCommand_LATELINK_FPTYPE_INTERNAL *XMLRPC_DispatchEntityCommand_LATELINK_FP;
extern char *XMLRPC_DispatchEntityCommand_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_XMLRPC_DispatchEntityCommand(void)
{
	XMLRPC_DispatchEntityCommand_LATELINK_FP = OVERRIDE_LATELINK_XMLRPC_DispatchEntityCommand;
	TestLateLinkArgString(&XMLRPC_DispatchEntityCommand_LATELINK_ARGSTRING, "XMLMethodResponse * CmdContext * char * ContainerID ", "XMLRPC_DispatchEntityCommand");
}

//Stuff relating to LATELINK_OVERRIDE_XMLRPC_LoadEntity(), defined in I:\Night\Night\src\libs\ServerLib\RemoteXMLRPC.c
extern void OVERRIDE_LATELINK_XMLRPC_LoadEntity(void* arg0, void* arg1);
typedef void XMLRPC_LoadEntity_LATELINK_FPTYPE_INTERNAL(void* arg0, void* arg1);
extern XMLRPC_LoadEntity_LATELINK_FPTYPE_INTERNAL *XMLRPC_LoadEntity_LATELINK_FP;
extern char *XMLRPC_LoadEntity_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_XMLRPC_LoadEntity(void)
{
	XMLRPC_LoadEntity_LATELINK_FP = OVERRIDE_LATELINK_XMLRPC_LoadEntity;
	TestLateLinkArgString(&XMLRPC_LoadEntity_LATELINK_ARGSTRING, "void CmdContext * char * ", "XMLRPC_LoadEntity");
}

//Stuff relating to LATELINK declaration for XPathSupport_GetContainerID(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h
extern char *XPathSupport_GetContainerID_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__HttpXpathSupport_h_ServerLib_3_XPathSupport_GetContainerID(void)
{
	TestLateLinkArgString(&XPathSupport_GetContainerID_LATELINK_ARGSTRING, "ContainerID ", "XPathSupport_GetContainerID");
}

//Stuff relating to LATELINK declaration for XPathSupport_GetServerType(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h
extern char *XPathSupport_GetServerType_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__HttpXpathSupport_h_ServerLib_2_XPathSupport_GetServerType(void)
{
	TestLateLinkArgString(&XPathSupport_GetServerType_LATELINK_ARGSTRING, "GlobalType ", "XPathSupport_GetServerType");
}

//Stuff relating to DEFAULT_LATELINK_dbOnlineCharacterIDFromAccountID(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_dbOnlineCharacterIDFromAccountID(GlobalType arg0, ContainerID arg1, U32 arg2, U32 arg3);
typedef void dbOnlineCharacterIDFromAccountID_LATELINK_FPTYPE_INTERNAL(GlobalType arg0, ContainerID arg1, U32 arg2, U32 arg3);
dbOnlineCharacterIDFromAccountID_LATELINK_FPTYPE_INTERNAL *dbOnlineCharacterIDFromAccountID_LATELINK_FP = NULL;
char *dbOnlineCharacterIDFromAccountID_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_dbOnlineCharacterIDFromAccountID(void)
{
	dbOnlineCharacterIDFromAccountID_LATELINK_FP = DEFAULT_LATELINK_dbOnlineCharacterIDFromAccountID;
	TestLateLinkArgString(&dbOnlineCharacterIDFromAccountID_LATELINK_ARGSTRING, "void GlobalType ContainerID U32 U32 ", "dbOnlineCharacterIDFromAccountID");
}
void dbOnlineCharacterIDFromAccountID(GlobalType arg0, ContainerID arg1, U32 arg2, U32 arg3)
{
	dbOnlineCharacterIDFromAccountID_LATELINK_FP(arg0, arg1, arg2, arg3);
}

//Stuff relating to LATELINK declaration for dbOnlineCharacterIDFromAccountID(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *dbOnlineCharacterIDFromAccountID_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_8_dbOnlineCharacterIDFromAccountID(void)
{
	TestLateLinkArgString(&dbOnlineCharacterIDFromAccountID_LATELINK_ARGSTRING, "void GlobalType ContainerID U32 U32 ", "dbOnlineCharacterIDFromAccountID");
}

//Stuff relating to DEFAULT_LATELINK_dbSubscribeToContainer(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_dbSubscribeToContainer(GlobalType arg0, ContainerID arg1, GlobalType arg2, ContainerID arg3, void* arg4);
typedef void dbSubscribeToContainer_LATELINK_FPTYPE_INTERNAL(GlobalType arg0, ContainerID arg1, GlobalType arg2, ContainerID arg3, void* arg4);
dbSubscribeToContainer_LATELINK_FPTYPE_INTERNAL *dbSubscribeToContainer_LATELINK_FP = NULL;
char *dbSubscribeToContainer_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_dbSubscribeToContainer(void)
{
	dbSubscribeToContainer_LATELINK_FP = DEFAULT_LATELINK_dbSubscribeToContainer;
	TestLateLinkArgString(&dbSubscribeToContainer_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ContainerID const char * ", "dbSubscribeToContainer");
}
void dbSubscribeToContainer(GlobalType arg0, ContainerID arg1, GlobalType arg2, ContainerID arg3, void* arg4)
{
	dbSubscribeToContainer_LATELINK_FP(arg0, arg1, arg2, arg3, arg4);
}

//Stuff relating to LATELINK declaration for dbSubscribeToContainer(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *dbSubscribeToContainer_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_0_dbSubscribeToContainer(void)
{
	TestLateLinkArgString(&dbSubscribeToContainer_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ContainerID const char * ", "dbSubscribeToContainer");
}

//Stuff relating to DEFAULT_LATELINK_dbSubscribeToOnlineContainers(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_dbSubscribeToOnlineContainers(GlobalType arg0, ContainerID arg1, GlobalType arg2);
typedef void dbSubscribeToOnlineContainers_LATELINK_FPTYPE_INTERNAL(GlobalType arg0, ContainerID arg1, GlobalType arg2);
dbSubscribeToOnlineContainers_LATELINK_FPTYPE_INTERNAL *dbSubscribeToOnlineContainers_LATELINK_FP = NULL;
char *dbSubscribeToOnlineContainers_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_dbSubscribeToOnlineContainers(void)
{
	dbSubscribeToOnlineContainers_LATELINK_FP = DEFAULT_LATELINK_dbSubscribeToOnlineContainers;
	TestLateLinkArgString(&dbSubscribeToOnlineContainers_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ", "dbSubscribeToOnlineContainers");
}
void dbSubscribeToOnlineContainers(GlobalType arg0, ContainerID arg1, GlobalType arg2)
{
	dbSubscribeToOnlineContainers_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for dbSubscribeToOnlineContainers(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *dbSubscribeToOnlineContainers_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_2_dbSubscribeToOnlineContainers(void)
{
	TestLateLinkArgString(&dbSubscribeToOnlineContainers_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ", "dbSubscribeToOnlineContainers");
}

//Stuff relating to DEFAULT_LATELINK_dbUnsubscribeFromContainer(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_dbUnsubscribeFromContainer(GlobalType arg0, ContainerID arg1, GlobalType arg2, ContainerID arg3, void* arg4);
typedef void dbUnsubscribeFromContainer_LATELINK_FPTYPE_INTERNAL(GlobalType arg0, ContainerID arg1, GlobalType arg2, ContainerID arg3, void* arg4);
dbUnsubscribeFromContainer_LATELINK_FPTYPE_INTERNAL *dbUnsubscribeFromContainer_LATELINK_FP = NULL;
char *dbUnsubscribeFromContainer_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_dbUnsubscribeFromContainer(void)
{
	dbUnsubscribeFromContainer_LATELINK_FP = DEFAULT_LATELINK_dbUnsubscribeFromContainer;
	TestLateLinkArgString(&dbUnsubscribeFromContainer_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ContainerID const char * ", "dbUnsubscribeFromContainer");
}
void dbUnsubscribeFromContainer(GlobalType arg0, ContainerID arg1, GlobalType arg2, ContainerID arg3, void* arg4)
{
	dbUnsubscribeFromContainer_LATELINK_FP(arg0, arg1, arg2, arg3, arg4);
}

//Stuff relating to LATELINK declaration for dbUnsubscribeFromContainer(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *dbUnsubscribeFromContainer_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_1_dbUnsubscribeFromContainer(void)
{
	TestLateLinkArgString(&dbUnsubscribeFromContainer_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ContainerID const char * ", "dbUnsubscribeFromContainer");
}

//Stuff relating to DEFAULT_LATELINK_dbUnsubscribeFromOnlineContainers(), defined in I:\Night\Night\src\libs\ServerLib\ServerLib.c
extern void DEFAULT_LATELINK_dbUnsubscribeFromOnlineContainers(GlobalType arg0, ContainerID arg1, GlobalType arg2);
typedef void dbUnsubscribeFromOnlineContainers_LATELINK_FPTYPE_INTERNAL(GlobalType arg0, ContainerID arg1, GlobalType arg2);
dbUnsubscribeFromOnlineContainers_LATELINK_FPTYPE_INTERNAL *dbUnsubscribeFromOnlineContainers_LATELINK_FP = NULL;
char *dbUnsubscribeFromOnlineContainers_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_dbUnsubscribeFromOnlineContainers(void)
{
	dbUnsubscribeFromOnlineContainers_LATELINK_FP = DEFAULT_LATELINK_dbUnsubscribeFromOnlineContainers;
	TestLateLinkArgString(&dbUnsubscribeFromOnlineContainers_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ", "dbUnsubscribeFromOnlineContainers");
}
void dbUnsubscribeFromOnlineContainers(GlobalType arg0, ContainerID arg1, GlobalType arg2)
{
	dbUnsubscribeFromOnlineContainers_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for dbUnsubscribeFromOnlineContainers(), defined in I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h
extern char *dbUnsubscribeFromOnlineContainers_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__ServerLib_h_ServerLib_3_dbUnsubscribeFromOnlineContainers(void)
{
	TestLateLinkArgString(&dbUnsubscribeFromOnlineContainers_LATELINK_ARGSTRING, "void GlobalType ContainerID GlobalType ", "dbUnsubscribeFromOnlineContainers");
}

//Stuff relating to LATELINK declaration for getAccountServer(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\net\accountnet.h
extern char *getAccountServer_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__accountnet_h_ServerLib_0_getAccountServer(void)
{
	TestLateLinkArgString(&getAccountServer_LATELINK_ARGSTRING, "char * ", "getAccountServer");
}

//Stuff relating to LATELINK_OVERRIDE_hogWarnImplementationLimitExceeded(), defined in I:\Night\Night\src\libs\ServerLib\svrError.c
extern U32 OVERRIDE_LATELINK_hogWarnImplementationLimitExceeded(void* arg0, U32 arg1, U32 arg2);
typedef U32 hogWarnImplementationLimitExceeded_LATELINK_FPTYPE_INTERNAL(void* arg0, U32 arg1, U32 arg2);
extern hogWarnImplementationLimitExceeded_LATELINK_FPTYPE_INTERNAL *hogWarnImplementationLimitExceeded_LATELINK_FP;
extern char *hogWarnImplementationLimitExceeded_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_hogWarnImplementationLimitExceeded(void)
{
	hogWarnImplementationLimitExceeded_LATELINK_FP = OVERRIDE_LATELINK_hogWarnImplementationLimitExceeded;
	TestLateLinkArgString(&hogWarnImplementationLimitExceeded_LATELINK_ARGSTRING, "U32 const char * U32 U32 ", "hogWarnImplementationLimitExceeded");
}

//Stuff relating to LATELINK declaration for logFlush(), defined in I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h
extern char *logFlush_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__logging_h_ServerLib_0_logFlush(void)
{
	TestLateLinkArgString(&logFlush_LATELINK_ARGSTRING, "void ", "logFlush");
}

//Stuff relating to LATELINK_OVERRIDE_logFlush(), defined in I:\Night\Night\src\libs\ServerLib\LogComm.c
extern void OVERRIDE_LATELINK_logFlush(void);
typedef void logFlush_LATELINK_FPTYPE_INTERNAL(void);
extern logFlush_LATELINK_FPTYPE_INTERNAL *logFlush_LATELINK_FP;
extern char *logFlush_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_logFlush(void)
{
	logFlush_LATELINK_FP = OVERRIDE_LATELINK_logFlush;
	TestLateLinkArgString(&logFlush_LATELINK_ARGSTRING, "void ", "logFlush");
}

//Stuff relating to DEFAULT_LATELINK_objTransactions_MaybeLocallyCopyBackupDataDuringReceive(), defined in I:\Night\Night\src\libs\ServerLib\objects\objServerTransactions.c
extern bool DEFAULT_LATELINK_objTransactions_MaybeLocallyCopyBackupDataDuringReceive(GlobalType arg0, void* arg1, void* arg2);
typedef bool objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_FPTYPE_INTERNAL(GlobalType arg0, void* arg1, void* arg2);
objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_FPTYPE_INTERNAL *objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_FP = NULL;
char *objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_ARGSTRING = NULL;
static void LATELINK_AUTORUN_objTransactions_MaybeLocallyCopyBackupDataDuringReceive(void)
{
	objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_FP = DEFAULT_LATELINK_objTransactions_MaybeLocallyCopyBackupDataDuringReceive;
	TestLateLinkArgString(&objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_ARGSTRING, "bool GlobalType void * void * ", "objTransactions_MaybeLocallyCopyBackupDataDuringReceive");
}
bool objTransactions_MaybeLocallyCopyBackupDataDuringReceive(GlobalType arg0, void* arg1, void* arg2)
{
	return objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_FP(arg0, arg1, arg2);
}

//Stuff relating to LATELINK declaration for objTransactions_MaybeLocallyCopyBackupDataDuringReceive(), defined in I:\Night\Night\src\libs\ServerLib\pub\objTransactions.h
extern char *objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__objTransactions_h_ServerLib_0_objTransactions_MaybeLocallyCopyBackupDataDuringReceive(void)
{
	TestLateLinkArgString(&objTransactions_MaybeLocallyCopyBackupDataDuringReceive_LATELINK_ARGSTRING, "bool GlobalType void * void * ", "objTransactions_MaybeLocallyCopyBackupDataDuringReceive");
}

//Stuff relating to LATELINK_OVERRIDE_resDictGetMissingResourceFromResourceDBIfPossible(), defined in I:\Night\Night\src\libs\ServerLib\ResourceDBSupport.c
extern void OVERRIDE_LATELINK_resDictGetMissingResourceFromResourceDBIfPossible(void* arg0);
typedef void resDictGetMissingResourceFromResourceDBIfPossible_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern resDictGetMissingResourceFromResourceDBIfPossible_LATELINK_FPTYPE_INTERNAL *resDictGetMissingResourceFromResourceDBIfPossible_LATELINK_FP;
extern char *resDictGetMissingResourceFromResourceDBIfPossible_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_resDictGetMissingResourceFromResourceDBIfPossible(void)
{
	resDictGetMissingResourceFromResourceDBIfPossible_LATELINK_FP = OVERRIDE_LATELINK_resDictGetMissingResourceFromResourceDBIfPossible;
	TestLateLinkArgString(&resDictGetMissingResourceFromResourceDBIfPossible_LATELINK_ARGSTRING, "void void * ", "resDictGetMissingResourceFromResourceDBIfPossible");
}


#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
79
0 "AttemptToBootPlayerWithBooter" "void"  "ContainerID"  "U32"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\PlayerBooter.c" 32 0 "void ContainerID U32 char * " 
2 "AttemptToBootPlayerWithBooter" "void"  "ContainerID"  "U32"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\PlayerBooter.h" 33 0 "void ContainerID U32 char * " 
1 "AutoSetting_CmdWasCalled" "void"  "void*"  "enumCmdContextHowCalled"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\AutoSettings.c" 353 1 "void const Cmd * enumCmdContextHowCalled const char * " 
1 "AutoSetting_PacketOfCommandsFromController" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\AutoSettings.c" 327 0 "void Packet * " 
1 "ConnectedToController_ServerSpecificStuff" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 429 1 "void " 
1 "ControllerScript_Failed" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1063 3 "void char * " 
1 "ControllerScript_Succeeded" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1052 2 "void " 
0 "DoYouOwnContainerReturn_Internal" "void"  "int"  "bool"  "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1776 14 "void int bool bool " 
2 "DoYouOwnContainerReturn_Internal" "void"  "int"  "bool"  "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 145 5 "void int bool bool " 
0 "GatewayNotifyLockStatus" "void"  "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\GatewayUtil.c" 33 0 "void bool " 
2 "GatewayNotifyLockStatus" "void"  "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\GatewayUtil.h" 18 0 "void bool " 
1 "GetAntiZombificationCookie" "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1182 7 "U32 " 
2 "GetAppGlobalID" "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h" 713 0 "U32 " 
1 "GetAppGlobalID" "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1157 4 "U32 " 
2 "GetAppIDStr" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h" 720 1 "void * " 
1 "GetAppIDStr" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1162 5 "void * " 
2 "GetCommandsForGenericServerMonitoringPage" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h" 251 4 "void GenericServerInfoForHttpXpath * " 
1 "GetControllerHost" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1176 6 "char * " 
0 "GetControllerTrackerHost" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2156 20 "char * " 
2 "GetControllerTrackerHost" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 204 10 "char * " 
2 "GetCustomServerInfoStructForHttp" "void"  "void*"  "void**"  "void**"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h" 144 0 "void UrlArgumentList * ParseTable * * void * * " 
2 "GetExtraInfoForLogPrintf" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h" 242 1 "const char * " 
0 "GetHeadShot_ReturnInternal" "void"  "void*"  "void*"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2185 23 "void TextParserBinaryBlock * char * U32 " 
2 "GetHeadShot_ReturnInternal" "void"  "void*"  "void*"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 220 13 "void TextParserBinaryBlock * char * U32 " 
0 "GetLocalTransactionManagerArraySizes" "void"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\LocalTransactionManager.c" 1365 0 "void int * int * " 
2 "GetLocalTransactionManagerArraySizes" "void"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\LocalTransactionManager_Internal.h" 211 0 "void int * int * " 
2 "GetLoggingStatusString" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h" 264 2 "char * " 
3 "GetLoggingStatusString" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h" 266 3 "char * " 
1 "GetLoggingStatusString" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\LogComm.c" 762 1 "char * " 
0 "GetQAControllerTrackerHost" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2161 21 "char * " 
2 "GetQAControllerTrackerHost" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 207 11 "char * " 
0 "GoAheadAndDie_ServerSpecific" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1922 15 "void " 
2 "GoAheadAndDie_ServerSpecific" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 149 6 "void " 
2 "HandleMonitoringCommandRequestFromPacket" "void"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h" 171 1 "void Packet * NetLink * " 
1 "HandleMonitoringCommandRequestFromPacket" "void"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\RemoteXMLRPC.c" 26 0 "void Packet * NetLink * " 
1 "IncAntiZombificationCoookie" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1188 8 "void " 
2 "IsAppServerBasedType" "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h" 759 3 "bool " 
2 "IsGameServerBasedType" "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h" 756 2 "bool " 
2 "LoggingResizeHappened" "void"  "int"  "int"  "int"  "int"  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h" 278 4 "void int int int int " 
0 "NewContainerLocallyCreated" "void"  "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\objects\objServerTransactions.c" 792 1 "void GlobalType " 
2 "NewContainerLocallyCreated" "void"  "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\objects\objTransactionCommands.h" 91 0 "void GlobalType " 
2 "ProdSpecificGlobalConfigSetup" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\GlobalTypes.h" 836 4 "void " 
1 "RemotelyVerifyNoReturnLogging" "void"  "void*"  "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2144 19 "void const char * GlobalType " 
0 "SendDebugTransferMessageToClient" "void"  "U32"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1719 13 "void U32 char * " 
2 "SendDebugTransferMessageToClient" "void"  "U32"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 141 4 "void U32 char * " 
0 "ServerLib_GetNumGSMachines" "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2004 16 "int " 
2 "ServerLib_GetNumGSMachines" "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 184 7 "int " 
1 "SetShardClusterOverview" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ShardCluster.c" 46 0 "void Cluster_Overview * " 
2 "SetShardClusterOverview" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ShardCluster.h" 107 0 "void Cluster_Overview * " 
2 "ShardClusterOverviewChanged" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ShardCluster.h" 113 1 "void " 
1 "ShardCommon_GetClusterName" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ShardCluster.c" 103 1 "char * " 
0 "SpecialMapTypeCorruptionAlertHandling" "bool"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 329 0 "bool const char * const char * " 
2 "SpecialMapTypeCorruptionAlertHandling" "bool"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 201 9 "bool const char * const char * " 
1 "SystemIsReadyForAlerts" "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2063 17 "bool " 
0 "TextureServerReturn" "void"  "int"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2167 22 "void int TextParserBinaryBlock * char * " 
2 "TextureServerReturn" "void"  "int"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 211 12 "void int TextParserBinaryBlock * char * " 
0 "UpdateJobLogging_Internal" "void"  "U32"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\JobManagerSupport.c" 182 0 "void U32 char * char * " 
2 "UpdateJobLogging_Internal" "void"  "U32"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\JobManagerSupport.h" 29 0 "void U32 char * char * " 
1 "XMLRPC_DispatchEntityCommand" "void*"  "void*"  "void*"  "ContainerID"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\RemoteXMLRPC.c" 281 1 "XMLMethodResponse * CmdContext * char * ContainerID " 
1 "XMLRPC_LoadEntity" "void"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\RemoteXMLRPC.c" 290 2 "void CmdContext * char * " 
2 "XPathSupport_GetContainerID" "ContainerID"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h" 248 3 "ContainerID " 
2 "XPathSupport_GetServerType" "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\components\HttpXpathSupport.h" 245 2 "GlobalType " 
0 "dbOnlineCharacterIDFromAccountID" "void"  "GlobalType"  "ContainerID"  "U32"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 2131 18 "void GlobalType ContainerID U32 U32 " 
2 "dbOnlineCharacterIDFromAccountID" "void"  "GlobalType"  "ContainerID"  "U32"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 198 8 "void GlobalType ContainerID U32 U32 " 
0 "dbSubscribeToContainer" "void"  "GlobalType"  "ContainerID"  "GlobalType"  "ContainerID"  "void*"  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1663 9 "void GlobalType ContainerID GlobalType ContainerID const char * " 
2 "dbSubscribeToContainer" "void"  "GlobalType"  "ContainerID"  "GlobalType"  "ContainerID"  "void*"  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 124 0 "void GlobalType ContainerID GlobalType ContainerID const char * " 
0 "dbSubscribeToOnlineContainers" "void"  "GlobalType"  "ContainerID"  "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1671 11 "void GlobalType ContainerID GlobalType " 
2 "dbSubscribeToOnlineContainers" "void"  "GlobalType"  "ContainerID"  "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 130 2 "void GlobalType ContainerID GlobalType " 
0 "dbUnsubscribeFromContainer" "void"  "GlobalType"  "ContainerID"  "GlobalType"  "ContainerID"  "void*"  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1667 10 "void GlobalType ContainerID GlobalType ContainerID const char * " 
2 "dbUnsubscribeFromContainer" "void"  "GlobalType"  "ContainerID"  "GlobalType"  "ContainerID"  "void*"  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 127 1 "void GlobalType ContainerID GlobalType ContainerID const char * " 
0 "dbUnsubscribeFromOnlineContainers" "void"  "GlobalType"  "ContainerID"  "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ServerLib.c" 1675 12 "void GlobalType ContainerID GlobalType " 
2 "dbUnsubscribeFromOnlineContainers" "void"  "GlobalType"  "ContainerID"  "GlobalType"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\ServerLib.h" 133 3 "void GlobalType ContainerID GlobalType " 
2 "getAccountServer" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\net\accountnet.h" 30 0 "char * " 
1 "hogWarnImplementationLimitExceeded" "U32"  "void*"  "U32"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\svrError.c" 137 0 "U32 const char * U32 U32 " 
2 "logFlush" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\..\UtilitiesLib\utils\logging.h" 218 0 "void " 
1 "logFlush" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\LogComm.c" 210 0 "void " 
0 "objTransactions_MaybeLocallyCopyBackupDataDuringReceive" "bool"  "GlobalType"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\objects\objServerTransactions.c" 47 0 "bool GlobalType void * void * " 
2 "objTransactions_MaybeLocallyCopyBackupDataDuringReceive" "bool"  "GlobalType"  "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\pub\objTransactions.h" 521 0 "bool GlobalType void * void * " 
1 "resDictGetMissingResourceFromResourceDBIfPossible" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\ServerLib\ResourceDBSupport.c" 227 0 "void void * " 
#endif
