#ifndef __AUTOTRANSDEFS_H_AST_H_
#define __AUTOTRANSDEFS_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \AutoTransDefs.h
//autogeneratednocheckin

//auto-generated staticdefine for enum enumLockType
//autogeneratednocheckin
extern StaticDefineInt enumLockTypeEnum[];

//auto-generated staticdefine for enum enumEarrayIndexType
//autogeneratednocheckin
extern StaticDefineInt enumEarrayIndexTypeEnum[];

extern ParseTable parse_ATRFixedUpLock[];
#define TYPE_parse_ATRFixedUpLock ATRFixedUpLock

extern ParseTable parse_ATRFixedUpEarrayUse[];
#define TYPE_parse_ATRFixedUpEarrayUse ATRFixedUpEarrayUse

extern ParseTable parse_ATRContainerArgDef[];
#define TYPE_parse_ATRContainerArgDef ATRContainerArgDef

extern ParseTable parse_ATR_FuncDef[];
#define TYPE_parse_ATR_FuncDef ATR_FuncDef

#endif
