#ifndef __CATEGORY_H_AST_H_
#define __CATEGORY_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \Category.h
//autogeneratednocheckin

extern ParseTable parse_CategoryName[];
#define TYPE_parse_CategoryName CategoryName

extern ParseTable parse_Category[];
#define TYPE_parse_Category Category

extern ParseTable parse_CategoryList[];
#define TYPE_parse_CategoryList CategoryList

extern ParseTable parse_CategoryMain[];
#define TYPE_parse_CategoryMain CategoryMain

extern ParseTable parse_CategoryListWrapper[];
#define TYPE_parse_CategoryListWrapper CategoryListWrapper

#endif
