#include "textparser.h"

//auto-generated staticdefine for enum enumCommandPrivacy
//autogeneratednocheckin
StaticDefineInt enumCommandPrivacyEnum[] =
{
	DEFINE_INT
	{ "PUBLIC", CMDPRIVACY_PUBLIC},
	{ "PRIVATE", CMDPRIVACY_PRIVATE},
	{ "LAST", CMDPRIVACY_LAST},
	DEFINE_END
};
void autoEnum_fixup_enumCommandPrivacy(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(enumCommandPrivacyEnum, "enumCommandPrivacy");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct CommandArgOverview
#define TYPE_parse_CommandArgOverview CommandArgOverview
ParseTable parse_CommandArgOverview[] =
{
	{ "CommandArgOverview", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(CommandArgOverview), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "ArgName",			TOK_POOL_STRING | TOK_STRING(CommandArgOverview, pArgName, 0), NULL },
	{ "TypeName",			TOK_POOL_STRING | TOK_STRING(CommandArgOverview, pTypeName, 0), NULL },
	{ "StructName",			TOK_POOL_STRING | TOK_STRING(CommandArgOverview, pStructName, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_CommandArgOverview()
{
	int iSize = sizeof(CommandArgOverview);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_CommandArgOverview, iSize, "CommandArgOverview", NULL, "cmdparse_http.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_CommandArgOverview[];
#define TYPE_parse_CommandArgOverview CommandArgOverview
//Structparser.exe autogenerated ParseTable for struct CommandOverview
#define TYPE_parse_CommandOverview CommandOverview
ParseTable parse_CommandOverview[] =
{
	{ "CommandOverview", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(CommandOverview), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "CommandName",			TOK_ESTRING | TOK_STRING(CommandOverview, pCommandName, 0), NULL },
	{ "NotesLink",				TOK_STRING(CommandOverview, pNotesLink, 0), NULL , 0 , "HTML = 1"},
	{ "CommandComment",			TOK_ESTRING | TOK_STRING(CommandOverview, pCommandComment, 0), NULL },
	{ "Execute",				TOK_ESTRING | TOK_STRING(CommandOverview, pExecute, 0), NULL , 0 , "command = 1"},
	{ "AccessLevel",			TOK_AUTOINT(CommandOverview, iAccessLevel, 0), NULL },
	{ "Privacy",				TOK_AUTOINT(CommandOverview, ePrivacy, 0), enumCommandPrivacyEnum },
	{ "ReturnTypeName",			TOK_POOL_STRING | TOK_STRING(CommandOverview, pReturnTypeName, 0), NULL },
	{ "ReturnTypeStructName",	TOK_POOL_STRING | TOK_STRING(CommandOverview, pReturnTypeStructName, 0), NULL },
	{ "Categories",				TOK_POOL_STRING | TOK_STRING(CommandOverview, pCategories, 0), NULL },
	{ "Args",					TOK_STRUCT(CommandOverview, ppArgs, parse_CommandArgOverview) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_CommandOverview()
{
	int iSize = sizeof(CommandOverview);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_CommandOverview, iSize, "CommandOverview", NULL, "cmdparse_http.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_CommandOverview[];
#define TYPE_parse_CommandOverview CommandOverview
//Structparser.exe autogenerated ParseTable for struct CommandCategoryOverview
#define TYPE_parse_CommandCategoryOverview CommandCategoryOverview
ParseTable parse_CommandCategoryOverview[] =
{
	{ "CommandCategoryOverview", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(CommandCategoryOverview), 0, NULL, 0, NULL },
	{ "{",							TOK_START, 0 },
	{ "Title",						TOK_ESTRING | TOK_STRING(CommandCategoryOverview, pTitle, 0), NULL },
	{ "Commands",					TOK_STRUCT(CommandCategoryOverview, ppCommands, parse_CommandOverview) },
	{ "}",							TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_CommandCategoryOverview()
{
	int iSize = sizeof(CommandCategoryOverview);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_CommandCategoryOverview, iSize, "CommandCategoryOverview", NULL, "cmdparse_http.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
