#ifndef __COLOR_H_AST_H_
#define __COLOR_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \Color.h
//autogeneratednocheckin

extern ParseTable parse_ColorDef[];
#define TYPE_parse_ColorDef ColorDef

extern ParseTable parse_ColorDefLoading[];
#define TYPE_parse_ColorDefLoading ColorDefLoading

extern ParseTable parse_Color4[];
#define TYPE_parse_Color4 Color4

#endif
