#include "textparser.h"

//auto-generated staticdefine for enum MeasurementType
//autogeneratednocheckin
StaticDefineInt MeasurementTypeEnum[] =
{
	DEFINE_INT
	{ "Base", kMeasurementType_Base},
	{ "Metric", kMeasurementType_Metric},
	{ "Yards", kMeasurementType_Yards},
	DEFINE_END
};
void autoEnum_fixup_MeasurementType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(MeasurementTypeEnum, "MeasurementType");
}

//auto-generated staticdefine for enum MeasurementSize
//autogeneratednocheckin
StaticDefineInt MeasurementSizeEnum[] =
{
	DEFINE_INT
	{ "Base", kMeasurementSize_Base},
	{ "Small", kMeasurementSize_Small},
	{ "Large", kMeasurementSize_Large},
	DEFINE_END
};
void autoEnum_fixup_MeasurementSize(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(MeasurementSizeEnum, "MeasurementSize");
}
