#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ErrorThreadStruct
#define TYPE_parse_ErrorThreadStruct ErrorThreadStruct
ParseTable parse_ErrorThreadStruct[] =
{
	{ "ErrorThreadStruct", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ErrorThreadStruct), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "DumpFlagsReceived",	TOK_AUTOINT(ErrorThreadStruct, bDumpFlagsReceived, 0), NULL },
	{ "ErrorFlagsReceived",	TOK_AUTOINT(ErrorThreadStruct, bErrorFlagsReceived, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ErrorThreadStruct()
{
	int iSize = sizeof(ErrorThreadStruct);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ErrorThreadStruct, iSize, "ErrorThreadStruct", NULL, "errornet.c", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
