#include "textparser.h"

//auto-generated staticdefine for enum HeatMapType
//autogeneratednocheckin
StaticDefineInt HeatMapTypeEnum[] =
{
	DEFINE_INT
	{ "TIMEDIVISIONS", HEATMAP_TIMEDIVISIONS},
	{ "DOUBLEBUFFERED", HEATMAP_DOUBLEBUFFERED},
	{ "SINGLEBUFFERED", HEATMAP_SINGLEBUFFERED},
	{ "CATEGORIES", HEATMAP_CATEGORIES},
	DEFINE_END
};
void autoEnum_fixup_HeatMapType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(HeatMapTypeEnum, "HeatMapType");
}

//auto-generated staticdefine for enum enumEventCountType
//autogeneratednocheckin
StaticDefineInt enumEventCountTypeEnum[] =
{
	DEFINE_INT
	{ "CURRENTMINUTE", EVENTCOUNT_CURRENTMINUTE},
	{ "LASTFULLMINUTE", EVENTCOUNT_LASTFULLMINUTE},
	{ "LASTFULL15MINUTES", EVENTCOUNT_LASTFULL15MINUTES},
	{ "LASTFULLHOUR", EVENTCOUNT_LASTFULLHOUR},
	{ "LASTFULL6HOURS", EVENTCOUNT_LASTFULL6HOURS},
	{ "LASTFULLDAY", EVENTCOUNT_LASTFULLDAY},
	{ "LASTFULLWEEK", EVENTCOUNT_LASTFULLWEEK},
	{ "COUNT", EVENTCOUNT_COUNT},
	DEFINE_END
};
void autoEnum_fixup_enumEventCountType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(enumEventCountTypeEnum, "enumEventCountType");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct HeatMapColorLevel
#define TYPE_parse_HeatMapColorLevel HeatMapColorLevel
ParseTable parse_HeatMapColorLevel[] =
{
	{ "HeatMapColorLevel", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(HeatMapColorLevel), 0, NULL, 0, NULL },
	{ "MinCount",			TOK_STRUCTPARAM | TOK_AUTOINT(HeatMapColorLevel, iMinCount, 0), NULL },
	{ "r",					TOK_STRUCTPARAM | TOK_AUTOINT(HeatMapColorLevel, r, 0), NULL },
	{ "g",					TOK_STRUCTPARAM | TOK_AUTOINT(HeatMapColorLevel, g, 0), NULL },
	{ "b",					TOK_STRUCTPARAM | TOK_AUTOINT(HeatMapColorLevel, b, 0), NULL },
	{ "\n",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_HeatMapColorLevel()
{
	int iSize = sizeof(HeatMapColorLevel);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_HeatMapColorLevel, iSize, "HeatMapColorLevel", NULL, "EventCountingHeatMap.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_HeatMapColorLevel[];
#define TYPE_parse_HeatMapColorLevel HeatMapColorLevel
//Structparser.exe autogenerated ParseTable for struct HeatMapColorLevels
#define TYPE_parse_HeatMapColorLevels HeatMapColorLevels
ParseTable parse_HeatMapColorLevels[] =
{
	{ "HeatMapColorLevels", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(HeatMapColorLevels), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "Levels",				TOK_STRUCT(HeatMapColorLevels, ppLevels, parse_HeatMapColorLevel) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_HeatMapColorLevels()
{
	int iSize = sizeof(HeatMapColorLevels);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_HeatMapColorLevels, iSize, "HeatMapColorLevels", NULL, "EventCountingHeatMap.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
