#include "textparser.h"

//auto-generated staticdefine for enum TexOptMipFilterType
//autogeneratednocheckin
StaticDefineInt TexOptMipFilterTypeEnum[] =
{
	DEFINE_INT
	{ "Kaiser", MIP_KAISER},
	{ "Box", MIP_BOX},
	{ "Cubic", MIP_CUBIC},
	{ "Mitchell", MIP_MITCHELL},
	DEFINE_END
};
void autoEnum_fixup_TexOptMipFilterType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(TexOptMipFilterTypeEnum, "TexOptMipFilterType");
}

//auto-generated staticdefine for enum TexOptMipSharpening
//autogeneratednocheckin
StaticDefineInt TexOptMipSharpeningEnum[] =
{
	DEFINE_INT
	{ "None", SHARPEN_NONE},
	{ "Negative", SHARPEN_NEGATIVE},
	{ "Lighter", SHARPEN_LIGHTER},
	{ "Darker", SHARPEN_DARKER},
	{ "ContrastMore", SHARPEN_CONTRASTMORE},
	{ "ContrastLess", SHARPEN_CONTRASTLESS},
	{ "Smoothen", SHARPEN_SMOOTHEN},
	{ "SharpenSoft", SHARPEN_SHARPENSOFT},
	{ "SharpenMedium", SHARPEN_SHARPENMEDIUM},
	{ "SharpenStrong", SHARPEN_SHARPENSTRONG},
	{ "FindEdges", SHARPEN_FINDEDGES},
	{ "Contour", SHARPEN_CONTOUR},
	{ "EdgeDetect", SHARPEN_EDGEDETECT},
	{ "EdgeDetectSoft", SHARPEN_EDGEDETECTSOFT},
	{ "Emboss", SHARPEN_EMBOSS},
	{ "MeanRemoval", SHARPEN_MEANREMOVAL},
	DEFINE_END
};
void autoEnum_fixup_TexOptMipSharpening(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(TexOptMipSharpeningEnum, "TexOptMipSharpening");
}

//auto-generated staticdefine for enum TexOptQuality
//autogeneratednocheckin
StaticDefineInt TexOptQualityEnum[] =
{
	DEFINE_INT
	{ "Production", QUALITY_PRODUCTION},
	{ "Lowest", QUALITY_LOWEST},
	{ "Medium", QUALITY_MEDIUM},
	{ "Highest", QUALITY_HIGHEST},
	DEFINE_END
};
void autoEnum_fixup_TexOptQuality(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(TexOptQualityEnum, "TexOptQuality");
}

//auto-generated staticdefine for enum TexOptCompressionType
//autogeneratednocheckin
StaticDefineInt TexOptCompressionTypeEnum[] =
{
	DEFINE_INT
	{ "Auto", COMPRESSION_AUTO},
	{ "DXT1", COMPRESSION_DXT1},
	{ "DXT5", COMPRESSION_DXT5},
	{ "HalfResTrueColor", COMPRESSION_HALFRES_TRUECOLOR},
	{ "Uncompressed16bpp", COMPRESSION_1555},
	{ "DXTifLarge", COMPRESSION_DXT_IF_LARGE},
	{ "U8", COMPRESSION_U8},
	{ "DXT5nm", COMPRESSION_DXT5NM},
	{ "TrueColor", COMPRESSION_TRUECOLOR},
	DEFINE_END
};
void autoEnum_fixup_TexOptCompressionType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(TexOptCompressionTypeEnum, "TexOptCompressionType");
}

//auto-generated staticdefine for enum RdrTexType
//autogeneratednocheckin
StaticDefineInt RdrTexTypeEnum[] =
{
	DEFINE_INT
	{ "RTEX_1D", RTEX_1D},
	{ "RTEX_2D", RTEX_2D},
	{ "RTEX_3D", RTEX_3D},
	{ "RTEX_CUBEMAP", RTEX_CUBEMAP},
	DEFINE_END
};
void autoEnum_fixup_RdrTexType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(RdrTexTypeEnum, "RdrTexType");
}
