#ifndef __MEMLEAKTRACKING_H_AST_H_
#define __MEMLEAKTRACKING_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \MemLeakTracking.h
//autogeneratednocheckin

extern ParseTable parse_MemLeakCategory[];
#define TYPE_parse_MemLeakCategory MemLeakCategory

#endif
