#ifndef __MEMORYMONITOR_H_AST_H_
#define __MEMORYMONITOR_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \MemoryMonitor.h
//autogeneratednocheckin

extern ParseTable parse_ModuleMemOperationStats[];
#define TYPE_parse_ModuleMemOperationStats ModuleMemOperationStats

#endif
