#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct MemoryBudgetFileEntry
#define TYPE_parse_MemoryBudgetFileEntry MemoryBudgetFileEntry
ParseTable parse_MemoryBudgetFileEntry[] =
{
	{ "MemoryBudgetFileEntry", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MemoryBudgetFileEntry), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "filename",				TOK_STRING(MemoryBudgetFileEntry, filename, 0), NULL },
	{ "size",					TOK_AUTOINT(MemoryBudgetFileEntry, size, 0), NULL },
	{ "count",					TOK_AUTOINT(MemoryBudgetFileEntry, count, 0), NULL },
	{ "traffic",				TOK_AUTOINT(MemoryBudgetFileEntry, traffic, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MemoryBudgetFileEntry()
{
	int iSize = sizeof(MemoryBudgetFileEntry);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MemoryBudgetFileEntry, iSize, "MemoryBudgetFileEntry", NULL, "MemoryBudget.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ModuleMemOperationStats[];
#define TYPE_parse_ModuleMemOperationStats ModuleMemOperationStats
extern ParseTable parse_MemoryBudget[];
#define TYPE_parse_MemoryBudget MemoryBudget
//Structparser.exe autogenerated ParseTable for struct MemoryBudget
#define TYPE_parse_MemoryBudget MemoryBudget
ParseTable parse_MemoryBudget[] =
{
	{ "MemoryBudget", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(MemoryBudget), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Name",			TOK_POOL_STRING | TOK_STRING(MemoryBudget, module, 0), NULL },
	{ "Size",			TOK_F32(MemoryBudget, allowed_mb, 0), NULL },
	{ "SizeSecondary",	TOK_F32(MemoryBudget, allowed_mb_secondary, 0), NULL },
	{ "stats",			TOK_STRUCT(MemoryBudget, stats, parse_ModuleMemOperationStats) },
	{ "Budget",			TOK_STRUCT(MemoryBudget, subBudgets, parse_MemoryBudget) },
	{ "End",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_MemoryBudget()
{
	int iSize = sizeof(MemoryBudget);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_MemoryBudget, iSize, "MemoryBudget", NULL, "MemoryBudget.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
