#ifndef __MEMTRACKLOG_H_AST_H_
#define __MEMTRACKLOG_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \MemTrackLog.h
//autogeneratednocheckin

extern ParseTable parse_MemTrackOpsStatistic[];
#define TYPE_parse_MemTrackOpsStatistic MemTrackOpsStatistic

extern ParseTable parse_MemTrackOpsInfo[];
#define TYPE_parse_MemTrackOpsInfo MemTrackOpsInfo

#endif
