#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct PixelCircleCoords
#define TYPE_parse_PixelCircleCoords PixelCircleCoords
ParseTable parse_PixelCircleCoords[] =
{
	{ "PixelCircleCoords", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PixelCircleCoords), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "x",					TOK_AUTOINT(PixelCircleCoords, x, 0), NULL },
	{ "y",					TOK_AUTOINT(PixelCircleCoords, y, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_PixelCircleCoords()
{
	int iSize = sizeof(PixelCircleCoords);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_PixelCircleCoords, iSize, "PixelCircleCoords", NULL, "PixelCircle.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_PixelCircleCoords[];
#define TYPE_parse_PixelCircleCoords PixelCircleCoords
//Structparser.exe autogenerated ParseTable for struct PixelCircle
#define TYPE_parse_PixelCircle PixelCircle
ParseTable parse_PixelCircle[] =
{
	{ "PixelCircle", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(PixelCircle), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "Coords",			TOK_STRUCT(PixelCircle, ppCoords, parse_PixelCircleCoords) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_PixelCircle()
{
	int iSize = sizeof(PixelCircle);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_PixelCircle, iSize, "PixelCircle", NULL, "PixelCircle.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
