#ifndef __SENTRYSERVERCOMM_C_AST_H_
#define __SENTRYSERVERCOMM_C_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \SentryServerComm.c
//autogeneratednocheckin

extern ParseTable parse_DeferredPacketForSentryServer[];
#define TYPE_parse_DeferredPacketForSentryServer DeferredPacketForSentryServer

extern ParseTable parse_GetFileCRCCache[];
#define TYPE_parse_GetFileCRCCache GetFileCRCCache

extern ParseTable parse_DeferredSendSingleTarget[];
#define TYPE_parse_DeferredSendSingleTarget DeferredSendSingleTarget

extern ParseTable parse_DeferredSendSingleFile[];
#define TYPE_parse_DeferredSendSingleFile DeferredSendSingleFile

extern ParseTable parse_SentryServerCommDeferredSendHandle[];
#define TYPE_parse_SentryServerCommDeferredSendHandle SentryServerCommDeferredSendHandle

extern ParseTable parse_GetDirectoryContentsCache[];
#define TYPE_parse_GetDirectoryContentsCache GetDirectoryContentsCache

#endif
