#include "textparser.h"

//auto-generated staticdefine for enum SimpleCpuUsageThread
//autogeneratednocheckin
StaticDefineInt SimpleCpuUsageThreadEnum[] =
{
	DEFINE_INT
	{ "GAMESERVER_MAIN", SIMPLE_CPU_USAGE_THREAD_GAMESERVER_MAIN},
	{ "GAMESERVER_SENDTOCLIENT", SIMPLE_CPU_USAGE_THREAD_GAMESERVER_SENDTOCLIENT},
	{ "MMBG_MAIN", SIMPLE_CPU_USAGE_THREAD_MMBG_MAIN},
	{ "WORLDCOLL_MAIN", SIMPLE_CPU_USAGE_THREAD_WORLDCOLL_MAIN},
	{ "PKTSEND", SIMPLE_CPU_USAGE_THREAD_PKTSEND},
	DEFINE_END
};
void autoEnum_fixup_SimpleCpuUsageThread(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(SimpleCpuUsageThreadEnum, "SimpleCpuUsageThread");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct SimpleCpuThreadData
#define TYPE_parse_SimpleCpuThreadData SimpleCpuThreadData
ParseTable parse_SimpleCpuThreadData[] =
{
	{ "SimpleCpuThreadData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(SimpleCpuThreadData), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "Thread",					TOK_AUTOINT(SimpleCpuThreadData, thread, 0), SimpleCpuUsageThreadEnum },
	{ "TimerCpuTicks64",		TOK_AUTOINT(SimpleCpuThreadData, s64TimerCpuTicks, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
extern ThreadSafeMemoryPool tsmemPoolSimpleCpuThreadData;
int autoStruct_fixup_SimpleCpuThreadData()
{
	int iSize = sizeof(SimpleCpuThreadData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_SimpleCpuThreadData, iSize, "SimpleCpuThreadData", NULL, "SimpleCpuUsage.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	ParserSetTPIUsesThreadSafeMemPool(parse_SimpleCpuThreadData, &tsmemPoolSimpleCpuThreadData);
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_SimpleCpuThreadData[];
#define TYPE_parse_SimpleCpuThreadData SimpleCpuThreadData
//Structparser.exe autogenerated ParseTable for struct SimpleCpuFrameData
#define TYPE_parse_SimpleCpuFrameData SimpleCpuFrameData
ParseTable parse_SimpleCpuFrameData[] =
{
	{ "SimpleCpuFrameData", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(SimpleCpuFrameData), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "SimpleCpuThreadData",	TOK_STRUCT(SimpleCpuFrameData, eaSimpleCpuThreadData, parse_SimpleCpuThreadData) },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_SimpleCpuFrameData()
{
	int iSize = sizeof(SimpleCpuFrameData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_SimpleCpuFrameData, iSize, "SimpleCpuFrameData", NULL, "SimpleCpuUsage.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_SimpleCpuFrameData[];
#define TYPE_parse_SimpleCpuFrameData SimpleCpuFrameData
//Structparser.exe autogenerated ParseTable for struct SimpleCpuData
#define TYPE_parse_SimpleCpuData SimpleCpuData
ParseTable parse_SimpleCpuData[] =
{
	{ "SimpleCpuData", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(SimpleCpuData), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "MaxCyclesFor30Fps",	TOK_F32(SimpleCpuData, fMaxCyclesFor30Fps, 0), NULL },
	{ "NextFrameIndex",		TOK_AUTOINT(SimpleCpuData, iNextFrameIndex, 0), NULL },
	{ "SimpleCpuFrameData",	TOK_STRUCT(SimpleCpuData, eaSimpleCpuFrameData, parse_SimpleCpuFrameData) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_SimpleCpuData()
{
	int iSize = sizeof(SimpleCpuData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_SimpleCpuData, iSize, "SimpleCpuData", NULL, "SimpleCpuUsage.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
