#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct StringListStruct
#define TYPE_parse_StringListStruct StringListStruct
ParseTable parse_StringListStruct[] =
{
	{ "StringListStruct", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(StringListStruct), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "list",				TOK_STRINGARRAY(StringListStruct, list), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_StringListStruct()
{
	int iSize = sizeof(StringListStruct);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_StringListStruct, iSize, "StringListStruct", NULL, "StringUtil.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
