#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct StructMod
#define TYPE_parse_StructMod StructMod
ParseTable parse_StructMod[] =
{
	{ "StructMod", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(StructMod), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "column",		TOK_AUTOINT(StructMod, column, 0), NULL },
	{ "idx",		TOK_AUTOINT(StructMod, idx, 0), NULL },
	{ "id",			TOK_AUTOINT(StructMod, id, 0), NULL },
	{ "val",		TOK_STRING(StructMod, val, 0), NULL },
	{ "name",		TOK_STRING(StructMod, name, 0), NULL },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_StructMod()
{
	int iSize = sizeof(StructMod);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_StructMod, iSize, "StructMod", NULL, "StructMod.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
