#include "textparser.h"
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct TriviaData
#define TYPE_parse_TriviaData TriviaData
ParseTable parse_TriviaData[] =
{
	{ "TriviaData", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(TriviaData), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "Key",		TOK_PERSIST | TOK_ESTRING | TOK_KEY | TOK_STRING(TriviaData, pKey, 0), NULL },
	{ "pKey",		TOK_REDUNDANTNAME | TOK_PERSIST | TOK_ESTRING | TOK_STRING(TriviaData, pKey, 0), NULL },
	{ "pKey",		TOK_REDUNDANTNAME | TOK_PERSIST | TOK_ESTRING | TOK_STRING(TriviaData, pKey, 0), NULL },
	{ "Val",		TOK_STRUCTPARAM | TOK_PERSIST | TOK_ESTRING | TOK_STRING(TriviaData, pVal, 0), NULL , 0 , "XML_ENCODE_BASE64 = 1"},
	{ "pVal",		TOK_REDUNDANTNAME | TOK_STRUCTPARAM | TOK_PERSIST | TOK_ESTRING | TOK_STRING(TriviaData, pVal, 0), NULL , 0 , "XML_ENCODE_BASE64 = 1"},
	{ "pVal",		TOK_REDUNDANTNAME | TOK_STRUCTPARAM | TOK_PERSIST | TOK_ESTRING | TOK_STRING(TriviaData, pVal, 0), NULL , 0 , "XML_ENCODE_BASE64 = 1"},
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_TriviaData()
{
	int iSize = sizeof(TriviaData);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_TriviaData, iSize, "TriviaData", NULL, "trivia.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_TriviaData[];
#define TYPE_parse_TriviaData TriviaData
//Structparser.exe autogenerated ParseTable for struct TriviaList
#define TYPE_parse_TriviaList TriviaList
ParseTable parse_TriviaList[] =
{
	{ "TriviaList", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(TriviaList), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "triviaDatas",	TOK_PERSIST | TOK_STRUCT(TriviaList, triviaDatas, parse_TriviaData) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_TriviaList()
{
	int iSize = sizeof(TriviaList);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_TriviaList, iSize, "TriviaList", NULL, "trivia.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_TriviaList[];
#define TYPE_parse_TriviaList TriviaList
//Structparser.exe autogenerated ParseTable for struct TriviaListMultiple
#define TYPE_parse_TriviaListMultiple TriviaListMultiple
ParseTable parse_TriviaListMultiple[] =
{
	{ "TriviaListMultiple", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(TriviaListMultiple), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "triviaLists",		TOK_PERSIST | TOK_STRUCT(TriviaListMultiple, triviaLists, parse_TriviaList) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_TriviaListMultiple()
{
	int iSize = sizeof(TriviaListMultiple);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_TriviaListMultiple, iSize, "TriviaListMultiple", NULL, "trivia.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct TriviaOverviewValue
#define TYPE_parse_TriviaOverviewValue TriviaOverviewValue
ParseTable parse_TriviaOverviewValue[] =
{
	{ "TriviaOverviewValue", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(TriviaOverviewValue), 0, NULL, 0, NULL },
	{ "{",						TOK_START, 0 },
	{ "pVal",					TOK_PERSIST | TOK_ESTRING | TOK_STRING(TriviaOverviewValue, pVal, 0), NULL , 0 , "XML_ENCODE_BASE64 = 1"},
	{ "uCount",					TOK_PERSIST | TOK_AUTOINT(TriviaOverviewValue, uCount, 0), NULL },
	{ "}",						TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_TriviaOverviewValue()
{
	int iSize = sizeof(TriviaOverviewValue);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_TriviaOverviewValue, iSize, "TriviaOverviewValue", NULL, "trivia.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_TriviaOverviewValue[];
#define TYPE_parse_TriviaOverviewValue TriviaOverviewValue
//Structparser.exe autogenerated ParseTable for struct TriviaOverviewItem
#define TYPE_parse_TriviaOverviewItem TriviaOverviewItem
ParseTable parse_TriviaOverviewItem[] =
{
	{ "TriviaOverviewItem", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(TriviaOverviewItem), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "pKey",				TOK_PERSIST | TOK_ESTRING | TOK_KEY | TOK_STRING(TriviaOverviewItem, pKey, 0), NULL },
	{ "ppValues",			TOK_PERSIST | TOK_STRUCT(TriviaOverviewItem, ppValues, parse_TriviaOverviewValue) },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_TriviaOverviewItem()
{
	int iSize = sizeof(TriviaOverviewItem);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_TriviaOverviewItem, iSize, "TriviaOverviewItem", NULL, "trivia.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_TriviaOverviewItem[];
#define TYPE_parse_TriviaOverviewItem TriviaOverviewItem
//Structparser.exe autogenerated ParseTable for struct TriviaOverview
#define TYPE_parse_TriviaOverview TriviaOverview
ParseTable parse_TriviaOverview[] =
{
	{ "TriviaOverview", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(TriviaOverview), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "ppTriviaItems",	TOK_PERSIST | TOK_STRUCT(TriviaOverview, ppTriviaItems, parse_TriviaOverviewItem) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_TriviaOverview()
{
	int iSize = sizeof(TriviaOverview);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_TriviaOverview, iSize, "TriviaOverview", NULL, "trivia.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct CommentEntry
#define TYPE_parse_CommentEntry CommentEntry
ParseTable parse_CommentEntry[] =
{
	{ "CommentEntry", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(CommentEntry), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "pDesc",			TOK_PERSIST | TOK_STRING(CommentEntry, pDesc, 0), NULL },
	{ "pIP",			TOK_PERSIST | TOK_STRING(CommentEntry, pIP, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_CommentEntry()
{
	int iSize = sizeof(CommentEntry);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_CommentEntry, iSize, "CommentEntry", NULL, "trivia.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
