#include "textparser.h"

//auto-generated staticdefine for enum FileSpecFlag
//autogeneratednocheckin
StaticDefineInt FileSpecFlagEnum[] =
{
	DEFINE_INT
	{ "NotRequired", FILESPEC_NOT_REQUIRED},
	{ "Mirrored", FILESPEC_MIRRORED_OUTSIDE_HOGGS},
	{ "NoWarn", FILESPEC_NOWARN},
	{ "Included", FILESPEC_INCLUDED},
	DEFINE_END
};
void autoEnum_fixup_FileSpecFlag(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(FileSpecFlagEnum, "FileSpecFlag");
}

//auto-generated staticdefine for enum ControlSpecType
//autogeneratednocheckin
StaticDefineInt ControlSpecTypeEnum[] =
{
	DEFINE_INT
	{ "Incl", CONTROLSPEC_INCLUDED},
	{ "Excl", CONTROLSPEC_EXCLUDED},
	{ "Bins", CONTROLSPEC_BINFILES},
	DEFINE_END
};
void autoEnum_fixup_ControlSpecType(void)
{
	static bool bOnce = false; if (bOnce) return; bOnce = true;
	RegisterNamedStaticDefine(ControlSpecTypeEnum, "ControlSpecType");
}
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct Spec
#define TYPE_parse_Spec Spec
ParseTable parse_Spec[] =
{
	{ "Spec", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(Spec), 0, NULL, 0, NULL },
	{ "{",		TOK_START, 0 },
	{ "spec",	TOK_STRING(Spec, spec, 0), NULL },
	{ "}",		TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_Spec()
{
	int iSize = sizeof(Spec);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_Spec, iSize, "Spec", NULL, "patchfilespec.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_Spec[];
#define TYPE_parse_Spec Spec
//Structparser.exe autogenerated ParseTable for struct HogSpec
#define TYPE_parse_HogSpec HogSpec
ParseTable parse_HogSpec[] =
{
	{ "HogSpec", 			TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(HogSpec), 0, NULL, 0, NULL },
	{ "{",					TOK_START, 0 },
	{ "filename",			TOK_STRING(HogSpec, filename, 0), NULL },
	{ "strip",				TOK_STRING(HogSpec, strip, 0), NULL },
	{ "filespecs",			TOK_STRUCT(HogSpec, filespecs, parse_Spec) },
	{ "mirror_stripped",	TOK_AUTOINT(HogSpec, mirror_stripped, 0), NULL },
	{ "}",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_HogSpec()
{
	int iSize = sizeof(HogSpec);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_HogSpec, iSize, "HogSpec", NULL, "patchfilespec.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct FlagSpecLine
#define TYPE_parse_FlagSpecLine FlagSpecLine
ParseTable parse_FlagSpecLine[] =
{
	{ "FlagSpecLine", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(FlagSpecLine), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "spec",			TOK_STRING(FlagSpecLine, spec, 0), NULL },
	{ "Exclude",		TOK_AUTOINT(FlagSpecLine, exclude, 0), NULL },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_FlagSpecLine()
{
	int iSize = sizeof(FlagSpecLine);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_FlagSpecLine, iSize, "FlagSpecLine", NULL, "patchfilespec.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_FlagSpecLine[];
#define TYPE_parse_FlagSpecLine FlagSpecLine
//Structparser.exe autogenerated ParseTable for struct FlagSpec
#define TYPE_parse_FlagSpec FlagSpec
ParseTable parse_FlagSpec[] =
{
	{ "FlagSpec", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(FlagSpec), 0, NULL, 0, NULL },
	{ "{",			TOK_START, 0 },
	{ "flag",		TOK_AUTOINT(FlagSpec, flag, 0), FileSpecFlagEnum },
	{ "filespecs",	TOK_STRUCT(FlagSpec, filespecs, parse_FlagSpecLine) },
	{ "}",			TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_FlagSpec()
{
	int iSize = sizeof(FlagSpec);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_FlagSpec, iSize, "FlagSpec", NULL, "patchfilespec.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
//Structparser.exe autogenerated ParseTable for struct ControlSpecLine
#define TYPE_parse_ControlSpecLine ControlSpecLine
ParseTable parse_ControlSpecLine[] =
{
	{ "ControlSpecLine", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ControlSpecLine), 0, NULL, 0, NULL },
	{ "spec",				TOK_STRUCTPARAM | TOK_STRING(ControlSpecLine, spec, 0), NULL },
	{ "type",				TOK_STRUCTPARAM | TOK_AUTOINT(ControlSpecLine, type, 0), ControlSpecTypeEnum },
	{ "\n",					TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ControlSpecLine()
{
	int iSize = sizeof(ControlSpecLine);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ControlSpecLine, iSize, "ControlSpecLine", NULL, "patchfilespec.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_ControlSpecLine[];
#define TYPE_parse_ControlSpecLine ControlSpecLine
//Structparser.exe autogenerated ParseTable for struct ControlSpec
#define TYPE_parse_ControlSpec ControlSpec
ParseTable parse_ControlSpec[] =
{
	{ "ControlSpec", 	TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(ControlSpec), 0, NULL, 0, NULL },
	{ "{",				TOK_START, 0 },
	{ "spec",			TOK_STRUCT(ControlSpec, specs, parse_ControlSpecLine) },
	{ "}",				TOK_END, 0 },
	{ "", 0, 0 }
};
int autoStruct_fixup_ControlSpec()
{
	int iSize = sizeof(ControlSpec);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_ControlSpec, iSize, "ControlSpec", NULL, "patchfilespec.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
//autogeneratednocheckin
extern ParseTable parse_HogSpec[];
#define TYPE_parse_HogSpec HogSpec
extern ParseTable parse_FlagSpec[];
#define TYPE_parse_FlagSpec FlagSpec
extern ParseTable parse_ControlSpec[];
#define TYPE_parse_ControlSpec ControlSpec
//Structparser.exe autogenerated ParseTable for struct FileSpecs
#define TYPE_parse_FileSpecs FileSpecs
ParseTable parse_FileSpecs[] =
{
	{ "FileSpecs", 		TOK_IGNORE | TOK_PARSETABLE_INFO, sizeof(FileSpecs), 0, NULL, 0, NULL },
	{ "hoggspecs",		TOK_STRUCT(FileSpecs, hoggspecs, parse_HogSpec) },
	{ "flagspecs",		TOK_STRUCT(FileSpecs, flagspecs, parse_FlagSpec) },
	{ "controlspecs",	TOK_EMBEDDEDSTRUCT(FileSpecs, controlspecs, parse_ControlSpec)},
	{ "", 0, 0 }
};
int autoStruct_fixup_FileSpecs()
{
	int iSize = sizeof(FileSpecs);
	static char once = 0;
	if (once) return 0;
	once = 1;
	ParserSetTableInfo(parse_FileSpecs, iSize, "FileSpecs", NULL, "patchfilespec.h", 0 | SETTABLEINFO_ALLOW_CRC_CACHING  );
	return 0;
};
