#ifndef __PCL_TYPEDEFS_H_AST_H_
#define __PCL_TYPEDEFS_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \pcl_typedefs.h
//autogeneratednocheckin

//auto-generated staticdefine for enum PCL_ErrorCode
//autogeneratednocheckin
extern StaticDefineInt PCL_ErrorCodeEnum[];

//auto-generated staticdefine for enum PCL_LogLevel
//autogeneratednocheckin
extern StaticDefineInt PCL_LogLevelEnum[];

extern ParseTable parse_XferStateInfo[];
#define TYPE_parse_XferStateInfo XferStateInfo

extern ParseTable parse_PatchProcessStats[];
#define TYPE_parse_PatchProcessStats PatchProcessStats

#endif
