#ifndef __AIAMBIENT_H_AST_H_
#define __AIAMBIENT_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \aiAmbient.h
//autogeneratednocheckin

extern ParseTable parse_AIAmbient[];
#define TYPE_parse_AIAmbient AIAmbient

#endif
