//This file contains data and prototypes for latelinks. It is autogenerated by StructParser

//autogeneratednocheckin
#include "LateLinkSupport.h"

//Stuff relating to LATELINK declaration for GameSpecific_CaptainCostumeFixup(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h
extern char *GameSpecific_CaptainCostumeFixup_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_AILib_3_GameSpecific_CaptainCostumeFixup(void)
{
	TestLateLinkArgString(&GameSpecific_CaptainCostumeFixup_LATELINK_ARGSTRING, "void Entity * ", "GameSpecific_CaptainCostumeFixup");
}

//Stuff relating to LATELINK declaration for GameSpecific_CreateShieldFX(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h
extern char *GameSpecific_CreateShieldFX_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_AILib_2_GameSpecific_CreateShieldFX(void)
{
	TestLateLinkArgString(&GameSpecific_CreateShieldFX_LATELINK_ARGSTRING, "void Entity * ", "GameSpecific_CreateShieldFX");
}

//Stuff relating to LATELINK declaration for GameSpecific_HolsterRequest(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h
extern char *GameSpecific_HolsterRequest_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_AILib_1_GameSpecific_HolsterRequest(void)
{
	TestLateLinkArgString(&GameSpecific_HolsterRequest_LATELINK_ARGSTRING, "void Entity * Entity * bool ", "GameSpecific_HolsterRequest");
}

//Stuff relating to LATELINK declaration for GetAppGlobalID(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h
extern char *GetAppGlobalID_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_AILib_0_GetAppGlobalID(void)
{
	TestLateLinkArgString(&GetAppGlobalID_LATELINK_ARGSTRING, "U32 ", "GetAppGlobalID");
}

//Stuff relating to LATELINK declaration for GetAppIDStr(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h
extern char *GetAppIDStr_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_AILib_1_GetAppIDStr(void)
{
	TestLateLinkArgString(&GetAppIDStr_LATELINK_ARGSTRING, "void * ", "GetAppIDStr");
}

//Stuff relating to LATELINK declaration for IsAppServerBasedType(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h
extern char *IsAppServerBasedType_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_AILib_3_IsAppServerBasedType(void)
{
	TestLateLinkArgString(&IsAppServerBasedType_LATELINK_ARGSTRING, "bool ", "IsAppServerBasedType");
}

//Stuff relating to LATELINK declaration for IsGameServerBasedType(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h
extern char *IsGameServerBasedType_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_AILib_2_IsGameServerBasedType(void)
{
	TestLateLinkArgString(&IsGameServerBasedType_LATELINK_ARGSTRING, "bool ", "IsGameServerBasedType");
}

//Stuff relating to LATELINK declaration for ProdSpecificGlobalConfigSetup(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h
extern char *ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__GlobalTypes_h_AILib_4_ProdSpecificGlobalConfigSetup(void)
{
	TestLateLinkArgString(&ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING, "void ", "ProdSpecificGlobalConfigSetup");
}

//Stuff relating to LATELINK declaration for aiShouldAvoidBeacon(), defined in I:\Night\Night\src\libs\AILib\..\WorldLib\pub\beaconPath.h
extern char *aiShouldAvoidBeacon_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__beaconPath_h_AILib_0_aiShouldAvoidBeacon(void)
{
	TestLateLinkArgString(&aiShouldAvoidBeacon_LATELINK_ARGSTRING, "int U32 Beacon * F32 ", "aiShouldAvoidBeacon");
}

//Stuff relating to LATELINK_OVERRIDE_aiShouldAvoidBeacon(), defined in I:\Night\Night\src\libs\AILib\aiAvoid.c
extern int OVERRIDE_LATELINK_aiShouldAvoidBeacon(U32 arg0, void* arg1, F32 arg2);
typedef int aiShouldAvoidBeacon_LATELINK_FPTYPE_INTERNAL(U32 arg0, void* arg1, F32 arg2);
extern aiShouldAvoidBeacon_LATELINK_FPTYPE_INTERNAL *aiShouldAvoidBeacon_LATELINK_FP;
extern char *aiShouldAvoidBeacon_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_aiShouldAvoidBeacon(void)
{
	aiShouldAvoidBeacon_LATELINK_FP = OVERRIDE_LATELINK_aiShouldAvoidBeacon;
	TestLateLinkArgString(&aiShouldAvoidBeacon_LATELINK_ARGSTRING, "int U32 Beacon * F32 ", "aiShouldAvoidBeacon");
}

//Stuff relating to LATELINK declaration for aiShouldAvoidLine(), defined in I:\Night\Night\src\libs\AILib\..\WorldLib\pub\beaconPath.h
extern char *aiShouldAvoidLine_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__beaconPath_h_AILib_1_aiShouldAvoidLine(void)
{
	TestLateLinkArgString(&aiShouldAvoidLine_LATELINK_ARGSTRING, "int U32 Beacon * const Vec3 Beacon * F32 BeaconPartitionData * ", "aiShouldAvoidLine");
}

//Stuff relating to LATELINK_OVERRIDE_aiShouldAvoidLine(), defined in I:\Night\Night\src\libs\AILib\aiAvoid.c
extern int OVERRIDE_LATELINK_aiShouldAvoidLine(U32 arg0, void* arg1, Vec3 arg2, void* arg3, F32 arg4, void* arg5);
typedef int aiShouldAvoidLine_LATELINK_FPTYPE_INTERNAL(U32 arg0, void* arg1, Vec3 arg2, void* arg3, F32 arg4, void* arg5);
extern aiShouldAvoidLine_LATELINK_FPTYPE_INTERNAL *aiShouldAvoidLine_LATELINK_FP;
extern char *aiShouldAvoidLine_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_aiShouldAvoidLine(void)
{
	aiShouldAvoidLine_LATELINK_FP = OVERRIDE_LATELINK_aiShouldAvoidLine;
	TestLateLinkArgString(&aiShouldAvoidLine_LATELINK_ARGSTRING, "int U32 Beacon * const Vec3 Beacon * F32 BeaconPartitionData * ", "aiShouldAvoidLine");
}

//Stuff relating to LATELINK declaration for character_ProjSpecificCombatLevelChange(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\Character.h
extern char *character_ProjSpecificCombatLevelChange_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Character_h_AILib_1_character_ProjSpecificCombatLevelChange(void)
{
	TestLateLinkArgString(&character_ProjSpecificCombatLevelChange_LATELINK_ARGSTRING, "void Entity * bool char * * ", "character_ProjSpecificCombatLevelChange");
}

//Stuff relating to LATELINK declaration for character_ProjSpecificDeathLogString(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\Character.h
extern char *character_ProjSpecificDeathLogString_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Character_h_AILib_0_character_ProjSpecificDeathLogString(void)
{
	TestLateLinkArgString(&character_ProjSpecificDeathLogString_LATELINK_ARGSTRING, "void Entity * bool char * * ", "character_ProjSpecificDeathLogString");
}

//Stuff relating to LATELINK declaration for ent_FixupProjectSpecificPowers(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\PowerTree.h
extern char *ent_FixupProjectSpecificPowers_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__PowerTree_h_AILib_1_ent_FixupProjectSpecificPowers(void)
{
	TestLateLinkArgString(&ent_FixupProjectSpecificPowers_LATELINK_ARGSTRING, "void Entity * ", "ent_FixupProjectSpecificPowers");
}

//Stuff relating to LATELINK declaration for ent_NeedsProjectSpecificPowersFixup(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\PowerTree.h
extern char *ent_NeedsProjectSpecificPowersFixup_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__PowerTree_h_AILib_0_ent_NeedsProjectSpecificPowersFixup(void)
{
	TestLateLinkArgString(&ent_NeedsProjectSpecificPowersFixup_LATELINK_ARGSTRING, "bool Entity * ", "ent_NeedsProjectSpecificPowersFixup");
}

//Stuff relating to LATELINK declaration for entity_CreateProjSpecificLogString(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h
extern char *entity_CreateProjSpecificLogString_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_AILib_0_entity_CreateProjSpecificLogString(void)
{
	TestLateLinkArgString(&entity_CreateProjSpecificLogString_LATELINK_ARGSTRING, "char * Entity * ", "entity_CreateProjSpecificLogString");
}

//Stuff relating to LATELINK declaration for exprFuncHelperBaseEntFromEntityRef(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h
extern char *exprFuncHelperBaseEntFromEntityRef_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Expression_h_AILib_3_exprFuncHelperBaseEntFromEntityRef(void)
{
	TestLateLinkArgString(&exprFuncHelperBaseEntFromEntityRef_LATELINK_ARGSTRING, "Entity * int U32 ", "exprFuncHelperBaseEntFromEntityRef");
}

//Stuff relating to LATELINK declaration for exprFuncHelperEntIsAlive(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h
extern char *exprFuncHelperEntIsAlive_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Expression_h_AILib_4_exprFuncHelperEntIsAlive(void)
{
	TestLateLinkArgString(&exprFuncHelperEntIsAlive_LATELINK_ARGSTRING, "int Entity * ", "exprFuncHelperEntIsAlive");
}

//Stuff relating to LATELINK declaration for exprFuncHelperGetEntRef(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h
extern char *exprFuncHelperGetEntRef_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Expression_h_AILib_2_exprFuncHelperGetEntRef(void)
{
	TestLateLinkArgString(&exprFuncHelperGetEntRef_LATELINK_ARGSTRING, "U32 Entity * ", "exprFuncHelperGetEntRef");
}

//Stuff relating to LATELINK declaration for exprFuncHelperShouldExcludeFromEntArray(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h
extern char *exprFuncHelperShouldExcludeFromEntArray_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Expression_h_AILib_0_exprFuncHelperShouldExcludeFromEntArray(void)
{
	TestLateLinkArgString(&exprFuncHelperShouldExcludeFromEntArray_LATELINK_ARGSTRING, "int Entity * ", "exprFuncHelperShouldExcludeFromEntArray");
}

//Stuff relating to LATELINK_OVERRIDE_exprFuncHelperShouldExcludeFromEntArray(), defined in I:\Night\Night\src\libs\AILib\aiLib.c
extern int OVERRIDE_LATELINK_exprFuncHelperShouldExcludeFromEntArray(void* arg0);
typedef int exprFuncHelperShouldExcludeFromEntArray_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern exprFuncHelperShouldExcludeFromEntArray_LATELINK_FPTYPE_INTERNAL *exprFuncHelperShouldExcludeFromEntArray_LATELINK_FP;
extern char *exprFuncHelperShouldExcludeFromEntArray_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_exprFuncHelperShouldExcludeFromEntArray(void)
{
	exprFuncHelperShouldExcludeFromEntArray_LATELINK_FP = OVERRIDE_LATELINK_exprFuncHelperShouldExcludeFromEntArray;
	TestLateLinkArgString(&exprFuncHelperShouldExcludeFromEntArray_LATELINK_ARGSTRING, "int Entity * ", "exprFuncHelperShouldExcludeFromEntArray");
}

//Stuff relating to LATELINK declaration for exprFuncHelperShouldIncludeInEntArray(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h
extern char *exprFuncHelperShouldIncludeInEntArray_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Expression_h_AILib_1_exprFuncHelperShouldIncludeInEntArray(void)
{
	TestLateLinkArgString(&exprFuncHelperShouldIncludeInEntArray_LATELINK_ARGSTRING, "int Entity * int int ", "exprFuncHelperShouldIncludeInEntArray");
}

//Stuff relating to LATELINK declaration for gameSpecificFixup(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h
extern char *gameSpecificFixup_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_AILib_4_gameSpecificFixup(void)
{
	TestLateLinkArgString(&gameSpecificFixup_LATELINK_ARGSTRING, "void Entity * ", "gameSpecificFixup");
}

//Stuff relating to LATELINK declaration for gameSpecificFixup_Version(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h
extern char *gameSpecificFixup_Version_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_AILib_5_gameSpecificFixup_Version(void)
{
	TestLateLinkArgString(&gameSpecificFixup_Version_LATELINK_ARGSTRING, "int ", "gameSpecificFixup_Version");
}

//Stuff relating to LATELINK declaration for gameSpecificPreLoginFixup_Version(), defined in I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h
extern char *gameSpecificPreLoginFixup_Version_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__Entity_h_AILib_6_gameSpecificPreLoginFixup_Version(void)
{
	TestLateLinkArgString(&gameSpecificPreLoginFixup_Version_LATELINK_ARGSTRING, "int ", "gameSpecificPreLoginFixup_Version");
}

//Stuff relating to LATELINK declaration for getAccountServer(), defined in I:\Night\Night\src\libs\AILib\..\UtilitiesLib\net\accountnet.h
extern char *getAccountServer_LATELINK_ARGSTRING;
static void LL_DECL_ARUN__accountnet_h_AILib_0_getAccountServer(void)
{
	TestLateLinkArgString(&getAccountServer_LATELINK_ARGSTRING, "char * ", "getAccountServer");
}


#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
27
2 "GameSpecific_CaptainCostumeFixup" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h" 1398 3 "void Entity * " 
2 "GameSpecific_CreateShieldFX" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h" 1394 2 "void Entity * " 
2 "GameSpecific_HolsterRequest" "void"  "void*"  "void*"  "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h" 1391 1 "void Entity * Entity * bool " 
2 "GetAppGlobalID" "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h" 713 0 "U32 " 
2 "GetAppIDStr" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h" 720 1 "void * " 
2 "IsAppServerBasedType" "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h" 759 3 "bool " 
2 "IsGameServerBasedType" "bool"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h" 756 2 "bool " 
2 "ProdSpecificGlobalConfigSetup" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\GlobalTypes.h" 836 4 "void " 
2 "aiShouldAvoidBeacon" "int"  "U32"  "void*"  "F32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\WorldLib\pub\beaconPath.h" 255 0 "int U32 Beacon * F32 " 
1 "aiShouldAvoidBeacon" "int"  "U32"  "void*"  "F32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\aiAvoid.c" 236 0 "int U32 Beacon * F32 " 
2 "aiShouldAvoidLine" "int"  "U32"  "void*"  "Vec3"  "void*"  "F32"  "void*"  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\WorldLib\pub\beaconPath.h" 259 1 "int U32 Beacon * const Vec3 Beacon * F32 BeaconPartitionData * " 
1 "aiShouldAvoidLine" "int"  "U32"  "void*"  "Vec3"  "void*"  "F32"  "void*"  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\aiAvoid.c" 295 1 "int U32 Beacon * const Vec3 Beacon * F32 BeaconPartitionData * " 
2 "character_ProjSpecificCombatLevelChange" "void"  "void*"  "bool"  "void**"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\Character.h" 1587 1 "void Entity * bool char * * " 
2 "character_ProjSpecificDeathLogString" "void"  "void*"  "bool"  "void**"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\Character.h" 1585 0 "void Entity * bool char * * " 
2 "ent_FixupProjectSpecificPowers" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\PowerTree.h" 1045 1 "void Entity * " 
2 "ent_NeedsProjectSpecificPowersFixup" "bool"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Combat\PowerTree.h" 1042 0 "bool Entity * " 
2 "entity_CreateProjSpecificLogString" "void*"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h" 1387 0 "char * Entity * " 
2 "exprFuncHelperBaseEntFromEntityRef" "void*"  "int"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h" 394 3 "Entity * int U32 " 
2 "exprFuncHelperEntIsAlive" "int"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h" 397 4 "int Entity * " 
2 "exprFuncHelperGetEntRef" "U32"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h" 391 2 "U32 Entity * " 
2 "exprFuncHelperShouldExcludeFromEntArray" "int"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h" 385 0 "int Entity * " 
1 "exprFuncHelperShouldExcludeFromEntArray" "int"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\aiLib.c" 551 0 "int Entity * " 
2 "exprFuncHelperShouldIncludeInEntArray" "int"  "void*"  "int"  "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\components\Expression.h" 388 1 "int Entity * int int " 
2 "gameSpecificFixup" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h" 1504 4 "void Entity * " 
2 "gameSpecificFixup_Version" "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h" 1507 5 "int " 
2 "gameSpecificPreLoginFixup_Version" "int"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\..\CrossRoads\Common\Entity\Entity.h" 1510 6 "int " 
2 "getAccountServer" "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "I:\Night\Night\src\libs\AILib\..\UtilitiesLib\net\accountnet.h" 30 0 "char * " 
#endif
