#ifndef __COMBATPOOL_H_AST_H_
#define __COMBATPOOL_H_AST_H_
#pragma once
GCC_SYSTEM
#include "textparser.h"
//This file is autogenerated and contains TextParserInfo prototypes from \CombatPool.h
//autogeneratednocheckin

//auto-generated staticdefine for enum CombatPoolPoint
//autogeneratednocheckin
extern StaticDefineInt CombatPoolPointEnum[];

//auto-generated staticdefine for enum CombatPoolBound
//autogeneratednocheckin
extern StaticDefineInt CombatPoolBoundEnum[];

//auto-generated staticdefine for enum CombatPoolUnit
//autogeneratednocheckin
extern StaticDefineInt CombatPoolUnitEnum[];

extern ParseTable parse_CombatPoolTarget[];
#define TYPE_parse_CombatPoolTarget CombatPoolTarget

extern ParseTable parse_CombatPoolDef[];
#define TYPE_parse_CombatPoolDef CombatPoolDef

#endif
